### ISSUE TITLE
Book 3 Section 12.1 Listing 33:  have a typo in the book

### ISSUE THREAD

**Issue by shadow-lr** [RayTracing/raytracing.github.io#1002]
url is https://raytracing.github.io/books/RayTracingTheRestOfYourLife.html#cleaninguppdfmanagement/diffuseversusspecular
![image](https://user-images.githubusercontent.com/58605529/162881041-6c38529f-37a4-4bc4-bef4-5484cd96a187.png)

The correct way to write it should be:
```cpp
srec.pdf_ptr = make_shared<cosine_pdf>(rec.normal);
```
![image](https://user-images.githubusercontent.com/58605529/162881150-449db8fa-5816-431c-bff0-7b9bb840e43e.png)

**Comment by hollasch** [comment]
This is fixed in the latest v4.0.0-alpha.2 release.
