### ISSUE TITLE
Change BVH Creation algorithm

### ISSUE THREAD

**Issue by trevordblack** [RayTracing/raytracing.github.io#1007]
At present, the text outlines the algorithm for creating a BVH structure:

```
1. randomly choose an axis
2. sort the primitives (using std::sort)
3. put half in each subtree
```

We should consider replacing--either outright, or in a revision chapter--random axis choice with using the axis with the longest extent.

This appears to be the first "good-enough" solution that you find in the literature, once you go beyond random axis.

**Comment by hollasch** [comment]
@trevordblack — I propose that we punt this to a post v4.0.0 release.

Hmmm, never mind. Am I correct in thinking that this is trivial?

**Comment by hollasch** [comment]
@trevordblack — would it look something like this?

```
bvh_node(const std::vector<shared_ptr<hittable>>& src_objects, size_t start, size_t end) {
    auto objects = src_objects; // Create a modifiable array of the source scene objects

    interval axis_extent[3];
    for (int object_index=start; object_index <= end; ++object_index) {
        auto object_bbox = src_objects[object_index].bounding_box();
        for (int axis=0; axis < 3; ++axis) {
            axis_extent[axis] = interval(axis_extent[axis], object_bbox.axis(axis));
        }
    }

    int axis;

    if (axis_extent[0] < axis_extent[1])
        axis = axis_extent[1] < axis_extent[2] ? 2 : 1;
    else
        axis = axis_extent[0] < axis_extent[2] ? 2 : 0;

    ...
```

**Comment by hollasch** [comment]
Ok, I think I've got it. 18% speedup. PR incoming.
