### ISSUE TITLE
CSS: Image N is not auto incremented and is italicised

### ISSUE THREAD

**Issue by trevordblack** [RayTracing/raytracing.github.io#1009]
This seems to be a specific design choice in markdeep, but:

Figures, listings, and tables are automatically numbered.
We hackily increment images as we go along with "image N:"

But, figures and listings are formatted:
**Figure N:** _This is a figure_
**Listing N:** _This is some code_

Whereas images are
_Image N: This is an image_ 

where `Figure N`/`Listing N` are bolded but not italicized
and `Image N:` is italicized but not bold

I can't seem to get `Image N` to not be italicised

**Comment by trevordblack** [comment]
Maybe we should drop image numbering?

**Comment by hollasch** [comment]
The Markdeep output is generally well-structured enough to have at it with CSS. Probably just need to mess with it more. I'll tackle this.

**Comment by hollasch** [comment]
Done.
