### ISSUE TITLE
Typo in Book 3 Listing 11

### ISSUE THREAD

**Issue by jdietz224** [RayTracing/raytracing.github.io#1011]
Book 3 Listing 11:
`scattered = ray(rec.p, unit_vector(direction), r_in.time());`

returns compile error that direction has not been declared in this scope.
I think it was meant to be "scatter_direction". At least it seemed to work fine for me if I changed it to that.

**Comment by hollasch** [comment]
Currently listing 19 in `dev-major`, fixed.
