### ISSUE TITLE
Infinite loop in book 1, simple diffusion material

### ISSUE THREAD

**Issue by genmeblog** [RayTracing/raytracing.github.io#1012]
I go through the book 1 (book1-review branch) reimplementing it in Clojure.

Listing 40 introduces recursive ray casting which is infinite. When `world.hit` hits a sphere, `rec.p` contains point on sphere. Next hit check always returns the same `rec.p`.
The reason is that `ray_t.contains(...)` in listing 28, checks closed interval (listing 25) instead of open one (as it was defined in listing 15)

**Comment by genmeblog** [comment]
Fixing shadow acne solves this problem but is introduced later (listing 43)

**Comment by hollasch** [comment]
Oof; good catch -- thanks.

**Comment by hollasch** [comment]
See related issue #875 .
