### ISSUE TITLE
Book 1 - the order of diffuse spheres

### ISSUE THREAD

**Issue by genmeblog** [RayTracing/raytracing.github.io#1013]
book1-review branch. The order of images is incorect imho.

Image 7 - looks like after gamma correction, which is introduced later in the book
Image 8 and 9 - the shadows are much darker than in the next image, my render of image 9 produces below result (ligher shadows):
![ch08b](https://user-images.githubusercontent.com/38646601/165834320-2c177fd7-bc66-4d3e-8332-11a0873d5aa7.jpg)

I use different method of genereting random vector from the ball (normalized gaussians rather than rejection), so maybe this is the reason. However there is a followin statement below image 10: "The shadows are more pronounced after the change". This statement suggests that images 8 and 9 should have ligher shadows, not darker.

**Comment by hollasch** [comment]
Ref #778

**Comment by tysonliddell** [comment]
I bumped into this same issue and banged my head against the wall trying to get the same result as the book.

Image 7 appears shows the result after some kind of enhancement has been applied, but the result the code gives you at this stage is much darker. This can be confirmed by checking out this repo at 516fb5c4b2fbe5b7646dfdcc06f8ddc3bec891f2 (master branch at the time of writing) and applying [this patch](https://gist.github.com/tysonliddell/0aed3040b4094d54939b074b6a1ba358) to remove code added in later sections. This yields the images below.

#### No gamma correction or shadow acne fix applied (this is what Image 7 should look like)
![no-gamma](https://user-images.githubusercontent.com/20079016/224579956-809064b0-f99c-4d9d-93d0-c65b5aa0300a.jpg)

#### Gamma correction applied
![with_gamma](https://user-images.githubusercontent.com/20079016/224580232-297e9b35-c4b6-4ad9-9b8d-9a9d85388f6b.jpg)

#### Removing shadow acne
![with_gamma_and_sa](https://user-images.githubusercontent.com/20079016/224580248-d2f5ae06-5f62-4ecc-9ba7-d664d4706b65.jpg)

**Comment by tysonliddell** [comment]
Relates to https://github.com/RayTracing/raytracing.github.io/issues/875.
