### ISSUE TITLE
Book 3: Listing 30 Isotropic changes are never used

### ISSUE THREAD

**Issue by genmeblog** [RayTracing/raytracing.github.io#1020]
The end of the Ch.8 includes changes in Isotropic material, which is never used in this state. Later it's redefined again in Listing 46.

**Comment by hollasch** [comment]
It may not be used in any of our example, but listing 29 (_Isotropic material, modified for importance sampling_) is definitely a setup for the change in listing 46 (_New isotropic scatter() method_). I don't see that we need to change anything.

**Comment by hollasch** [comment]
Perhaps this is just more of the issues around #1019, which seems like the same thing.
