### ISSUE TITLE
Handling Surface Acne in section 12.6 seems wrong.

### ISSUE THREAD

**Issue by jeffreyrosenbluth** [RayTracing/raytracing.github.io#1021]
https://github.com/RayTracing/raytracing.github.io/blob/04d80ed895c7115ff2a417eadc935a85bcea1163/src/common/color.h#L24

Replacing NaNs here with 0.0 will simply replace a pixel with one thats the wrong color. E.g. rgb = (NaN, Nan, Nan) will be black in the final image. When I use the glass sphere in my cornell box I still get acne. As you describe in the text 'pixel_color' is the average over many samples so the NaN fix should take place before the averaging. Probably here: https://github.com/RayTracing/raytracing.github.io/blob/04d80ed895c7115ff2a417eadc935a85bcea1163/src/TheRestOfYourLife/scene.h#L34  So that the black is averaged in. I tested this in my ray tracer which is written in Rust and it seems to work. Technically I think it would be better to just throw out this ray but this would require keeping track of the number of "good" rays to reduce the number of samples_per_pixel in the denominator.

**Comment by trevordblack** [comment]
I believe this was already fixed in the `dev-major` branch, but if not, an issue might be floating around for this somewhere.

**Comment by jeffreyrosenbluth** [comment]
The `def-major` branch still has this error. But you are right, issue 979 https://github.com/RayTracing/raytracing.github.io/issues/979#issue-1097036531 discuss this problem

Thanks for the speedy response!

**Comment by trevordblack** [comment]
If I'm in a meeting at the office, you get a speedy response!

**Comment by hollasch** [comment]
Let's close this issue and consolidate discussion in #979.
