### ISSUE TITLE
Book 1 suggestion for .h and .cpp seperation

### ISSUE THREAD

**Issue by abroadhurstDistology** [RayTracing/raytracing.github.io#1026]
I encountered an issue where the complier kept throwing "already declared" errors however there was no issue with the code but the defined 'hit' functions for sphere and hittable_list needed to be placed the the .cpp files instead of inside the h guard. I'm working with visual studio so it may be an IDE issue only, I can't say that I'm experience enough to know the exact issue that cause it. It may be worth placing a note in chapter 6.6 regarding it.

**Comment by trevordblack** [comment]
This is a complicated one for us to fix.

We made the decision to have only one object file (.cc or .cpp) being the main file, and having everything else live inside of header files (.h).

This is a bit of an idiosyncratic pattern as the usual pattern to avoid the errors you raise above is to have the absolute minimum defined in each header file, don't include header files in header files, and define everything in .cpp object files of classes.

We probably aren't going to do that. The reason we went with the code pattern that we did is that it is the most programming language agnostic pattern that we could have come up with.

The idea of header files and object files is very much a C/C++ specific programming pattern and is found in almost no other modern programming language (none that I'm aware of). So leaning into the necessary C++ patterns to avoid dumb IDE errors would make our book less usable by anyone else using any other programming language.

Something for us to think about, but this might just be one of those cases where people have to debug around around our choices :/

**Comment by hollasch** [comment]
Another consideration is that separating the header and implementation files would multiply a lot of our code listings, as we'd need to have a listing (or listing change) for declarations, and another one for implementations. We _could_ adopt a new strategy of somehow having a hybrid listing to address this, but I don't think it's worth the effort.

Unless some new angle comes up for this issue, I'm going to close this out for now.
