### ISSUE TITLE
[book 3] Is sampling a light from a point where said light can't be seen correct?

### ISSUE THREAD

**Issue by miguelggcc** [RayTracing/raytracing.github.io#1036]
As the title says, wouldn't biasing rays towards a light in places located in the shadow of that light significantly increase the variance there, to the point it would need an ridiculous amount of computing time to eventually converge? Shadow rays would easily solve this problem.

Hopefully this image clarifies what I mean:
![image](https://user-images.githubusercontent.com/100235899/179579157-b6e473d9-4eaf-45e5-a612-6994a3e3bea8.png)

**Comment by trevordblack** [comment]
You are correct.
Biasing rays toward a light in an area of the scene that does not have visibility of the light will increase variance.
You can definitely add shadow rays as an alternative.

With that said, this isn't really something that we can address in the book as the content of book 3 is meant to educate the reader on an underlying understanding of PDFs. We don't have the time to rewrite for variance & shadow rays.

This is something that we are actively thinking about. But I don't know the extent to which we can/will address

**Comment by hollasch** [comment]
From the first chapter in the book:
> I don’t cover shadow rays (deciding instead to make rays more likely to go toward lights), nor do I cover bidirectional methods, Metropolis methods, or photon mapping. You'll find many of these techniques in the so-called “serious ray tracers”, but they are not covered here because it is more important to cover the concepts, math, and terms of the field. I think of this book as a deep exposure that should be your first of many, and it will equip you with some of the concepts, math, and terms that you'll need in order to study these and other interesting techniques.

And from the introduction to chapter 9:
> The problem with sampling uniformly over all directions is that lights are no more likely to be sampled than any arbirary or unimportant direction. We could use shadow rays to solve for the direct lighting at any given point. Instead, I’ll just use a PDF that sends more rays to the light. We can then turn around and change that PDF to send more rays in whatever direction we want.

Finally, chapter 11 has another large paragraph dedicated to this topic:
> The mixture-density approach is an alternative to having more traditional shadow rays. These are rays that check for an unobstructed path from an intersection point to a given light source. Rays that intersect an object between a point and a given light source indicate that the intersection point is in the shadow of that particular light source. The mixture-density approach is something that I personally prefer, because in addition to lights, you can sample windows or bright cracks under doors or whatever else you think might be bright — or important. But you'll still see shadow rays in most professional path tracers. Typically they'll have a predefined number of shadow rays (e.g 1, 4, 8, 16) where over the course of rendering, at each place where the path tracing ray intersects, they'll send these terminal shadow rays to random lights in the scene to determine if the intersection is lit by that random light. The intersection will either be lit by that light, or completely in shadow, where more shadow rays lead to a more accurate illumination. After all of the shadow rays terminate (either at a light or at an occluding surface), the inital path tracing ray continues on and more shadow rays are sent at the next intersection. You can't tell the shadow rays what is important, you can only tell them what is emissive, so shadow rays work best on simpler scenes that don't have overly complicated photon distribution. That said, shadow rays terminate at the first thing they run into and don't bounce around, so one shadow ray is cheaper than one path tracing ray, which is the reason that you'll typically see a lot more shadow rays than path tracing rays (e.g 1, 4, 8, 16). You could choose shadow rays over mixture-density in a more restricted scene; that’s a personal design preference. Shadow rays tend to be cheaper for a crude result than mixture-density and is becoming increasingly common in realtime.

We may add more material in the future covering shadow rays, but it will not be in books 1–3.
