### ISSUE TITLE
where the "Hermite cubic" come from?

### ISSUE THREAD

**Issue by fdcumt** [RayTracing/raytracing.github.io#1050]
![image](https://user-images.githubusercontent.com/10294860/183796145-bf5b4fd4-a7b7-4cf8-a2ad-33cb6db5906f.png)

I don`t know the code come from where, can you tell me the theory? Or paste a link?

thanks

**Comment by alkanen** [comment]
It's also known as the Hermite spline (of type 01), and it's used to make sure that both the value and the first derivative at the intersection points are the same on both sides, which reduces the grid-like appearance:
https://en.wikipedia.org/wiki/Cubic_Hermite_spline

It's commonly used as an ease function for all sorts of things, like animations to make sure one animation segment smoothly transitions into the next without any jerky motion.
