### ISSUE TITLE
Book 1 Chapter 7.2 `dev_major`: `render` part of code has bug (sphere shape is unstable)

### ISSUE THREAD

**Issue by LollipopFt** [RayTracing/raytracing.github.io#1065]
with this code:
https://github.com/RayTracing/raytracing.github.io/blob/806ab499cc220d044f4abff57fe01612bd9a6e82/books/RayTracingInOneWeekend.html#L1626-L1633

image output is unstable:
`1st run`
![image](https://user-images.githubusercontent.com/62802897/187018469-6d528fc2-3e74-48ba-aa0b-728e609b704d.png)
`2nd run`
![image](https://user-images.githubusercontent.com/62802897/187018477-cd8f3da7-ce6c-4432-aeae-5c12e3c003ef.png)
`3rd run`
![image](https://user-images.githubusercontent.com/62802897/187018489-792ac6fb-b126-48bf-9ef4-df614e2dfc24.png)

and many more. notice how unstable the bottom and top of the sphere is. however, with the original code in `master`, a stable image is produced:
`1st run`
![image](https://user-images.githubusercontent.com/62802897/187018548-5cf2dcc2-761e-499c-be48-e144faa03373.png)
`2nd run`
![image](https://user-images.githubusercontent.com/62802897/187018560-e9c435e6-ec0c-4691-b381-fe505577fb89.png)
`3rd run`
![image](https://user-images.githubusercontent.com/62802897/187018570-ab55b981-b54c-4bc6-9ae0-e7794e83b99d.png)

**Comment by xw901103** [comment]
put the line under row(height) for loop `auto t = (j + random_double()) / (image_height-1);` inside antialiasing sampling for loop. your code should looks like following.

for (int j = 0; j < image_height; ++j) {
        std::clog << "\rScanlines remaining: " << (image_height - j) << ' ' << std::flush;

        for (int i = 0; i < image_width; ++i) {
            color pixel_color(0, 0, 0);
            for (int sample = 0; sample < samples_per_pixel; ++sample) {
                auto t = (j + random_double()) / (image_height-1);
                auto s = (i + random_double()) / (image_width-1);
                std::clog << t << std::endl;
                ray r = cam.get_ray(s, t);
                pixel_color += ray_color(r, world, max_depth);
            }
            write_color(std::cout, pixel_color, samples_per_pixel);
        }
    }

if you leave that t value only changes every time you go to next scanline, you will have horizontal sampling insufficient which looks like the results you posted above.

**Comment by LollipopFt** [comment]
@xw901103 that's my point, the code that they gave in `dev_major` is wrong.

**Comment by hollasch** [comment]
Sorry for the delay. Yes, this is a definite bug I introduced. Thank you for catching it.

**Comment by hollasch** [comment]
Fixed in PR #1097.
