### ISSUE TITLE
Book 1: Camera terms used without being introduced

### ISSUE THREAD

**Issue by kristopolous** [RayTracing/raytracing.github.io#1071]
There's a number of things that for me, need to be cleared up:

> ...For now we'll use a 16:9 aspect ratio, since that's so common.

> In addition to setting up the pixel dimensions for the rendered image, we also need to set up a virtual viewport through which to pass our scene rays. For the standard square pixel spacing, the viewport's aspect ratio should be the same as our rendered image. We'll just pick a viewport two units in height. 

This suggests a width of 16/9 * 2 units, right?

> We'll also set the distance between the projection plane and the projection point to be one unit. 

"Projection plane" and "projection point" aren't defined here. They are technical terms with functional meanings. This is the first time they are introduced.

> This is referred to as the “focal length”, not to be confused with “focus distance”, which we'll present later.

Without a meaningful functional definition of "projection plane" and "projection point", the term "focal length" and what "distance" means in this context is unknown and opaque. It is effectively the same as this:

> We'll also set the ████ between the ████ and the ████ to be one unit. This is referred to as the “focal length”, not to be confused with “focus distance”, which we'll present later.

**Comment by ShijianXu** [comment]
I agree. I took a lot of time to figure out what the `viewport` mean. I think some terms should be explained in more details. Like why we set the viewport size to be `2x3.5555` or actually any size that keeps the ratio `9:16` makes sense.

**Comment by hollasch** [comment]
We'll roll this into the new camera updates.
