### ISSUE TITLE
5.1 Ray Sphere Intersection rationality

### ISSUE THREAD

**Issue by kristopolous** [RayTracing/raytracing.github.io#1074]
The statement "Recall that the equation for a sphere centered at the origin of radius R is x2+y2+z2=R2." is fairly lacking because "why squared" is never answered (nor for that matter what squaring a number is in this context but we can skip that).

It took me a few seconds to realize this is Pythogorean. A helpful math link such as to here http://mathcentral.uregina.ca/qq/database/qq.09.03/jaidev1.html or something equally brief would be of great assistance to people like me who are a bit impertinent that things get demonstrated

**Comment by trevordblack** [comment]
I might extend from the equation of a 2 dimensional circle to that of a 3 dimensional sphere.
But this falls well on the side of things that we need to expect the user to understand.

We can't stop and explain everything to everyone, we completely gloss over all vector math in chapter 3 for this reason.

For those readers that aren't familiar with how to solve for the equation of the sphere, we mention that it exists, so the motivated reader should go off and fill that gap in their knowledge.
