### ISSUE TITLE
Book 3 Section 12.1 Listing 37: Code and screenshot 9 do not match

### ISSUE THREAD

**Issue by StrangeVoyager** [RayTracing/raytracing.github.io#1085]
Listing 37 lists a dielectric sphere in place of the shorter box, but the screenshot still shows the box.

Listing 37 also does not compile because we pass in a hittable_list of lights to ray_color, but have not yet implemented (for hittable_list) the pdf_value or random methods at this point in the code that are needed bit the hittable_pdf light_ptr.

**Comment by StrangeVoyager** [comment]
Closed. I'm not sure where I was looking, but there is no screenshot.

**Comment by KnockerPulsar** [comment]
The first part is already covered in the dev-major branch. I opened issue #1084 and found out that the image / code were fixed on the branch.

**Comment by hollasch** [comment]
Looks like this was fixed.
