### ISSUE TITLE
Book2 Listing 17 Bounding volume hierarchy node

### ISSUE THREAD

**Issue by DrMofu** [RayTracing/raytracing.github.io#1090]
In Book 2, Listing 17,
We should change
```
bvh_node::bvh_node(
    std::vector<shared_ptr<hittable>>& src_objects,
    size_t start, size_t end, double time0, double time1
)
```
to 
```
bvh_node::bvh_node(
    const std::vector<shared_ptr<hittable>>& src_objects,
    size_t start, size_t end, double time0, double time1
)
```
(add a "const" term)
since we declare 
```
bvh_node(
            const std::vector<shared_ptr<hittable>>& src_objects,
            size_t start, size_t end, double time0, double time1);
```
in listing 15.

The code in the GitHub repo is fine, but the code in the book2 is missing this "const" term.
My compiler will fail if I don't add this "const" term.

**Comment by hollasch** [comment]
Let me know if you wanted to make this change (in branch `dev-major`), otherwise I'll tackle it.

**Comment by hollasch** [comment]
This has already been fixed in `dev-major`.
