### ISSUE TITLE
Render ray construction is inconsistent

### ISSUE THREAD

**Issue by jvaque** [RayTracing/raytracing.github.io#1094]
The code in listing 24 in the book is as follows.

```
ray r(origin, lower_left_corner + u*horizontal + v*vertical);
```

But from the previous ray generation implementation (Listing 9) it should still subtract the origin coordinates, even if at this stage the origin is still (0, 0, 0).

```
ray r(origin, lower_left_corner + u*horizontal + v*vertical - origin);
```

The book goes back to subtracting the origin (Listing 27) when implementing the camera class in order to get the accurate ray if the camera is to move.

**Comment by hollasch** [comment]
This code is under development on the current (`dev-major`) branch. Our camera code is getting a sizeable rewrite.
