### ISSUE TITLE
Need solution to highlighted code lines

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#11]
One solution would be to enable line numbers in code blocks, and then have the text reference the appropriate lines.

Another solution would be to introduce some form of CSS/HTML markup to denote highlighted regions. The downside of this is that you couldn't just import code blocks into the book in the future (which I think I'd like to do for other reasons). Probably better to just leave the code pure.

For example, see the last code block in Ray Tracing: The Next Week, chapter 4 (this used code comments). See the first code block in Ray Tracing: The Rest of Your Life, chapter 7 (new chapter 8). This one uses background highlighting.

----

After discussion, we'll just use code comments to call out changes. We need to make these changes for all three books.

**Comment by hollasch** [comment]
Another option is to point out the delta explicitly in code, using comments or whatever other language features support highlighting the new changes.

**Comment by trevordblack** [comment]
Commenting out deltas in the code gets my vote

**Comment by hollasch** [comment]
Sounds good — let's go with code commentary. I've updated the story description.

**Comment by hollasch** [comment]
Cool! Check this out: https://casual-effects.com/markdeep/features.md.html#basicformatting/fencedcodeblocks/multi-codeblocksandcustomcss

**Comment by trevordblack** [comment]
Yep. Shoulda just dug through the documentation as a first thing.
Looks good. Gets my vote.

It had also just occurred to me that we could use a beige background in code to match Peter's original color.

**Comment by hollasch** [comment]
I asked Pete about the existing code styling, and he just grabbed screenshots off his IDE. He explicitly said he didn't care about the code style being replicated in the new version. The new style is still open to discussion, though, on its own merits.
