### ISSUE TITLE
Book 2: Listing 17 BVH bounding box data member naming inconsistency (bbox vs box).

### ISSUE THREAD

**Issue by KnockerPulsar** [RayTracing/raytracing.github.io#1104]
Hello, found a minor nitpick while going through the latest version of The Next Week on `dev-major`.

![image](https://user-images.githubusercontent.com/12754772/230684117-56bcc108-c9f8-4cae-9442-f250e34dd452.png)

Apologies if it's a duplicate, I checked and haven't found similar issues.

**Comment by hollasch** [comment]
Thank you!
PR #1108

**Comment by trevordblack** [comment]
@hollasch Can this get closed out?
