### ISSUE TITLE
Book2: Listing 33 function noise parameters error

### ISSUE THREAD

**Issue by HaiBooLang** [RayTracing/raytracing.github.io#1109]
Hi, found a minor nitpick while going through the latest version of The Next Week on `master`.

The code in Listing 33 in line 4 in the book is as follows.

`double noise(point3 vec3& p) const {`

I guess it should be；

`double noise(const vec3& p) const {`

**Comment by hollasch** [comment]
Thank you! PR for `dev-major` pending (#1110).
