### ISSUE TITLE
Book 1 Section 7.2 misspelled terminology

### ISSUE THREAD

**Issue by zentros** [RayTracing/raytracing.github.io#1113]
### Book 1 Section 7.2 misspelled terminology :

_"Now's a good time to create a camera class to manage our virtual camera and the related tasks of scene **scampling**. The following class implements a simple camera using the axis-aligned camera from before:"_

The word "sampling" is misspelled as "scampling".

**Comment by hollasch** [comment]
Duplicate of #921.

**Comment by hollasch** [comment]
This is fixed in `dev-major`.
