### ISSUE TITLE
Revisit asynchronous code reviews as desired

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#1129]
This is a meta issue to after-the-fact review PRs that have been merged without a complete review yet. I'll be updating the list of pending reviews here for proper tracking.

- [x] #1120 
- [x] #1126 
- [x] #1135
- [x] #1136 
- [x] #1137
- [x] #1170 
- [x] #1171
- [x] #1172
- [x] #1177
- [x] #1180
- [x] #1181
- [x] #1184 
- [x] #1185

**Comment by hollasch** [comment]
- [ ] #1135 
- [ ] #1136 
- [ ] #1137

**Comment by trevordblack** [comment]
Going through the book, the code  syntax highlighting style is quite poor

**Comment by hollasch** [comment]
Yeah. My preferred style is one color for comments, and a second color for code. Everything else is just shades of clown car to me.

**Comment by trevordblack** [comment]
Oh interesting, I disagree.

I find determining which things are type names versus type symbols, operators, etc. Much more immediately legible

Whether or not the color choice is pretty is not really a concern for me

What matters to me on this context is legibility by the reader

**Comment by hollasch** [comment]
One large issue is that this is just JavaScript-powered code styling, and there are many quirks. I'd say grab the book.css and play with things if you'd like. Swap in the `book-highlight-test.css` to see the highlighting available.

**Comment by hollasch** [comment]
I've gone through each of the remaining open reviews and tagged them with the "Review" tag.

Use the query https://github.com/RayTracing/raytracing.github.io/pulls?q=is%3Apr+is%3Aclosed+label%3AReview to display all items with an open deferred review.
