### ISSUE TITLE
Change signature from `int main()` to `void main()`

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#1145]
Less confusing for people unfamiliar with arcane details of C/C++ (the fact that `main` is special in that it doesn't require you to actually return a value, contrary to its declared signature). All modern compilers should support `void main()`.

**Comment by trevordblack** [comment]
I'm of the opinion that we leave it as is.

Which is to say `int main()` that doesn't explicitly call `return 0;`.

https://stackoverflow.com/questions/204476/what-should-main-return-in-c-and-c

**Comment by hollasch** [comment]
Any particular reason? It's a five-minute change.

**Comment by hollasch** [comment]
Oh, didn't see your link. Reading...

**Comment by trevordblack** [comment]
https://www.stroustrup.com/bs_faq2.html#void-main

From what I'm reading, `void main()` sounds like an emergent thing, and was explicitly not desired

**Comment by hollasch** [comment]
Yeah, I'd vote to keep it `int main()` for C/C++ programmers, but I'm thinking about keeping the code accessible for non-C programmers. Still, we've had no complaints for readers, so let's drop it for now.
