### ISSUE TITLE
[book 3][ch 6.1] Image doesn't match the settings

### ISSUE THREAD

**Issue by genmeblog** [RayTracing/raytracing.github.io#1197]
When I change samples per pixel from 64 to 100 (as it is in listing 17) my image is still much noisier than Image 3. In my reimplementation `1000` gives the matching result.

**Comment by genmeblog** [comment]
Rendered examples on my side (possibly buggy):

Image 2 is almost the same as in the book:

![ch02b](https://github.com/RayTracing/raytracing.github.io/assets/38646601/2a2e9bfa-f350-40e7-9cce-38b9883ecc72)

Image 3, after changing samples per pixels to 100:

![ch06a](https://github.com/RayTracing/raytracing.github.io/assets/38646601/ccf12990-316c-4e42-9b0b-13d9be3c2819)

Image 4, imperfect PDF

![ch06c](https://github.com/RayTracing/raytracing.github.io/assets/38646601/a7360a6c-6f08-4982-ab80-5daf0a5d79b1)

Image 5, `random_in_hemisphere`, this is undefined in the book, btw. Anyway the result is strange...

![ch06d](https://github.com/RayTracing/raytracing.github.io/assets/38646601/9d217877-c0d3-4772-a9e6-f8e99718fc91)

**Comment by hollasch** [comment]
This work should be accomplished as a result of #863.

**Comment by dimitry-ishenko** [comment]
> When I change samples per pixel from 64 to 100 (as it is in listing 17) my image is still much noisier than Image 3. In my reimplementation `1000` gives the matching result.

Maybe this is an old issue, but Chapter 6.1 now says to increase number of samples per pixel to 1000:

> Let’s adjust some parameters for the Cornell box:
> ```diff
>  int main() {
>      ...
> +    cam.samples_per_pixel = 1000;
>      ...
>  }
> ```

**Comment by dimitry-ishenko** [comment]
The brighter image part is a dup of #1321. @hollasch this issue can technically be closed.
