### ISSUE TITLE
Port Pete's in1weekend.blogspot.com articles to the raytracing wiki

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#1217]
Peter originally created https://in1weekend.blogspot.com/ to serve as updates and further information for the _Ray Tracing in One Weekend_ series. Though it's a bit out of date, the articles contain useful information. (And sadly, the comments have been filled with spam.)

We'd like to port this content over to [the wiki](https://github.com/RayTracing/raytracing.github.io/wiki) to keep it close to the project and open for further updates.

**Comment by hollasch** [comment]
See also #676

**Comment by hollasch** [comment]
See also #407

**Comment by rupsis** [comment]
Addressed in #1378
