### ISSUE TITLE
There isn't a GitHub Pages site here.

### ISSUE THREAD

**Issue by jukrb0x** [RayTracing/raytracing.github.io#1221]
Hi, I just found https://raytracing.github.io/ is not accessible for the moment, is there anything wrong with the repository configuration?

<img width="813" alt="image" src="https://github.com/RayTracing/raytracing.github.io/assets/15688641/aef4b4c4-56eb-4eb8-8ba7-762d6d76e30b">

**Comment by aliasgar55** [comment]
Untill the issue is fixed you can visit [here](https://aliasgar55.github.io/raytracing.github.io/)

**Comment by disini** [comment]
same problem here.

> Hi, I just found https://raytracing.github.io/ is not accessible for the moment, is there anything wrong with the repository configuration?
> 
> <img alt="image" width="813" src="https://user-images.githubusercontent.com/15688641/261200266-aef4b4c4-56eb-4eb8-8ba7-762d6d76e30b.png">

**Comment by disini** [comment]
> Untill the issue is fixed you can visit [here](https://aliasgar55.github.io/raytracing.github.io/)

nice! much appreciated! @aliasgar55

**Comment by dimitry-ishenko** [comment]
Just clone the repo on your computer and open `raytracing.github.io/books/RayTracingInOneWeekend.html` in the browser.

**Comment by hollasch** [comment]
Fixed! And wow, thanks everyone for the quick workaround advice in the meantime!
