### ISSUE TITLE
[Book1] Wording error in subsection 4.2 - Sending Rays Into the Scene

### ISSUE THREAD

**Issue by carvalhais** [RayTracing/raytracing.github.io#1246]
The last two sentences in the first paragraph after listing 8 reads as:
> First, `integer_height `is rounded down to the nearest integer, which can increase the ratio. Second, we don't allow `integer_height `to be less than one, which can also change the actual aspect ratio.

I believe they should read as:
> First, **`image_height`** is rounded down to the nearest integer, which can increase the ratio. Second, we don't allow **`image_height`** to be less than one, which can also change the actual aspect ratio.

I'm willing to make the fix myself, waiting for the correct development branch assignment.

**Comment by carvalhais** [comment]
TBH really did a review of the open issues, but was concerned about the titles. However today, browsing through the open issues, I came across the following comment on another issue: https://github.com/RayTracing/raytracing.github.io/issues/1222#issuecomment-1682540391.

About the wording error I mentioned, I read that yesterday night on the book on the website version. If it is still not merged, I'm available to fix it.

**Comment by hollasch** [comment]
Already fixed in `dev`, 2ee8f9a6
