### ISSUE TITLE
There is also a missing word just below **Listing 8**:

### ISSUE THREAD

**Issue by carvalhais** [RayTracing/raytracing.github.io#1247]
There is also a missing word just below **Listing 8**:

"If you're wondering why we don't just use `aspect_ratio` when computing `viewport_width`, it's because the value set to `aspect_ratio` is the ideal ratio, it may not be the actual ratio between `image_width` and `image_height`. If `image_height` was allowed to be real valued—rather than just an integer—then it would **be** fine to use `aspect_ratio`. ..."

And in the same paragraph `image_height` is called `integer_height` twice:

"... But the actual ratio between `image_width` and `image_height` can vary based on two parts of the code. First, **`integer_height`** is rounded down to the nearest integer, which can increase the ratio. Second, we don't allow **`integer_height`** to be less than one, which can also change the actual aspect ratio."

_Originally posted by @dimitry-ishenko in https://github.com/RayTracing/raytracing.github.io/issues/1222#issuecomment-1682540391_

**Comment by carvalhais** [comment]
Sorry, was trying to reference the original issue and inadvertently created this one.

**Comment by dimitry-ishenko** [comment]
I think my comment got lost in between the other discussion. Feel free to create a new issue for that, unless there is one already. This way we can also close my issue.

**Comment by carvalhais** [comment]
Thanks for the input, I had already created issue #1246, and was trying to reference your comment on that issue.
