### ISSUE TITLE
[Book 1] Minor improvement in Listing 1

### ISSUE THREAD

**Issue by carvalhais** [RayTracing/raytracing.github.io#1249]
Reproducing listing 1:
```c++
#include <iostream>

int main() {

    // Image

    int image_width = 256;
    int image_height = 256;

    // Render

    std::cout << "P3\n" << image_width << ' ' << image_height << "\n255\n";

    for (int j = 0; j < image_height; ++j) {
        for (int i = 0; i < image_width; ++i) {
            auto r = double(i) / (image_width-1);
            auto g = double(j) / (image_height-1);
            auto b = 0;                                // <--- here b is of type int

            int ir = static_cast<int>(255.999 * r);
            int ig = static_cast<int>(255.999 * g);
            int ib = static_cast<int>(255.999 * b);    // <--- here there are two casts at play,
                                                       // to double, than back to int

            std::cout << ir << ' ' << ig << ' ' << ib << '\n';
        }
    }
}
```

In Listing 1, both `r` and `g` are of type double because of the cast in the variable definition, but `b` is of type int, because it is initialized to `0` and not `0.0`. This make no difference in the functionality of the code, because all of these three variables will be used in expressions that themselves evaluates to an `int` when they are referred to in the initialization of the `int` type variables.

But there are two type conversions that happen when `b` is used in such expression, first it is promoted to a `double`, because it is multiplied by `255.999`, and then back to an `int` in the `static_cast`. I'm not sure this was on purpose, but this hides a C/C++ specific behaviour (that other languages might mimic).

I believe that just giving `b` an initial value of `0.0` instead of just `0`, would make things clearer from people with no C/C++ background, as in those the `int` to `double` promotion might not be implicit, and it makes the programmer intention more clear.

**Comment by carvalhais** [comment]
@hollasch I'm slowing typing all the code in the book, as suggest, and I'm starting to come up with a lot of issues that could be considered. I'm a bit afraid of opening too many issues, because some of them might be a little pedantic. What do you suggest I should do?

**Comment by hollasch** [comment]
An issue with a ton of different aspects will never be closed or addressed, as there's no proper way to tell when more items will be added in the future or when it should be considered "done". Please create one GitHub issue per issue.
