### ISSUE TITLE
[Book 1] Listing 6: use double type literal 0.0 for consistency

### ISSUE THREAD

**Issue by carvalhais** [RayTracing/raytracing.github.io#1251]
Listing 6 snippet:
```cpp
auto pixel_color = color(double(i)/(image_width-1), double(j)/(image_height-1), 0);
```
Just to keep consistent with other parts of the code, and possible to avoid hidden C/C++ specific behaviours, I would suggest changing the last parameter of that function call to a `double` literal (`0.0`) instead of an `int` literal (`0`), as in:
```cpp
auto pixel_color = color(double(i)/(image_width-1), double(j)/(image_height-1), 0.0);
```

**Comment by hollasch** [comment]
In C/C++, "0" means many things, not just `int` value `0`. For example, `0` means null pointer when assigned to pointer types. It means `0.0` when assigned to float types. In fact, if you use the literal `0.0`, you'll often get a warning if you assign it to a single-precision float. Generally throughout our codebase, we prefer integer values when the values are integral, even when assigning to floating-point types. There are many examples of this throughout our code, but `camera.h` is a fine one to start with.
