### ISSUE TITLE
[Book 1] Clarify explanation in section 5.1 - Ray-Sphere Intersection

### ISSUE THREAD

**Issue by carvalhais** [RayTracing/raytracing.github.io#1252]
Snippet from section 5.1 - Ray-Sphere Intersection:
> You can also think of this as saying that if a given point _(x,y,z)_ is on the sphere, then _x²+y²+z²=r²_. If a given point _(x,y,z)_ is inside the sphere, then _x²+y²+z²<r²_, and if a given point _(x,y,z)_ is outside the sphere, then _x²+y²+z²>r²_.

Maybe this suggestion makes sense to me because I'm a foreigner and sometimes have a little trouble with English prepositions, but it took me a little to while to ponder about that sentence, and understand that the first case specifically talks about when the point is on the surface of the sphere. Maybe this could be made explicit as in:
> You can also think of this as saying that if a given point _(x,y,z)_ is on the **surface of the** sphere, then _x²+y²+z²=r²_. If a given point _(x,y,z)_ is inside the sphere, then _x²+y²+z²<r²_, and if a given point _(x,y,z)_ is outside the sphere, then _x²+y²+z²>r²_.

**Comment by hollasch** [comment]
_Technically_, a sphere is the set of all points at a specific distance from some (center) point, and any point closer is not really "in" the sphere. My master's thesis was on rendering four-dimensional geometry, so fussy details like that were actually quite important.

Still, I can see now how that might be confusing. Thanks for the suggestion; will fix.

**Comment by hollasch** [comment]
Done.
