### ISSUE TITLE
typo at section 2.4 of raytracing the next week

### ISSUE THREAD

**Issue by hanseuljun** [RayTracing/raytracing.github.io#1253]
In sphere::center of sphere.h shown in Listing 3,

return center0 + time*center_vec;

should be

return center1 + time*center_vec;

**Comment by hollasch** [comment]
We recommend moving to v4.0.0-alpha.1 at this point. Though books 2 and 3 are still under development, their current state is already a large improvement from the older v3.2.3 version. We will not be doing further fixes on the v3 versions.

This issue has been fixed in v4.0.0-alpha.1.
