### ISSUE TITLE
typo at section 2.4 listing 4

### ISSUE THREAD

**Issue by hanseuljun** [RayTracing/raytracing.github.io#1254]
I believe

point3 center = is_moving ? sphere_center(r.time()) : center1;

should be

point3 center = is_moving ? sphere::center(r.time()) : center1;

**Comment by armansito** [comment]
You are right about the discrepancy and thank you for pointing it out. I believe the book listing was fixed on the `dev` branch in #1232 and it looks like the source code was updated too.
