### ISSUE TITLE
missing material.h update in Section 4

### ISSUE THREAD

**Issue by hanseuljun** [RayTracing/raytracing.github.io#1258]
At the end of Section 4.2, it is assumed class lambertian has a constructor accepting a texture. But up to this point, such constructor is not introduced to lambertian.

Line 36, 37, 48, 52, 53 should be updated to that of material.h at the below link. This update converted albedo from a instance of color to texture. 

https://github.com/RayTracing/raytracing.github.io/blob/95975fe79a13f95d078c82dbee1bf38b7177589e/src/TheNextWeek/material.h#L34C10-L34C10

**Comment by hanseuljun** [comment]
Found that this update of material.h appears at Listing 30 of Section 4.4.

**Comment by hollasch** [comment]
Thank you for doing the extra work to locate the changes! This was fumbled during the large texture chapter reorganization.

**Comment by hollasch** [comment]
Done.
