### ISSUE TITLE
[Book 1] Missing function qualifier in Listing 59

### ISSUE THREAD

**Issue by carvalhais** [RayTracing/raytracing.github.io#1259]
Listing 59 doesn't have the `inline` function qualifier in the `reflect()` function, even though all utility functions in the header file have them:
```c++
vec3 reflect(const vec3& v, const vec3& n) {
    return v - 2*dot(v,n)*n;
}
```
The `reflect()` function ins again listed in Listing 65, but now with the `inline` qualifier:
```c++
inline vec3 reflect(const vec3& v, const vec3& n) {
    return v - 2*dot(v,n)*n;
}
```

**Comment by hollasch** [comment]
Done.
