### ISSUE TITLE
[Book3] Only change the denominator PDF value can also converge to the correct answer?

### ISSUE THREAD

**Issue by LiuZengqiang** [RayTracing/raytracing.github.io#1272]
In ``6.2 Using a Uniform PDF Instead of a Perfect Match``,  the scatter ray is sampled in Lambert Distribution in ``rec.mat->scatter()``, but the pdf value is set to ``1/(2*pi)``. I think it is against the Monte Carlo Theory. Can It still converge to the correct answer?  As the book said `` This will still converge on the correct answer``. I'm confused about this.

**Comment by hollasch** [comment]
Ref #1302

**Comment by hollasch** [comment]
Merging into #1302.
