### ISSUE TITLE
[Book1] A hollow glass sphere

### ISSUE THREAD

**Issue by irevoire** [RayTracing/raytracing.github.io#1278]
Hey, huge noob here.

I’m following the first book in rust; once I reached the chapter: « Modeling a Hollow Glass Sphere » I started to have different results than the one you show in the book:
![image](https://github.com/RayTracing/raytracing.github.io/assets/7032172/a79afdf8-91c9-4900-8195-3e1ed25c2599)

The thing is, after I spent a few hours trying to find a difference between my code and yours, I decided to run your code directly and found a different result than the one in the book (and different than mine as well 😓).

![image](https://github.com/RayTracing/raytracing.github.io/assets/7032172/c0af9d86-363e-43c3-aa27-219aa5a4b71b)

On top is my code, and on the bottom is yours.

I don’t know where the issue is located and am a bit lost, but I’m pretty sure that my code does the same thing as the c++ version, except the two final chapters are not implemented. (and that may explain the slight difference between the two renders I made?) 

I pushed my code here if you want to check it out: https://github.com/irevoire/raytracing2. You can run it with `cargo run --release` after installing rust.

**Comment by LiuZengqiang** [comment]
This result is related to the factor ``_etai_over_etat``.
The target rendering result can be obtained by changing the value of ``_etai_over_etat``.

**Comment by zyx-db** [comment]
Hi, I am running into the same issue, and am wondering if you have figured it out.
@LiuZengqiang can you please expand on what to change about '_etai_over_etat'?

**Comment by LiuZengqiang** [comment]
When set ``_etai_over_etat = 1.02``, I got a result similar to the image on Book 1, as follow:
My code when ``_etai_over_etat = 1.02``.
![_etai_over_etat=1.02](https://github.com/RayTracing/raytracing.github.io/assets/74355935/49cc7f08-6fc4-4d98-bdfa-ac0b0f85f9cb)
My code is shown bellow:
```cpp
// main.cpp
...
  auto material_ground = make_shared<lambertian>(color(0.8, 0.8, 0.0));
  auto material_center = make_shared<lambertian>(color(0.1, 0.2, 0.5));
  auto material_left = make_shared<dielectric>(1.02);
  auto material_right = make_shared<metal>(color(0.8, 0.6, 0.2), 0.0);
...
  cam.aspect_ratio = 16.0 / 9.0;  // 图像的长宽比
  cam.image_width = 400;          // 图像的宽(像素数)
  cam.samples_per_pixel = 50;      // 每个像素的采样光线数
  cam.max_depth = 10;             // 光线的最大深度

  cam.vfov = 90;                    // 视场角
  cam.lookfrom = point3(0, 0, 0);  // 相机位置
  cam.lookat = point3(0, 0, -1);     // 相机观察的点
  cam.vup = vec3(0, 1, 0);          // 相机上方向向量

  cam.defocus_angle = 0.6;  // 模拟实际相机的散射角度(以实现景深效果)
  cam.focus_dist = 1.0;  // 模拟实际相机的理想焦距(以实现景深效果)
...
```
```cpp
// material.h
...
class dielectric : public material {
 public:
  dielectric(double _etai_over_etat) : etai_over_etat(_etai_over_etat) {}

  bool scatter(const ray& r_in, const hit_record& rec, color& attenuation,
               ray& scattered) const override {
    attenuation = color(1.0, 1.0, 1.0);
    // 根据入射光的方向进行判断 eta/eta' 的值
    double refraction_ratio =
        rec.front_face ? (1.0 / etai_over_etat) : (etai_over_etat);
    vec3 unit_direction = unit_vector(r_in.direction());

    // 入射角若很大则只发生反射, 没有折射
    double cos_theta = fmin(dot(rec.normal, -unit_direction), 1.0);

    double sin_theta = sqrt(1.0 - cos_theta * cos_theta);
    bool cannot_refraction = refraction_ratio * sin_theta > 1.0;
    vec3 direction;
    if (cannot_refraction ||
        reflectance(cos_theta, refraction_ratio) > random_double()) {
      // 若为反射
      direction = reflect(unit_direction, rec.normal);
    } else {
      // 若为折射
      direction = refract(unit_direction, rec.normal, refraction_ratio);
    }
    scattered = ray(rec.p, direction);
    return true;
  }

 private:
  double etai_over_etat;  // 入射介质折射率/出射介质折射率

  // 计算 反射折射比率
  static double reflectance(double cosine, double ref_idx) {
    // 使用 Schlick's 逼近公式计算
    auto r0 = (1 - ref_idx) / (1 + ref_idx);
    r0 = r0 * r0;
    return r0 + (1 - r0) * pow((1 - cosine), 5);
  }
};
...

**Comment by TheThief** [comment]
I think the call to `reflectance()` is also wrong - it's called using refraction_ratio, but the formula expects the ir, not the ratio. This is resulting it using the wrong value when going outside to inside

**Comment by meemsbror** [comment]
Had the same issue, but managed to figure it out.

In Listing 73 you aren't supposed to change the current glass sphere, but rather add a 2nd one.

```
world.add(make_shared<sphere>(point3(-1.0,    0.0, -1.0),   0.5, material_left));
world.add(make_shared<sphere>(point3(-1.0,    0.0, -1.0),  -0.4, material_left));
```

Together both spheres make a hollow sphere. I accidentally did not include this one, and only had one with the negative radius, and I got the same results as you.

**Comment by hollasch** [comment]
I'll see if I can make this change more clear.

**Comment by LiuZengqiang** [comment]
I will check it, maybe my code is wrong.

**Comment by TheThief** [comment]
> I think the call to `reflectance()` is also wrong - it's called using refraction_ratio, but the formula expects the ir, not the ratio. This is resulting it using the wrong value when going outside to inside

@hollasch you seem to have missed this comment of mine also. Do you want me to put in a separate issue/pull request?

**Comment by irevoire** [comment]
> Together both spheres make a hollow sphere. I accidentally did not include this one, and only had one with the negative radius, and I got the same results as you.

It still doesn't work on my side, but I can definitely make it work with the original cpp code from the book, so I guess that was the only issue in play here:
<img width="809" alt="image" src="https://github.com/RayTracing/raytracing.github.io/assets/7032172/54ca5148-005e-4bf6-aafd-8546b8e37eff">

> you seem to have missed this comment of mine also. Do you want me to put in a separate issue/pull request?

Yeah, I think it would be better to open a new issue since your comment seems unrelated to my issue.

Closing, thanks for the solution and the PR on the book!
