### ISSUE TITLE
[Book1] About ch6.8 An Interval Class

### ISSUE THREAD

**Issue by Penguin-SAMA** [RayTracing/raytracing.github.io#1281]
How to solve infinity undefined problem
<img width="1262" alt="image" src="https://github.com/RayTracing/raytracing.github.io/assets/50973632/00143ddc-a47e-4ff5-a60f-d1bc09889590">

**Comment by hollasch** [comment]
You need to include rtweekend.h as the first file in your main program. This file contains the definition of the constant `infinity`.

**Comment by Penguin-SAMA** [comment]
thanks
