### ISSUE TITLE
[Book2] Incorrect marble pattern at the final Perlin noise section

### ISSUE THREAD

**Issue by MaximusPrimeForever** [RayTracing/raytracing.github.io#1286]
Hi, I'm implementing this code in Rust instead of CPP so I very much hope that this isn't due to language differences.

## The issue
Anyways, in the Perlin Noise chapter at the marble pattern section the book proposes this modification to get the marble texture:
```c++
color value(double u, double v, const point3& p) const override {
    auto s = scale * p;
    return color(1,1,1) * 0.5 * (1 + sin(s.z() + 10*noise.turb(s)));  // << this line
}
```
Here is my equivalent Rust code:
```rust
fn value(&self, _: f64, _: f64, point: &Point3) -> Color {
    let scaled_point = self.scale * (*point);
    Color::new(1.0, 1.0, 1.0) * 0.5 * (1.0 + (scaled_point.z() + 10.0 * self.noise.turbulence(scaled_point, 7)).sin())
}
```
And this is the image produced:
![marble_sphere_bugged](https://github.com/RayTracing/raytracing.github.io/assets/12038387/cf5d4cb3-a006-4505-8468-3b1277c087b6)

This is doesn't really look like marble, and does not resemble the following example from the book:
![from-the-book](https://raytracing.github.io/images/img-2.15-perlin-marble.png)

## Potential solution
I've played around with the code, and noticed that if I pass the raw point (unscaled) to the turbulence function like so:
```rust
fn value(&self, _: f64, _: f64, point: &Point3) -> Color {
    let scaled_point = self.scale * (*point);
    Color::new(1.0, 1.0, 1.0) * 0.5 * (1.0 + (scaled_point.z() + 10.0 * self.noise.turbulence(*point, 7)).sin()) // << *point instead of scaled_point
}
```
I get the following image:
![marble_sphere_correct](https://github.com/RayTracing/raytracing.github.io/assets/12038387/37e276c1-b0a9-4759-9006-fdbcc9bc9f59)

Which appears much closer to the intended result.  
I cannot say I understand the math behind this chapter very well, so I don't know if this is the correct solution, but wanted to share anyway.

Hope this is helpful!

**Comment by gau-nernst** [comment]
It seems like your solution matches the code in v3: https://raytracing.github.io/v3/books/RayTracingTheNextWeek.html#perlinnoise/adjustingthephase

Scaling is only applied to the phase `p.z()`

**Comment by MaximusPrimeForever** [comment]
> It seems like your solution matches the code in v3: https://raytracing.github.io/v3/books/RayTracingTheNextWeek.html#perlinnoise/adjustingthephase
> 
> Scaling is only applied to the phase `p.z()`

Looks like it's fixed for future releases then :)

**Comment by hollasch** [comment]
No, @gau-nernst is saying that the _old_ version matches your solution, and the _new_ version in development has the defect you point out.

At this point, your comment and solution look correct to me.

In order to properly test this, I'll need to be in the middle of the book 2 progression work that we have scheduled when the book 2 alpha is getting ready for release. I'll revisit then and likely apply your fix.

**Comment by hollasch** [comment]
Wait, no — I was looking at `perlin.h` when I should have been looking at `texture.h`. Testing now.

**Comment by hollasch** [comment]
Yup, looks good. Nice catch; thank you!

**Comment by hollasch** [comment]
Fixed.
