### ISSUE TITLE
Book 1 Section 6.2 Simplifying the Ray-Sphere Intersection Code

### ISSUE THREAD

**Issue by AlecHang** [RayTracing/raytracing.github.io#1292]
In https://github.com/RayTracing/raytracing.github.io/blob/1134eb3800838892738d328576b179d41780f355/books/RayTracingInOneWeekend.html#L845C9-L845C46
with sentence "auto half_b = dot(oc, r.direction());"
I guess a negative sign "-" is missing infront of "dot(oc, r.direction())".

**Comment by TheRealFirst** [comment]
The simplified code in listening 14 of book 1 sadly doesnt work for me, it just doesnt show me a sphere then, it only works with the first code and also the colors are wrong somehow (with the first solution). Could anyone pls try to help me? Maybe someone who had the same problem or saw it before. I would be very thankful.

**Comment by krmckone** [comment]
I'm running into this as well. I can get the red sphere but after that I struggle to get the right image with the simplified sphere intersection code.

**Comment by hollasch** [comment]
At this point, particularly for book 1, I would recommend using the latest version, v4.0.0-alpha.1, which has many many fixes: https://raytracing.github.io/books/RayTracingInOneWeekend.html. This bug is with v3.2.3, so we won't be back-porting fixes to that version.

**Comment by krmckone** [comment]
Thank you yeah I went back and checked all of my code and I had a typo in my dot product function I swapped a `v` for a `u`, working as expected now
