### ISSUE TITLE
[Book 2] Section 4.3: Validate checkered sphere image

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#1307]
Benny Tsang writes:
> (Book 2) Section 4.3, the size of the checker boxes in "Image 3: Checkered Spheres" looks rather different from my output following the code in Listing 27. I believe it is due to a different implementation of checker_texture's value() function compared to an old version (perhaps it has a different default `scale`?).

**Comment by gau-nernst** [comment]
The old version uses sine functions to generate alternating pattern. It is equivalent to setting scale = 1 / PI, since the sine function has a period of 2 PI.

**Comment by rupsis** [comment]
@gau-nernst is correct that the alternating pattern in V4  uses a different method. 
Fixed in https://github.com/RayTracing/raytracing.github.io/pull/1376. An updated scale is used to produce an image _very_ close to V3.
