### ISSUE TITLE
Listing 3.6 / Camera listing error

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#1309]
Benny Tsang writes:
> - (Book 3) Section 2.3, Listing 6, in camera::render, the number of subgrids in a pixel `sqrt_spp` is not undefined (it shows up much later in Listing 40). Similarly, its reciprocal value `reciprocal_sqrt_spp` is not defined in the `pixel_sample_square` function.

**Comment by armansito** [comment]
This is now fixed on the `dev` branch.
