### ISSUE TITLE
Listing 3.29 lacks proper change highlighting

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#1312]
Benny Tsang writes:
> (Book 3) Section 8.3, the addition of the argument `double& pdf` in scatter() is not highlighted in Listing 29. Also, the corresponding changes in other materials are also not shown.

**Comment by hollasch** [comment]
For "corresponding changes in other materials", see #1019.

**Comment by rupsis** [comment]
Resolved in #1514
