### ISSUE TITLE
Listing 3.39: Rename `axis_A`/`axis_B` to `u`/`v`

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#1316]
Benny Tsang writes:
> (Book 3) Listing 39: the variables `axis_A` and `axis_B` should be `u` and `v`, respectively.

**Comment by rupsis** [comment]
@hollasch Can you confirm https://github.com/RayTracing/raytracing.github.io/commit/09f31bb12d9e2e540aa0e7678717be87218861de resolves this?

**Comment by hollasch** [comment]
Ah, yes it does.
