### ISSUE TITLE
Broken link to `in1weekend.blogspot.com` in first book

### ISSUE THREAD

**Issue by Urhengulas** [RayTracing/raytracing.github.io#1326]
The link to `https://in1weekend.blogspot.com/` in the introduction of the first book is broken, because it sends me to `https://in1weekend.blogspot.com/,` instead (note the comma at the end).

Not sure how to fix it, because in the HTML it is just as a plain link. Maybe insert a space between link and comma?

https://github.com/RayTracing/raytracing.github.io/blob/95975fe79a13f95d078c82dbee1bf38b7177589e/books/RayTracingInOneWeekend.html#L69

**Comment by rupsis** [comment]
@hollasch  I can confirm this issue is resolved by #1347. 

Should be good to close this out.
