### ISSUE TITLE
In One Weekend: Improvement - PPM's potential not present and random device as seed

### ISSUE THREAD

**Issue by Kethers** [RayTracing/raytracing.github.io#1329]
Hi, recently I relearn the book 1 and find some potential improvements:
1. PPM format encoding: On Windows 11 or 10, default encoding of terminal is utf-16le while on Linux is utf-8, which might makes image viewer failed to show ppm image on Windows. Reencoding the ppm file with utf-8 will fix that. I think better mention it in the book for beginners' convenience.
2. In rtweekend.h, in random_double() function, use ``std::random_device`` as the seed for mt19937 generator, which gives better randomization.

```cpp
inline double random_double()
{
	// Returns a random real in [0,1)
	static std::random_device rd;
	static std::uniform_real_distribution<double> distribution(0.0, 1.0);
	static std::mt19937 generator(rd());
	return distribution(generator);
}
```

**Comment by hollasch** [comment]
Please don't lump multiple issues into one.

For the PPM issue, this is mentioned in book 1, section 2.2, pointing to a complete discussion of the issue.

For the random number, the simpler `rand()` function is sufficient, faster, and has the benefit that it produces the same stream from run-to-run, often a help when debugging. High-quality randomness is key for cryptographic purposes, but sometimes overkill when all that's really needed is uniform sampling. It is possible that weak RNGs can sometimes yield visible artifacts in special cases, but that isn't something we've encountered with these simple scenes.

**Comment by d-k-ivanov** [comment]
@Kethers,

May I add my experience playing with different random devices in this Ray-Tracing Framework.

According to my experience, the mentioned Mersenne Twister (mt19937) device is very slow. Indeed, in some cases you'd like to have wider random numbers (for example, if you're generating some noisy images and would like to make it more colourful in terms of coloured pixels distributions).

If you definitely want to use wider random devices, have a look at `std::minstd_rand` as random engine, it's faster, or move to [Xoshiro](https://prng.di.unimi.it/) or [PCG](https://www.pcg-random.org/index.html). But the integration would require some effort.

Anyway, as mentioned by Steve, the `rand()` approach fits perfectly well for performant generation of beautiful images using ray-tracing.
