### ISSUE TITLE
[Book2] Chapter 3.8, Listing 17, typo in `box` (should be `bbox`)

### ISSUE THREAD

**Issue by gau-nernst** [RayTracing/raytracing.github.io#1332]
As described in the title, [Book2] Chapter 3.8, Listing 17, there is a typo in `!box.hit(r, ray_t)`. I believe it should be `bbox` instead.

**Comment by hollasch** [comment]
Fixed in `dev` branch, commit 3d18a10dc806dd5c58eb6939e1673516604d1447
