### ISSUE TITLE
[Book 2] Section 2.4 Unnecessary section in regards to Interval class (?)

### ISSUE THREAD

**Issue by graciexia8** [RayTracing/raytracing.github.io#1334]
In section **_2.4 Adding Moving Spheres_**: I'm not sure if this was put in the wrong place or that it was duplicated by accident. If it was intentional, could someone explain to me why we need to change this function inside the interval class?

![image](https://github.com/RayTracing/raytracing.github.io/assets/15184219/57559654-3217-4476-a56d-c14bcb989c81)

**Comment by hollasch** [comment]
Fixed in `dev` branch, commit f4ebec4.
