### ISSUE TITLE
[Book 1]: Section 6.8 (In Dev) size() method not needed in interval class

### ISSUE THREAD

**Issue by rupsis** [RayTracing/raytracing.github.io#1351]
In Book 1, Version 4.0.0-alpha.1 the `size()` method in the `interval` class doesn't exist (nor should it, it isn't used for book 1).

Currently in Dev, the `size()` method is showing up in Section 6.8

```c++
class interval {
 ...
  double size() const {
          return max - min;
      }
}
```

Since this method isn't used until Book 2, it should be introduced in Book 2 Section 3.4, listing 7 (with the `expand()` method). 

p.s I'm happy to make these change.

**Comment by hollasch** [comment]
Yes, that's generally true for specific methods. In this case, it's a very basic method that helps to illustrate the way the interval class works, and we cheat a bit knowing that it will come in handy later. There are a few other examples of this, and the (tiny) benefit is that we don't need to motivate and document it separately in a listing later. I think we'll keep it as-is for now.
