### ISSUE TITLE
[Book 2]: 3.4, Listing 8: Using ix, iy, iz for initializer list instead of _x, _y, _z

### ISSUE THREAD

**Issue by rupsis** [RayTracing/raytracing.github.io#1352]
For `class aabb`, the parameterized constructor arguments are `ix`, `iy`, `iz`, instead of `_x`, `_y`, `_z` (used throughout the rest of the book(s)). 

Exp:
```c++
class aabb {
...
aabb(const interval& _x, const interval& _y, const interval& _z)
      : x(_x), y(_y), z(_z)
    {
        pad_to_minimums();
    }
}
```

Is there a specific reason for this?

Happy to make these changes.

**Comment by hollasch** [comment]
This follows the pattern used throughout the book when initializing member variables whose names are naturally the same as you'd give for the parameters. For example, see the `sphere` class and constructor parameters.

**Comment by rupsis** [comment]
This [sphere constructor](https://github.com/RayTracing/raytracing.github.io/blob/dev/src/TheNextWeek/sphere.h#L22-L23)? Doesn't that follow the same `_` convention?

**Comment by hollasch** [comment]
Ah, I had it backwards. Yeah, go ahead and submit the change.
