### ISSUE TITLE
[Book 3] layout error in chapter3.6, equations with `random_double`

### ISSUE THREAD

**Issue by lobneroO** [RayTracing/raytracing.github.io#1355]
Just a simple layout error, but in chapter 3.6 the `random_double` in equations currently gets rendered with a very small `d` and no underscore. I checked with v3, it was correct in there, so this is a regression for v4.

![image](https://github.com/RayTracing/raytracing.github.io/assets/17877050/869df6fb-59ac-4629-b54d-741a81eba742)

In [TheRestofYourLife](https://github.com/RayTracing/raytracing.github.io/blob/release/books/RayTracingTheRestOfYourLife.html) in lines 1084 and 1101 it probably should be `$$ ... random\textunderscore double ... $$` instead of `$$ ... random_double ... $$`.

I'm willing to make a pull request but wanted to follow the contribution guidelines

**Comment by hollasch** [comment]
Fixed in `dev` branch, commit 48caa61, PR #1330.
