### ISSUE TITLE
[Book 2] List 39 introduces u,v,w, then re-introduces them again in Listing 44

### ISSUE THREAD

**Issue by rupsis** [RayTracing/raytracing.github.io#1358]
Listing 39 (in Dev)  introduces 3 variables (u,v,w)

![image](https://github.com/RayTracing/raytracing.github.io/assets/9646385/5fdca654-4590-4fa2-8d71-2f2de5bb9a99)

(In Listing 40 it's improved with Hermitian Smoothing)

in Listing 44, we swap over to use Random Vectors, and the highlighting suggest we add u,v,w back in again:
![image](https://github.com/RayTracing/raytracing.github.io/assets/9646385/163553a2-e088-4f3a-b5cc-681a0a616f16)

Showing the removal of the Hermitian Smoothing _might_ make more visual sense:
![image](https://github.com/RayTracing/raytracing.github.io/assets/9646385/2a841d04-077f-46f2-8817-1e9a963acc2c)

Anyway, not really an issue. It tripped me up for a second, and I figured it was worth mentioning. Happy to make this change :)

**Comment by hollasch** [comment]
I like the removal idea — go for it.

**Comment by rupsis** [comment]
Fixed in https://github.com/RayTracing/raytracing.github.io/commit/8646911a5b7a7562e113002fc7b3222934396798
