### ISSUE TITLE
[Book 2]: Listing 55: Suggestion - Use interval for is_interior conditional check

### ISSUE THREAD

**Issue by rupsis** [RayTracing/raytracing.github.io#1359]
In listing 55 we check if alpha and beta are within the interval [0,1]. We could use our handy interval class to easily check if an interval `contains` those points:

```c++
  virtual bool is_interior(double a, double b, hit_record &rec) const {
    interval region = interval(0, 1);
    // Given the hit point in plane coordinates, return false if it is outside the
    // primitive, otherwise set the hit record UV coordinates and return true.
    if (!region.contains(a) || !region.contains(b)) {
      return false;
    }

    rec.u = a;
    rec.v = b;
    return true;
  }
 ```
 
 Nothing wrong with the previous implementation, I just think this is a little easier to read. 
 Happy to make the changes if we decide to go this direction :)

**Comment by hollasch** [comment]
region → unitInterval

**Comment by rupsis** [comment]
Fixed in https://github.com/RayTracing/raytracing.github.io/commit/b3bd1e3f6a08477371b2a7667207d53ee1b87c34
