### ISSUE TITLE
[Book 2] image 15: is the "Perlin noise, marbled texture" image wrong?

### ISSUE THREAD

**Issue by rupsis** [RayTracing/raytracing.github.io#1360]
Seems like the perlin marble noise image is from the old book?
![image](https://github.com/RayTracing/raytracing.github.io/blob/release/images/img-2.15-perlin-marble.png?raw=true)

Running `two_perlin_spheres()` on dev branch produces this results:
![perlin_marble](https://github.com/RayTracing/raytracing.github.io/assets/9646385/2ee6e2ab-bbc7-4683-b257-6e8f973bccc6)

Happy to update the image (or related code) :)

**Comment by rupsis** [comment]
I suppose if this _is_ the case, then subsequent  images (17, 18) would also need to be updated.

**Comment by hollasch** [comment]
Fixed with #1363
