### ISSUE TITLE
[Book 2] Listing 68: Should include "aabb::empty" and "aabb::universe" to be consistent with Listing 69

### ISSUE THREAD

**Issue by rupsis** [RayTracing/raytracing.github.io#1361]
No real issue, more of an inconsistency. Listing 68 adds the `operator+`

```
class aabb {
    ...
};

aabb operator+(const aabb& bbox, const vec3& offset) {
    return aabb(bbox.x + offset.x(), bbox.y + offset.y(), bbox.z + offset.z());
}

aabb operator+(const vec3& offset, const aabb& bbox) {
    return bbox + offset;
}
```

but doesn't include the `aabb::empty` & `aabb::universe` in the diff. Whereas Listing 69 includes the `interval::empty` & interval::universe` in the diff. 

happy to make this change :)

**Comment by hollasch** [comment]
Fixed in 1d2740a
