### ISSUE TITLE
[Book 3] Listing 6: missing recip_sqrt_spp & sqrt_spp

### ISSUE THREAD

**Issue by rupsis** [RayTracing/raytracing.github.io#1373]
Book 3 listing 6 doesn't introduce private members `sqrt_spp` and `recip_sqrt_spp`. Looking at the source code, it seems like they're declared and used inside the `initialize()` method. [Ref](https://github.com/RayTracing/raytracing.github.io/blob/release/src/TheRestOfYourLife/camera.h#L75)

Additionally, in listing 40, it seems to introduce `int sqrt_spp = int(sqrt(samples_per_pixel));` in the `render()` method, which I believe can be removed. 

Happy to make these changes.

**Comment by hollasch** [comment]
Subsumed by #1421.
