### ISSUE TITLE
[Book 2] Listing 32, hearder perlin.h is not introduced yet

### ISSUE THREAD

**Issue by cccccz** [RayTracing/raytracing.github.io#1375]
![image](https://github.com/RayTracing/raytracing.github.io/assets/60713799/336ca9e7-a8b6-4fde-9467-95b322b825ac)
as title

**Comment by rupsis** [comment]
Seems to have been fixed in Dev:

<img width="753" alt="image" src="https://github.com/RayTracing/raytracing.github.io/assets/9646385/f3e8ed59-02af-471d-b362-b75e9b4ad39d">

**Comment by cccccz** [comment]
nice. For the future I will also check if it has already been fixed in Dev
