### ISSUE TITLE
[Book 2] aabb.pad() has been renamed to pad_to_minimums in codes, but writing is not consistent to the code

### ISSUE THREAD

**Issue by wlbksy** [RayTracing/raytracing.github.io#1403]
`aabb.pad()` has been renamed to `pad_to_minimums` in codes, but writing is not consistent to the code.

This need some writing and listed codes change in book2 section6.1.

I'll leave this to people who has time to fix it.

**Comment by armansito** [comment]
Ah yes, @hollasch  it looks like the refactor in #1238 missed section 6.1 where the narrative explains and introduces `aabb::pad()`. I can take this on unless you've got further edits in the works.

**Comment by hollasch** [comment]
Yeah, I'd appreciate if you could tackle this, but let's wait until the quad bbox fix gets in.

**Comment by armansito** [comment]
> Yeah, I'd appreciate if you could tackle this, but let's wait until the quad bbox fix gets in.

Thank you for merging #1404. I think we can close this now as I believe @wlbksy intended to push their bbox fix after resolving this one.

**Comment by wlbksy** [comment]
Yes. I think you can close this issue.
