### ISSUE TITLE
logic error in dielectric::scatter

### ISSUE THREAD

**Issue by yashasg** [RayTracing/raytracing.github.io#141]
cosine = m_refIdx * -Dot( In.m_direction , Rec.normal ) / In.m_direction.Length( );

multiplying refraction index to cosine got rid of a black pixel artifact I was seeing on my render.

P.S: notice the minus sign next to the Dot, this is for the else part where Dot product is <=0.

**Comment by trevordblack** [comment]
Blocked y #270
