### ISSUE TITLE
Book 2, Chapter 5.7 -- incorrect image

### ISSUE THREAD

**Issue by dimitry-ishenko** [RayTracing/raytracing.github.io#1415]
The _release_ branch of the book shows incorrect image in _**Chapter 5.7 Adjusting the Phase**_. Specifically, the period of the sine wave is not scaled.

The image has been fixed in the _dev_ branch (74a5c2589ef9fc0d9fc685d38ef0fb5272f31a9b). However, the _dev_ branch has incorrect equation in Listing 49, which does not actually produce that image.

In other words, the _release_ branch currently shows:

> ```c++
> class noise_texture : public texture {
>   public:
>     noise_texture() {}
> 
>     noise_texture(double sc) : scale(sc) {}
> 
>     color value(double u, double v, const point3& p) const override {
>         auto s = scale * p;
>         return color(1,1,1) * 0.5 * (1 + sin(s.z() + 10*noise.turb(s)));
>     }
> 
>   private:
>     perlin noise;
>     double scale;
> };
> ```
> **Listing 47**: [texture.h] _Noise texture with marbled texture_
> 
> Which yields:
> 
> ![](https://raw.githubusercontent.com/RayTracing/raytracing.github.io/1d2740a752d8cfa7ae75b2c420ed06d8b2a83780/images/img-2.15-perlin-marble.png)

And the _dev_ branch shows:

> ```c++
> class noise_texture : public texture {
>   public:
>     noise_texture() {}
> 
>     noise_texture(double sc) : scale(sc) {}
> 
>     color value(double u, double v, const point3& p) const override {
>         return color(.5, .5, .5) * (1 + sin(scale * p.z() + 10 * noise.turb(p, 7)));
>     }
> 
>   private:
>     perlin noise;
>     double scale;
> };
> ```
> **Listing 49**: [texture.h] _Noise texture with marbled texture_
> 
> Which yields:
> 
> ![](https://raw.githubusercontent.com/RayTracing/raytracing.github.io/74a5c2589ef9fc0d9fc685d38ef0fb5272f31a9b/images/img-2.15-perlin-marble.png)

However, the code in the _release_ branch yields the image shown in the _dev_ branch. And vice versa.

**Comment by dimitry-ishenko** [comment]
On a related note, the code in _**Chapter 5.6 Introducing Turbulence**_ in the _dev_ branch is missing the scaling factor:

```c++
class noise_texture : public texture {
  public:
    noise_texture() {}

    noise_texture(double sc) : scale(sc) {}

    color value(double u, double v, const point3& p) const override {
        return color(1,1,1) * noise.turb(p, 7);
    }

  private:
    perlin noise;
    double scale;
};
```

but the image below it is shown with the scaling factor applied.

This is not a problem in the _release_ branch, which shows the following code and the matching image:

```c++
class noise_texture : public texture {
  public:
    noise_texture() {}

    noise_texture(double sc) : scale(sc) {}

    color value(double u, double v, const point3& p) const override {
        auto s = scale * p;
        return color(1,1,1) * noise.turb(s);
    }

  private:
    perlin noise;
    double scale;
};
```

So, there seems to be some inconsistency between the _release_ and the _dev_ branches. Perhaps some changes were committed directly to the _release_ branch and merged to the _dev_ branch?

**Comment by armansito** [comment]
Thank you for the report and yes, this is a known discrepancy. The images were updated with a broken version of the scaling factor. The code got fixed but the images haven't been updated.

I believe @hollasch is planning to update all the images when he validates the book content.

**Comment by hollasch** [comment]
Yes, see #779 in milestone `v4.0.0-alpha.2-release`.
