### ISSUE TITLE
Chapter 7: tangent unit sphere clarity

### ISSUE THREAD

**Issue by acarcher** [RayTracing/raytracing.github.io#142]
In chapter 7, we have the sentences:

"Pick a random point s from the unit radius sphere that is tangent to the hitpoint, and send a ray
from the hitpoint p to the random point s. That sphere has center (p+N)."

After puzzling over this for a while (even with the picture) it finally dawned on me that it is the unit sphere itself that is tangent to the hitpoint p, and not the point s. It seems obvious in retrospect, but I think this point could be made clearer. I think my confusion comes from two facts:

1) hitpoint p (and the ray that generates it) is not labeled in the diagram (so it was not obvious to me that the surface underneath the unit sphere is what is actually being hit by the ray)
2) point s would be secant to hitpoint p

To trace my confusion: I originally imagined that the unit sphere was at the center of the sphere being hit and could therefore approximate a sphere of any size; then I imagined the unit sphere's center was at hitpoint p and we were looking for a point on the sphere tangent to it (which made no sense to me); and then finally I partially understood the unit sphere's tangency to p, but still thought point s would be secant to p and that the modifier "tangent" applied to s and not the sphere.

**Comment by hollasch** [comment]
Will address this in #263.

**Comment by hollasch** [comment]
Ah, this is supposed to be the open one.

**Comment by petershirley** [comment]
Here is a figure checked into branch  v3newfigures as fig.rand-vector.jpg  
![image](https://user-images.githubusercontent.com/2800266/77267297-ccb3fb00-6c67-11ea-815a-24d719188a00.png)

**Comment by hollasch** [comment]
Fixed in #409
