### ISSUE TITLE
Clang --debug vs --release flags have no performance benefit 

### ISSUE THREAD

**Issue by rupsis** [RayTracing/raytracing.github.io#1432]
While testing out #1422, I noticed we get a huge performance boost on OSX/Clang while using the `-O3` flag. 
However, the Cmake `--debug` vs `--release` flags seem to have no impact on performance. 

We should add a conditional check against Clang in the `CMakeList.txt` to set the `-O3` [optimization flag](https://clang.llvm.org/docs/CommandGuide/clang.html#code-generation-options).

```
if (CMAKE_BUILD_TYPE STREQUAL "Release")
    add_compile_options(-O3)
endif()
```

Happy to make these changes :D 

_Originally posted by @rupsis in https://github.com/RayTracing/raytracing.github.io/issues/1422#issuecomment-1989587869_

**Comment by armansito** [comment]
Yes, I think we should add this for Clang. If you have the time for it I would certainly appreciate it :)
