### ISSUE TITLE
Book 2 Listing 5 Redefines `interval::contains`

### ISSUE THREAD

**Issue by codyd51** [RayTracing/raytracing.github.io#1441]
Hi! Firstly, thank you for the wonderful and entertaining work! 

I apologise if I've recognised something in error, but it appears as though Book 2, Listing 5 redefines `interval::contains`, which was originally defined in Book 1, Listing 26. 

<img width="300" alt="Book 1, Listing 26" src="https://github.com/RayTracing/raytracing.github.io/assets/4972184/2eebcfce-c259-48e4-9e0e-2271c8d4feca">

<img width="300" alt="Book 2, Listing 5" src="https://github.com/RayTracing/raytracing.github.io/assets/4972184/c4a2ddfb-ea36-4a82-89e8-6be4e47e216d">

The prose in Book 2 introducing the listing also seems to imply that `contains` was referenced in the code or prose just above, but it doesn't appear to have been mentioned. 

It looks as though Listing 5 and the leading line should be dropped. This issue appears to be present in version 4.0.0-alpha.1.

**Comment by rupsis** [comment]
It's resolved in Dev by https://github.com/RayTracing/raytracing.github.io/commit/f4ebec4063c6b0dea23d5e480d53e07debea3927
