### ISSUE TITLE
Book 1, Section 14.1 incorrectly references pixel sample count

### ISSUE THREAD

**Issue by codyd51** [RayTracing/raytracing.github.io#1442]
The end of Book 1, Section 14.1 incorrectly quotes the currently value of `samples_per_pixel`, and claims that it was previously set to `10`. 

<img width="300" alt="Book 1, Section 14.1" src="https://github.com/RayTracing/raytracing.github.io/assets/4972184/3f3a6660-1756-415e-ab19-9ad742d034f6">

`samples_per_pixel` is indeed `10` in the default `camera` field:

<img width="300" alt="Book 1, Listing 74" src="https://github.com/RayTracing/raytracing.github.io/assets/4972184/18d77a20-5bca-4680-8af7-93922c00f17a">

However, in the sample code up to now, this field is initialised to 100:

<img width="300" alt="Book 1, Listing 62" src="https://github.com/RayTracing/raytracing.github.io/assets/4972184/b1da597c-2289-4061-a6b9-7a3870527565">

The prose in Section 14.1 should just be adjusted to say `100` instead of `10`. 

This issue is present in version 4.0.0-alpha.1.

**Comment by rupsis** [comment]
> The sample code uses a value of 10 in the interest of reasonable...

I believe this is referring to the accompanied source code, which has [cam.samples_per_pixel = 10](https://github.com/RayTracing/raytracing.github.io/blob/release/src/InOneWeekend/main.cc#L68).

Perhaps updating it to "The sample source code" would be clearer. @hollasch Thoughts?

**Comment by hollasch** [comment]
Or perhaps "the project source code". @rupsis , want to take a crack at it?

**Comment by hollasch** [comment]
Done.
