### ISSUE TITLE
Lambertian BRDF is actually cosine squared brdf

### ISSUE THREAD

**Issue by vchizhov** [RayTracing/raytracing.github.io#145]
The Lambertian brdf uses `random_in_unit_sphere`, however this induces a cosine squared brdf rather than a Lambertian one. To correct this, one has to use `random_on_unit_sphere` (this can be achieved through `normalize(random_in_unit_sphere)`). For more information see: https://github.com/vchizhov/Derivations/blob/master/Probability%20density%20functions%20of%20the%20projected%20offset%20disk%2C%20circle%2C%20ball%2C%20and%20sphere.pdf
Note that this is a mistake in both the book and the code.

**Comment by trevordblack** [comment]
We are aware of the problem.
This (#145). #155, and #179 are all probably going to make the next release (2.1.0 or 2.0.1).
We are in no position to merge anything for the next few weeks.

**Comment by hollasch** [comment]
Resolved in PR #229, development branch.
