### ISSUE TITLE
[Book 2] Chapter 7. Lights: Not all materials are born emitting

### ISSUE THREAD

**Issue by dimitry-ishenko** [RayTracing/raytracing.github.io#1456]
In chapter _7. Lights_ we introduce virtual function `emitted()`.

However, not all materials emit light.

And, while the default implementation (returning `color{0, 0, 0}`) yields the correct result mathematically (adding zero to the ray color does not change its value), it's not entirely correct from the standpoint of semantics. Because, semantically we are saying that the material emits "black" light, which it doesn't...

I know it's a bit of a nitpick, but we do make that distinction in the `scatter()` function, which returns true or false. We could have likewise returned `color{0, 0, 0}` in the `attenuation` variable to indicate that the material didn't scatter any light instead of returning true/false.

Again, I understand it's a nitpick, and it's a bit more pronounced in [my own implementation](https://github.com/dimitry-ishenko/raytracing.github.io/blob/exercise/material.hpp), where instead of returning true/false I return:

```c++
struct scatter
{
    ray3 ray;
    color3 atten;
};

struct material
{
    virtual std::optional<scatter> get_scatter(const ray3& ray, const hit&) const = 0;
};
```

So, when I started adding the `emitted()` function, I've realized, why should scatter be optional, but emitted not?

Anyway if you don't think it's worth adding this distinction, feel free to close the issue.

**Comment by hollasch** [comment]
Pretty much everything around us emits energy in the infrared range. Convolve that spectrum with the short/medium/long wavelength response curves of our retina, and you get total response of zero for each one. It doesn't mean that everything emits nothing; it means that what it _does_ emit doesn't register on the three limited scalar sensors in our eyes. In this sense, you might conclude that it makes more sense to return a zero level for each sensor, without asserting that such a material is emitting nothing. Put another way, black ≠ nothing. (Also, there are infinitely many different spectra that equal black, just as there are infinitely many colors that look identical to any given color to a human.)

None of this really matters however, as we're just implementing a ray tracer. You're free to interpret the `emitted()` function as returning true only if the spectrum registers a non-zero response for a typical human eye, or to interpret it as returning the response level of each of the three standard human retina cones. I actually kind of like that we do it both ways, and readers are free to choose either approach or do some third option.

**Comment by dimitry-ishenko** [comment]
> Pretty much everything around us emits energy in the infrared range.

Well yes... But, we could also make the same argument for scattering. I was mainly referring to the difference in the interfaces between `scatter()` and `emitted()`.

> I actually kind of like that we do it both ways, and readers are free to choose either approach or do some third option.

If you are doing it for learning sake, then I understand. But, in general, I would disagree as from the programming standpoint you usually want to keep consistent interface, so that you spend less time trying to remember/look up function signatures and focus on task at hand.

**Comment by armansito** [comment]
> And, while the default implementation (returning color{0, 0, 0}) yields the correct result mathematically (adding zero to the ray color does not change its value), it's not entirely correct from the standpoint of semantics. Because, semantically we are saying that the material emits "black" light, which it doesn't...

I don't think the text implies the emission of "black" light. You could interpret the returned `color` value to represent the emitted light intensity, where `color(0, 0, 0)` represents 0 intensity (in all 3 color channels) which contributes nothing to the total radiance. I think the mathematical model matches the intended logic fairly closely.

Not that there is anything wrong with having `emitted()` return a `std::optional<color>` and performing the addition conditionally; I think this is a design choice and you're more than encouraged to adapt the code according to your preference. Personally, I don't think that this makes the semantics particularly more clear, for example a material implementation could still return a `optional{color(0, 0, 0)}` which one might view as a redundant corner case of the abstraction.

**Comment by dimitry-ishenko** [comment]
@armansito I am not advocating for the use of `std::optional` per se (although in my humble opinion it more clearly shows the [intent](https://github.com/dimitry-ishenko/raytracing.github.io/blob/exercise/material.hpp)).

The main point I was trying to bring up is inconsistency between `scatter()` and `emitted()`. All the arguments you and @hollasch bring up in regards to the emitted light can likewise be applied to the scattered light. Yet scattered light is optional (by means of the return value of `scatter()`) and emitted light is "mandatory".

**Comment by armansito** [comment]
> The main point I was trying to bring up is inconsistency between `scatter()` and `emitted()`. All the arguments you and @hollasch bring up in regards to the emitted light can likewise be applied to the scattered light. Yet scattered light is optional (by means of the return value of `scatter()`) and emitted light is "mandatory".

I understand. While I sympathize with wanting to keep the function signatures consistent, I think this is more or less related to your interpretation of what the returned types mean. In my view `emitted()` returns what's inherently a _numerical_ quantity (and $0$ represents what we want it to represent). I can't say the same thing for `scatter()`: we always want to explicitly detect the case when the material doesn't scatter and do something different. Although you could just as well have `scatter()` return a degenerate `vec3(0)` and treat that special case to mean "no direction", I think returning a `bool` (or a `optional<scatter>` like in your version) makes for a clean representation for that case.

The point I'm trying to make is that I don't think these signatures are necessarily inconsistent. In the end, I think both your version and the version in the book are equally valid ways to define these signatures.

**Comment by hollasch** [comment]
Agreed. I think Dimitry's suggestion is a fine inclination. I just don't see it as a significant improvement either way. My personal preference is to let values flow through computation, eliminating branching where possible (a good inclination when working on low-level hardware), so I might be inclined to tackle the approach with the `scatter()` function. Despite my own leanings, I don't think it's a meaningful improvement.

**Comment by dimitry-ishenko** [comment]
Well, thank you everyone for the feedback. I will go ahead and close the issue.
