### ISSUE TITLE
Book1 The last of 2.1 : The description of the code which outputs the example PPM file suspiciously has an error

### ISSUE THREAD

**Issue by chiikusa** [RayTracing/raytracing.github.io#1470]
The description about the code which outputs the example PPM file suspiciously has an error.

"Red goes from fully off (black) to fully on (bright red) from left to right, and green goes from fully off at the top to black at the bottom"

I thought that it should be "Red goes from fully off (black) to fully on (bright red) from left to right, and green goes from fully off at the top to [bright green] at the bottom".

**Comment by hollasch** [comment]
Duplicate #1344. Changes in `dev`.
