### ISSUE TITLE
Add missing std:: namespace

### ISSUE THREAD

**Issue by dimitry-ishenko** [RayTracing/raytracing.github.io#1487]
There are a number of small functions throughout the course that are referred to in global namespace, for example:

* `fmin`, `fmax`
* `sqrt`
* `fabs`
* `sin`, `cos`, `tan`
* `rand`

Two of them -- `sqrt` and `fabs` -- are pulled into global namespace with the `using` directive inside `rtweekend.h`, but others -- aren't. Two possible solutions:

1. Prefix all functions with `std::` namespace (preferred).
2. Pull missing functions into global namespace (poor practice).

**Comment by hollasch** [comment]
I'm inclined to just pull them in to the global namespace, but agree that the approach should be consistent.

**Comment by hollasch** [comment]
@dimitry-ishenko — please create a PR adding yourself to the `books/acknowledgments.md.html` file, with optional hotlink.

**Comment by hollasch** [comment]
Given the fact that the standard library names above are all three or four letters in length, I think I'm just going to go with an explicit prefix. This also helps readers to get a hint about functions they do and don't need to have implemented.

**Comment by hollasch** [comment]
Ugh. All right, guess I'm going to be inconsistent. It's too painful with `std::make_shared` and `std::shared_ptr`, as that causes new line wraps all over the place, plus the fact that these two names are highly unlikely for anyone to collide with in their own implementations. Everything else will get the `std::` prefix though.

**Comment by hollasch** [comment]
By the way, one thing that I'm currently puzzled by is that dropping the using statements does _not_ cause unprefixed functions to generate errors. I'm not sure why.

**Comment by dimitry-ishenko** [comment]
> By the way, one thing that I'm currently puzzled by is that dropping the using statements does _not_ cause unprefixed functions to generate errors. I'm not sure why.

Some of these functions also exist in C. And, since most C++ compilers are also C compilers, they pull in those C headers and "re-declare" (with `using`) the functions inside `std::` namespace. Side effect of this is that the functions end up being leaked into the global namespace.

**Comment by hollasch** [comment]
Also `log`, `atan2`.

**Comment by dimitry-ishenko** [comment]
> @dimitry-ishenko — please create a PR adding yourself to the `books/acknowledgments.md.html` file, with optional hotlink.

@hollasch I am gonna be famous now... 😊
