### ISSUE TITLE
Support compiling on Windows 10

### ISSUE THREAD

**Issue by ronaldfw** [RayTracing/raytracing.github.io#149]
Getting the code to run on Windows 10 is fairly involved. Setting up a Visual Studio solution is straightforward but there are a number of code portability issues that come up and need some effort to resolve. 

The one that takes the most time is that drand48() does not seem to be supported on Windows 10. (I believe "MAXFLOAT" is another issue, but I would have to confirm.)

There are some suggestions to fix the drand48() issue here: https://stackoverflow.com/a/11068161 (including the option to just copy & paste the drand48() code into the project). In my own project I use <random> (C++11) to generate numbers.

**Comment by hollasch** [comment]
Fixed in PR #213
