### ISSUE TITLE
Stick with blue middle sphere in book 1

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#1492]
Images 1.13 and 1.14 use dull-orange for the middle sphere, and then without motivation switch to a blue sphere. Keep the color consistent by using the blue color from the start.

**Comment by rupsis** [comment]
@hollasch Do we want the right sphere to be a shiny metal? (like your update IOR images), or remain the same rough metal material?

**Comment by hollasch** [comment]
That's a separate issue.

**Comment by rupsis** [comment]
Addressed in #1493
