### ISSUE TITLE
[Book 3] Update Captions to use LaTeX $\pi$ 

### ISSUE THREAD

**Issue by rupsis** [RayTracing/raytracing.github.io#1494]
For the captions, we've been using the ~ASCII~ Unicode 'π' where the rest of the book has been using the LaTeX $\pi$. 

For consistency, we can make the captions render the same as the rest of the book. 

<img width="745" alt="image" src="https://github.com/RayTracing/raytracing.github.io/assets/9646385/6b14fc46-04e5-40cb-b099-dae98723919e">

**Comment by hollasch** [comment]
Edit: ~ASCII~ → Unicode above.

**Comment by rupsis** [comment]
Looked over the other books, and no other LaTeX listing were missing. 

This was addressed in https://github.com/RayTracing/raytracing.github.io/pull/1462
