### ISSUE TITLE
Book 3.4: Sphere Importance Sampling

### ISSUE THREAD

**Issue by rupsis** [RayTracing/raytracing.github.io#1500]
Perhaps I'm just slow, but for Listing 16, the `f()` function took me a little while to figure out.

```
double f(const vec3& d) {
    auto cosine_squared = d.z()*d.z();
    return cosine_squared;
}
``` 

If I understand correctly, $cos(\theta)^2$ here is $(\cos(0^\circ) *z)^2$ (where Z is from the `random_unit_vector`) 
and since $cos(0^\circ) = 1$ we're left with `d.z()*d.z()`.

The text doesn't make that obvious. Perhaps (and very likely) the issue is me. But if my understanding _is_ correct, maybe some clarification could be useful. A small attempt on my part:

<img width="744" alt="image" src="https://github.com/RayTracing/raytracing.github.io/assets/9646385/c152e414-f7d3-4ba4-8f33-dae105876236">

**Comment by hollasch** [comment]
Good point. I don't know if I would have made the connection myself. I would actually expound on this a bit further. Something like:

> If the integrand is $\cos^2(\theta)$, and $\theta$ is the angle with the $z$ axis, then $\theta = 0$, and $\cos^2(0) = 1$.

I'm still missing where the $z$ comes in, though. Why is $\cos^2(\theta) = (\cos(0\deg)\cdot z)^2$?

@trevordblack? @petershirley?

**Comment by dimitry-ishenko** [comment]
@rupsis @hollasch I think you guys got this wrong. 😺 

From [scalar projection](https://en.wikipedia.org/wiki/Scalar_projection) we know that projection of vector $a$ onto $b$ is equal to the length of $a$ multiplied by the cosine of angle $\theta$ between $a$ and $b$.

In our case we have random vector $d$ (of unit length) and from the chapter we know that **" $\theta$ is the angle with the $z$ axis."** Therefore we can say that projection of $d$ onto axis $z$ is equal $d_z = \lVert d \rVert \cos \theta = 1 \cdot \cos \theta$.

So, in our function $f(\theta, \phi) = \cos^2 (\theta)$ we can replace $\cos \theta$ with $d_z$ and get $f(\theta, \phi) = f(d) = {d_z}^2$.

**Comment by dimitry-ishenko** [comment]
There is one thing that's odd though...

In Chapter 3, we've been somewhat confusingly using $f$ to designate inverse of the CDF, and sometimes functions that we want to integrate. The distinction was the $f(d)$ referred to the former, and $f(x)$—to the latter.

Now, in Chapter 4 we introduce function $f(\theta, \phi)$ and **"we want to integrate this function over the surface of the unit sphere"**. So, this makes me think this is _NOT_ the inverse of the CDF, and yet in Listing 16 it is used as such...

I am lost.

**Comment by hollasch** [comment]
See also #1536. Things are a bit muddy in this region of the text.
