### ISSUE TITLE
[Book 3] Listing 23 plot.ly isn't a free resource anymore

### ISSUE THREAD

**Issue by rupsis** [RayTracing/raytracing.github.io#1502]
After listing 23:
> And plot them for free on plot.ly (a great site with 3D scatterplot support): 

plot.ly redirects to https://plotly.com/, which seams to be a paid enterprise product. 

Not a huge issue, but might be worth removing, or finding an alternative.

**Comment by hollasch** [comment]
Plotly is still open source. It does have enterprise components, but you can either use their open source libraries (https://github.com/plotly/plotly.js, https://github.com/plotly/plotly.py) or their free Dash install (https://plotly.com/dash).

We could also direct users to https://public.tableau.com/app/discover, but honestly, I don't want to go too far down this rabbit hole.

**Comment by rupsis** [comment]
Yeah, I actually ended up using mathplotlib. Definitely a bunch of open source / free ways to plot the graph. 
Considering this is the last (and most advanced) I'm sure people can figure it out for themselves.
