### ISSUE TITLE
[dev] Book 2, Listing 14: stale `hittable_list::hit` signature

### ISSUE THREAD

**Issue by armansito** [RayTracing/raytracing.github.io#1507]
The listing shows `bool hit(const ray& r, double ray_tmin, double ray_tmax, hit_record& rec) const override` but it should show `bool hit(const ray& r, interval ray_t, hit_record& rec) const override` (a change introduced in the book 1).

**Comment by hollasch** [comment]
Thanks for catching this — I'll fix it shortly.
