### ISSUE TITLE
Define proper and portable constants

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#151]
The current code base uses `M_PI` and `MAXFLOAT`. Both of these should be simple C++ constants defined somewhere. This may induce the need for a new common header (`constants.h`?).

Also note that `MAXFLOAT`, in addition to not being portable, also defines the maximum representable finite floating-point value. It should really be replaced with infinity (of the appropriate precision).

**Comment by ronaldfw** [comment]
@hollasch Mind if I take this? I will try to make all code compile and run on Windows/Linux/Mac and I think this is part of that.

I'll assign to myself, but please reassign if you have already started or want to work on this.

**Comment by hollasch** [comment]
Sweet — thanks Ronald!

**Comment by ronaldfw** [comment]
Fixed on the `future` branch.

**Comment by hollasch** [comment]
Now in the development branch.
