### ISSUE TITLE
[Book 3] Content suggestions

### ISSUE THREAD

**Issue by dimitry-ishenko** [RayTracing/raytracing.github.io#1518]
This was replaced by individual issues that can be dealt with one at a time.

**Comment by dimitry-ishenko** [comment]
We introduce Monte Carlo Method in chapter 2 and promptly start estimating value of π, which felt a bit like a diversion. Perhaps there could be short mention at the beginning that this method is used to improve sub-pixel sampling. I couldn't figure out what estimating value of π has to do with ray tracing (which is explained towards the end of the chapter).

**Comment by dimitry-ishenko** [comment]
"Buffon Needle" is mentioned twice in the book. IMHO, it doesn't add any value to the material. Especially for people who don't know what it is and have to go look it up elsewhere.

**Comment by dimitry-ishenko** [comment]
In chapter 3 we introduce expected values, integrals, histograms, density functions, and a whole lot of other math without explaining what it's for until the end of chapter. Maybe there can also be a short explanation at the beginning of the chapter why we need them all?

**Comment by dimitry-ishenko** [comment]
Chapter 3.1:

![Screenshot from 2024-04-10 21-40-19](https://github.com/RayTracing/raytracing.github.io/assets/2858291/78ae381e-827e-4ec8-809e-a03c496093a1)

To say that _average(Y) = E[Y]_ is not technically correct... If I have 6-sided die, my expected value is:
```
E[Y] = 1⋅(1/6) + 2⋅(1/6) + 3⋅(1/6) + 4⋅(1/6) + 5⋅(1/6) + 6⋅(1/6) = 21/6 = 3.5
```

But, if I do 10 rolls and get 6 each time, (however improbable) my average value is:
```
average(Y) = (6 + 6 + 6 + 6 + 6 + 6 + 6 + 6 + 6 + 6) / 10 = 6
```

When N is sufficiently large, then I can agree with that statement, but the value on N is not mentioned.

**Comment by dimitry-ishenko** [comment]
Chapter 3.2:

![Screenshot from 2024-04-10 22-54-44](https://github.com/RayTracing/raytracing.github.io/assets/2858291/849a6a75-a1d2-47bc-bf08-2e8eb6541c5a)

Add this for clarity?
![Screenshot from 2024-04-10 22-55-00](https://github.com/RayTracing/raytracing.github.io/assets/2858291/8267154d-de91-4181-af52-7785a34b6a54)

**Comment by dimitry-ishenko** [comment]
Chapter 3, at the very beginning, states that we can use Monte-Carlo method compute area of a circle with radius 1.

I feel like Chapter 3.1 tries to expound on that, but does it in a haphazard way. What I understood from Chapter 3.1 is that we can compute expected value of a function using Monte-Carlo method:

$$ E[f(x') | a \leq x' \leq b] \approx \frac 1 N \sum_{i=0}^{N-1} f(x_i) $$

At the same time, we've proven that:

$$ E[f(x') | a \leq x' \leq b] = \frac{1}{b - a} \int_{a}^{b} f(x) dx $$

And, since we know that:

$$ area(f(x), a, b) = \int_{a}^{b} f(x) dx $$

we can use Monte-Carlo method to compute area of an arbitrary function $f$:

$$ area(f(x), a, b) = (b - a) \cdot E[f(x') | a \leq x' \leq b] $$

$$ area(f(x), a, b) \approx \frac{b - a}{N} \sum_{i=0}^{N-1} f(x_i) $$

**Comment by dimitry-ishenko** [comment]
In Chapter 3.5 we can't seem to settle on which letter to use as a parameter for the CDF and keep switching between $x$ and $r$. This is not a big deal, just a bit disorienting. Here is a sample:

![Screenshot from 2024-04-15 22-28-51](https://github.com/RayTracing/raytracing.github.io/assets/2858291/146e47d2-a97e-4fae-b6f0-5bab01c03a77)

**Comment by dimitry-ishenko** [comment]
In Chapter

**Comment by hollasch** [comment]
Thank you!
