### ISSUE TITLE
Book 3.2.1: Buffon Needle

### ISSUE THREAD

**Issue by dimitry-ishenko** [RayTracing/raytracing.github.io#1529]
The term "Buffon Needle" is mentioned in chapters 2 and 3, but is not used anywhere in the book, and carries no useful information. It only acts as a distraction for people who are not familiar with it.

**Comment by rupsis** [comment]
I personally found the mention be useful. I was unfamiliar and looked it up, which helped my learn the material. 

With that said, we probably could do a better job mentioning it. But I don't think it entirely useless.

**Comment by dimitry-ishenko** [comment]
@rupsis I can see your point. The reason I brought this up is that I am a firm believer that a course should define all  the terms used in it. Otherwise, students end up getting dispersed or drop out altogether. And, since this particular term is not used in the course itself, IMHO it would be better to omit it.

**Comment by hollasch** [comment]
Moving into the v4.0.0 milestone for consideration. We may or may not punt this for the actual v4.0.0 release, depending on our progress.
