### ISSUE TITLE
Figure 3.8: Graph incorrectly labeled

### ISSUE THREAD

**Issue by dimitry-ishenko** [RayTracing/raytracing.github.io#1532]
The $x$ axis should be $P(x)$:

![fig-3 08-approx-f](https://github.com/RayTracing/raytracing.github.io/assets/2858291/6e1c3f17-050b-4106-a8a5-f3b7bedd8d0b)

**Comment by dimitry-ishenko** [comment]
The vertical axis **is** the $x$ axis (since $f(P(x)) = x$), which is why it goes from 0 to 2. And, the horizontal axis is the resulting CDF or $P(x)$ and goes from 0 to 1 (or 0-100% probability).

**Comment by dimitry-ishenko** [comment]
If that helps, here's fixed image that can be used as replacement:

![fig-3 08-approx-f](https://github.com/RayTracing/raytracing.github.io/assets/2858291/024ed33c-bd7c-4773-841a-61cce52cac0d)

**Comment by hollasch** [comment]
This intersects with #1531.
