### ISSUE TITLE
Book 2, 5.4. : Default constructor leaves noise_texture::scale uninitialized

### ISSUE THREAD

**Issue by tom-anders** [RayTracing/raytracing.github.io#1546]
This leads to undefined behavior when calling the default constructor (which the book does not do, but still)

The default value should probably be `1.0` ..?

**Comment by rupsis** [comment]
The default constructor was cleaned up in dev [#1521](https://github.com/RayTracing/raytracing.github.io/pull/1521/files#diff-a3cb92300537e3425aba44de696213d23368dbe4cbe4f26e5cb75ee870e51d9bL2255)

**Comment by hollasch** [comment]
The default constructor still exists, but many of our classes are more Plain Old Data than formal C++ classes. Compare to the `ray` class, for example. We strongly recommend that you use these books to write your own proper implementation, as we take many shortcuts.
