### ISSUE TITLE
I don't believe -1 to 1 represents a "unit cube"

### ISSUE THREAD

**Issue by hrakaroo** [RayTracing/raytracing.github.io#1555]
In the RayTracingInOneWeekend book around line 2314 in the `dev` branch the text reads:
```
First, we will use a rejection method to generate the random vector inside of the unit sphere. Pick
a random point in the unit cube, where $x$, $y$, and $z$ all range from -1 to +1, and reject this
point if it is outside the unit sphere.
```

While a unit sphere is defined as all points within one unit from a point in space, and therefore goes from -1 to 1, I don't believe it is correct that `$x$, $y$, and $z$ all range from -1 to +1` represents a unit cube as each side would have a length of 2 units.  I believe this is just a "cube" and not a "unit cube".

**Comment by dimitry-ishenko** [comment]
@hrakaroo is correct: https://en.wikipedia.org/wiki/Unit_cube. The fix is pretty trivial - drop the word _unit_ from _unit cube_.
