### ISSUE TITLE
`<<` and `>>` operators overloaded but never used

### ISSUE THREAD

**Issue by p1v0t** [RayTracing/raytracing.github.io#156]
In vec3.h file, the the `<<` and `>>` are overloaded for take vector element from standard input, and to print it, but never used in anywhere. I'm not sure it's a problem but it simply isn't necessary.

**Comment by hollasch** [comment]
`vec3::operator<<` is used in `theNextWeek/constant_medium.h`.

**Comment by hollasch** [comment]
Resolved in #226, changes in development branch.
