### ISSUE TITLE
[Book3] Typo in Listing 13?

### ISSUE THREAD

**Issue by YSakhno** [RayTracing/raytracing.github.io#1563]
Shouldn't function `pdf` be

```c++
double pdf(double x) {
    return 0.5 * x;
}
```

instead of `return 0.5;`?

I do not know much, but a function that returns constant value regardless of its input seems weird to me, especially in this context.

**Comment by dimitry-ishenko** [comment]
@YSakhno what makes it seem weird to you?

Chapter 3.7 says that we are using constant PDF over the interval [0, 2]. That alone should tell you the function will return constant value not dependent on `x`. 

If you use the data learned in the book, you should also be able to verify it yourself. We know that integral of the PDF over its interval must be equal to 1 (ie, 100% probability), so:

$$ \int_0^2 pdf(x) dx = \int_0^2 0.5 dx = 0.5 \int_0^2 dx = 0.5 \cdot x\big|_0^2 = 0.5 \cdot (2 - 0) = 1$$

QED

**Comment by YSakhno** [comment]
OK, I was confused by the function $`P(x) = x/2`$ immediately prior to the listing, and thought that $`P(x)`$ was the PDF.

**Comment by dimitry-ishenko** [comment]
Oh I see what you mean. In this case $P(x)$ refers to the CDF.

There is a bit of inconsistency with function and parameter names in the text. I've raised an issue #1531 in regards to the function parameters. Feel free to drop a note in there to unify function names as well.

There was also a relevant issue #1537 which deals with function names used in the code.

**Comment by hollasch** [comment]
I'll close this one out.
