### ISSUE TITLE
[Book 1]  Typo in Chapter 9.4

### ISSUE THREAD

**Issue by artogahr** [RayTracing/raytracing.github.io#1564]
https://github.com/RayTracing/raytracing.github.io/blob/c3a5b710ceb196b8e99b3c2a0dfebe57b82b8c5b/books/RayTracingInOneWeekend.html#L2673

The correct English sentence should be as such: 
> Not a lot of common everyday objects are perfectly diffused, so our visual intuition of how these objects behave under light can be poorly formed.

**Comment by hollasch** [comment]
A diffuse (adjective) surface is one that diffuses reflected light. The object itself is not diffused.

**Comment by artogahr** [comment]
TIL diffuse is also an adjective. Sorry to waste your time.

**Comment by hollasch** [comment]
No problem; thanks for the offer to help.
