### ISSUE TITLE
In a weekend between chapt 4 to chapt 5

### ISSUE THREAD

**Issue by Joeycho** [RayTracing/raytracing.github.io#157]
Hello, there!

I got this error message when I just followed the code, and run in my linux.

![raytracing_error](https://user-images.githubusercontent.com/29337166/64066671-234ede80-cc1d-11e9-8c8d-a66eccd6e179.PNG)

It happens when I followed the code from chapt 4 to chapt 5.

So, probably there is an error in the below code,

 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ C++
    bool hit_sphere(const vec3& center, float radius, const ray& r) {
        vec3 oc = r.origin() - center;
        float a = dot(r.direction(), r.direction());
        float b = 2.0 * dot(oc, r.direction());
        float c = dot(oc, oc) - radius*radius;
        float discriminant = b*b - 4*a*c;
        if (discriminant < 0) {
            return -1.0;
        }
        else {
            return (-b - sqrt(discriminant) ) / (2.0*a);
        }
    }

    vec3 color(const ray& r) {
        float t = hit_sphere(vec3(0,0,-1), 0.5, r);
        if (t > 0.0) {
            vec3 N = unit_vector(r.point_at_parameter(t) - vec3(0,0,-1));
            return 0.5*vec3(N.x()+1, N.y()+1, N.z()+1);
        }
        vec3 unit_direction = unit_vector(r.direction());
        t = 0.5*(unit_direction.y() + 1.0);
        return (1.0-t)*vec3(1.0, 1.0, 1.0) + t*vec3(0.5, 0.7, 1.0);
    }
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by hollasch** [comment]
Thank you for the heads up. Please report back when you determine what the issue is.

**Comment by trevordblack** [comment]
From visual inspection alone, it looks like hit_sphere should be returning
a `float`, the function declaration returns `bool`

**Comment by Joeycho** [comment]
@trevordblack Yes, you were right!

I fixed it just changing 'bool' to 'float' in hit_sphere function declaration part.

I would make a pull request to update it.

**Comment by trevordblack** [comment]
This problem should make v2.

It's simple, and a definite bug.

@Joeycho  already provided a pull request with #160

**Comment by hollasch** [comment]
Fixed.
