### ISSUE TITLE
[book 1] Listing12 may contain an error

### ISSUE THREAD

**Issue by coder-Zzx** [RayTracing/raytracing.github.io#1570]
in function `ray_color`, `t` is defined as the smaller root of the equation according to `hit_sphere`,    
``` c++
color ray_color(const ray& r) {
    auto t = hit_sphere(point3(0,0,-1), 0.5, r);
    if (t > 0.0) {
        vec3 N = unit_vector(r.at(t) - vec3(0,0,-1));
        return 0.5*color(N.x()+1, N.y()+1, N.z()+1);
    }
```
but if this root is negative, the subsequent codes wont render this pixel , this may be a bug

**Comment by dimitry-ishenko** [comment]
There is more code below in the function:

```c++
    ...
    vec3 unit_direction = unit_vector(r.direction());
    auto a = 0.5*(unit_direction.y() + 1.0);
    return (1.0-a)*color(1.0, 1.0, 1.0) + a*color(0.5, 0.7, 1.0);
}
```

So, if the root is negative, the function will render the background pixel.

**Comment by hollasch** [comment]
Yup, agreed with Dimitry. If the sphere is behind the ray origin, it's not a hit, so we render the background.
