### ISSUE TITLE
stratification missing green diff highlight on line

### ISSUE THREAD

**Issue by 9mm** [RayTracing/raytracing.github.io#1575]
I could have missed a previous step but i dont think so, here:

https://raytracing.github.io/books/RayTracingTheRestOfYourLife.html

This text ive highlighted with my mouse was new, yet its not highlighted green. it took me awhile to find why my scene was way overexposed:

<img width="769" alt="image" src="https://github.com/RayTracing/raytracing.github.io/assets/1386207/5ca00a79-4030-4ac1-acc0-0cc14acca05e">

**Comment by hollasch** [comment]
You don't mention what version you're talking about, but you do reference the latest release (v4.0.0-alpha.2). This change is highlighted in book 1, listing 45: https://raytracing.github.io/books/RayTracingInOneWeekend.html#listing_camera-spp.
