### ISSUE TITLE
3.6.1 - samples per pixel is wrong

### ISSUE THREAD

**Issue by 9mm** [RayTracing/raytracing.github.io#1576]
It's actually `1000` not `100` (presumably, based on the fact it says it takes 15 minutes, as well as the actual image is very close to when i set it to 1000)

<img width="781" alt="image" src="https://github.com/RayTracing/raytracing.github.io/assets/1386207/848fc05c-8bef-431e-bba3-744b77b43721">

**Comment by hollasch** [comment]
Looks like this one's been fixed in v4.0.0.
