### ISSUE TITLE
Book 2.3.9: Use a comparison class instead of one function per axis

### ISSUE THREAD

**Issue by bovarysme** [RayTracing/raytracing.github.io#1581]
As the issue title says, listing 18 could be replaced with something like:
```C++
class bvh_node : public hittable {
  ...
};

class box_compare {
  public:
    box_compare(int axis_index) : axis_index(axis_index) {}

    bool operator()(const shared_ptr<hittable> a, const shared_ptr<hittable> b) {
        auto a_axis_interval = a->bounding_box().axis_interval(axis_index);
        auto b_axis_interval = b->bounding_box().axis_interval(axis_index);
        return a_axis_interval.min < b_axis_interval.min;
    }

  private:
    int axis_index;
};
```

And listing 16 could be simplified to:
```C++
#include "rtweekend.h"

#include "aabb.h"
#include "hittable.h"
#include "hittable_list.h"

#include <algorithm>

class bvh_node : public hittable {
  public:
    ...

    bvh_node(std::vector<shared_ptr<hittable>>& objects, size_t start, size_t end) {
        size_t object_span = end - start;

        if (object_span == 1) {
            left = right = objects[start];
        } else if (object_span == 2) {
            left = objects[start];
            right = objects[start+1];
        } else {
            // Note: moved the definition of `axis` closer to its usage.
            int axis = random_int(0,2);

            std::sort(objects.begin() + start, objects.begin() + end, box_compare(axis));

            auto mid = start + object_span/2;
            left = make_shared<bvh_node>(objects, start, mid);
            right = make_shared<bvh_node>(objects, mid, end);
        }

        bbox = aabb(left->bounding_box(), right->bounding_box());
    }

    ...
};
```

Thanks for the books! I'm new to the field of computer graphics and I've been having a lot of fun :)

**Comment by PoneyUHC** [comment]
I'm currently working on this section of the book.
The idea a function per axis just to change a single value was tilting me a bit.
Your code is a solution, but I think introducing a new class makes it even more overkill.

If found a simple solution using a lambda :
```cpp
auto comparator = [axis_index](shared_ptr<IHittable> obj1, shared_ptr<IHittable> obj2){
    return BVHNode::CompareAABB(obj1, obj2, axis_index);
};

[...]

sort(objects.begin() + start, objects.begin() + end, comparator);
```

Which makes it all to a single function, being curryfied in some way thanks to the lambda.

**Comment by hollasch** [comment]
Both of these are good suggestions. Were I to write my own ray tracer from scratch, I'd probably do something similar.

However, both of these solutions introduce more support code, and both require a fluency with C++ that the average reader may not have (many readers have _no_ personal experience with C++). Our general code philosophy with these books is to keep the code as stupid as possible, leveraging modern idioms only where they are universally comprehensible and which simplify the code.

We've had to make this tradeoff in many places, and *strongly* encourage readers to use the example code as illustrative, writing their own implementations in the language and style they prefer, and exploring simple and obvious performance improvements as they go.

For this reason, I think we'll pass on these suggestions for the books, but strongly encourage you to use them in your own implementations.
