### ISSUE TITLE
Book 1: Highlighting missing due to mis-matched casing

### ISSUE THREAD

**Issue by whydoubt** [RayTracing/raytracing.github.io#1600]
I ran across a listing in the first book (41, in section 8.1, FWIW), where I expected highlighting, but it was missing.
In the source a string of tildes followed by "C++ Highlight" appears to mark a section as class "Highlight" (upper-case _h_).
However, the proper class is "highlight" (lower-case _h_), so "C++ highlight" would seem to be the correct annotation.
This only seems to be the case in the first book, and it contains 16 instances that should be changed.
I am fine creating the PR if desired.

**Comment by hollasch** [comment]
Very nice catch. I've sent you a contributor invite if you'd like to proceed with a PR. Please make changes to the `dev-patch` branch, and add your entry to `books\acknowledgments.md.html`. Thanks!

**Comment by whydoubt** [comment]
Should I add an entry to CHANGELOG.md as well?

**Comment by hollasch** [comment]
Sure, go ahead.
