### ISSUE TITLE
1.9.1: Interval does not match 'cube enclosing the unit sphere'.

### ISSUE THREAD

**Issue by whydoubt** [RayTracing/raytracing.github.io#1603]
In #1591, text was changed from 'unit cube' to 'cube enclosing the unit sphere' to correctly describe the cube.
At the same time, the range was changed to interval notation, and the values were changed (from -1 and +1 to 0 and 1).
While I like the use of interval notation here, the values are now incorrect.
x/y/z in the range `[-1,1]` is the actual range for a cube enclosing the unit sphere.
x/y/z in the range `[0,1]` is (ironically?) a unit cube.

**Comment by hollasch** [comment]
Yup, the range should be $[-1,+1]$. Let me know if you want to make the PR, or I can do it.

**Comment by whydoubt** [comment]
You can go ahead with this one, I'm away from my workstation for a bit.

**Comment by hollasch** [comment]
Will do; thanks.
