### ISSUE TITLE
3.9.3: refactoring `emitted` should remove the need for extra parameters

### ISSUE THREAD

**Issue by fee1-dead** [RayTracing/raytracing.github.io#1605]
As `hit_record` will contain information about uv and the point of hit, there's no need to pass those to the `emitted` function anymore.

**Comment by hollasch** [comment]
Nice catch; thanks!

**Comment by hollasch** [comment]
This goes back to book two. In addition, there's something funny in `material.h`, where we have a `class hit_record;` declaration, but following code accesses components of the `hit_record`. Thus it would seem that the definition is already in scope at that point (making the `class hit_record` forward declaration unnecessary. Seems like there's some more cleaning work to be done here.

**Comment by hollasch** [comment]
This uncovered an additional issue: #1608, which I'll fix first.
