### ISSUE TITLE
[Book 1] Chapter 6.1 Incorrect comparison for `t`

### ISSUE THREAD

**Issue by p0wp0wpanda** [RayTracing/raytracing.github.io#1643]
[Minor]

https://github.com/RayTracing/raytracing.github.io/blob/b6a33687100bf301c318a24a7333077529406a3d/books/RayTracingInOneWeekend.html#L977-L980

Book image
<img width="768" alt="image" src="https://github.com/user-attachments/assets/de941154-df4f-4090-8c41-c89214b91495">

My output
<img width="768" alt="image" src="https://github.com/user-attachments/assets/77a9b6c8-e6b3-4fa1-a4bb-08639dacab0d">

It should be `t > -1.0` instead

**Comment by whydoubt** [comment]
You should check for other differences between your code, and the code in the book (such as signs and variable order).  Any `t` less than 0 should represent a hit behind the 'camera'.

**Comment by hollasch** [comment]
@whydoubt is correct. For a given ray, $t=0$ yields the ray's origin point. $t > 0$ yields points along the ray, and $t < 0$ is true for points "behind" the ray. In your case, I'd revisit the projection ray and/or the coordinates of the sphere.
