### ISSUE TITLE
Book 1 Section 11.2 Formula Missing a Variable

### ISSUE THREAD

**Issue by ReneeeZhang** [RayTracing/raytracing.github.io#1644]
The highlighted formula in the following screenshot is missing a variable
<img width="987" alt="Screenshot 2024-10-05 at 2 25 12 PM" src="https://github.com/user-attachments/assets/26948798-45c9-4967-bc74-0b6339168d6b">
$$ \mathbf{R}'_\perp = \frac{\eta}{\eta'} \left( \mathbf{R} + \cos \theta \mathbf{n} \right)$$ is wrong.
It should be:
$$ \mathbf{R}'_\perp = \frac{\eta}{\eta'} \left( \mathbf{R} + |\mathbf{R}|\cos \theta \mathbf{n} \right) $$ 
Looks like:
<img width="309" alt="Screenshot 2024-10-05 at 2 34 25 PM" src="https://github.com/user-attachments/assets/d55018f2-7e85-4714-86b6-3c13b3ee7ded">

**Comment by hollasch** [comment]
Note that in our code, $\mathbf{R}$ is a unit vector.

**Comment by ReneeeZhang** [comment]
Thank you. I do notice that in the code $\mathbf{R}$ is a unit vector, but in the book, it does not explicitly say this assumption, which was a bit confusing when I tried to reason about the formula myself.

**Comment by hollasch** [comment]
Yeah, I noticed the same thing while going through the equations to verify. Your suggestion is a good one.
