### ISSUE TITLE
constant_medium::hit fails with concave boundary shapes

### ISSUE THREAD

**Issue by vilya** [RayTracing/raytracing.github.io#186]
The `constant_medium` class allows _any_ other shape to be used as the boundary of the medium, but its `hit` method will only work correctly when the boundary shape is convex. For non-convex shapes it can return a miss in cases where it should return a hit. Specifically, if extending the ray backwards would enter & exit the volume, then the current `hit` method will fail to find any places where extending the ray _forwards_ would enter the volume.

I don't think this breaks anything in the book because the book only seems to have convex shapes, but it might be worth adding a warning about it or something? It could catch people out if they add support for loading 3D models and try to use one as a volume, for example.

**Comment by hollasch** [comment]
Interesting catch — thanks! I wonder if there are other cases where non-convex shapes might be a problem. Sounds like a good appendix topic.

At a minimum, I agree that we should at least flag this and leave it as an exercise for the reader. Flagging this for the post-v2 release.

**Comment by hollasch** [comment]
Done.
