### ISSUE TITLE
Please add link to my CUDA implementation.

### ISSUE THREAD

**Issue by rogerallen** [RayTracing/raytracing.github.io#191]
I didn't see a way to edit the wiki page.  Hoping this is the right way to update it...

In the "Implementations in Other Languages" page in the "Ray Tracing in One Weekend" section, could you add a link to my CUDA language implementation? 

https://github.com/rogerallen/raytracinginoneweekendincuda

If possible, adding a link to the blog post describing it might also be useful: https://devblogs.nvidia.com/accelerated-ray-tracing-cuda/

Thanks!

**Comment by hollasch** [comment]
Wiki editing was restricted to those with push access only. I've relaxed the restriction to allow for public editing; I suspect that will be fine. However, logging an issue was a great workaround — thank you for being persistent.

In the meantime, I've added an entry for your implementation, plus a link to the blog post.

Thank you!
