### ISSUE TITLE
MAXFLOAT should be rewritten as Infinity

### ISSUE THREAD

**Issue by trevordblack** [RayTracing/raytracing.github.io#195]
MAXFLOAT represents the largest possible floating point (32 or 64 bit) number.
This will almost never present a problem in practice, but the correct formulation here is with floating point infinity.

**Comment by hollasch** [comment]
Agreed.

**Comment by ronaldfw** [comment]
Fixed on `future` branch. Will keep this issue open until this is merged with `master`.

**Comment by hollasch** [comment]
Merged into the development branch.
