### ISSUE TITLE
Update CHANGELOG.md for web release v2.0.0

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#20]
This should capture all of the changes we've made since they first appeared on GitHub under Pete's GitHub user account.

- [x] In One Weekend
- [x] The Next Week
- [x] The Rest Of Your Life

We should investigate some form of semver grouping. Like
1. Fixes (patch level)
2. New Content (minor changes)
3. Replaced/Deleted Content (major changes)

So level 1 would mean that you could just grab the latest and rest assured that the new book is better in every way. No need to review anything.

Level 2 means that you'll get additional new things, and you might want to visit those topics specifically to see the new stuff.

Level 3 means that big changes were made, and you should review them to see if you need to update your personal code. This may also correct misunderstanding that you had before.

Here's an example of what I'm talking about: https://github.com/hollasch/timeprint/blob/master/CHANGELOG.md

**Comment by hollasch** [comment]
Resurrecting — I shouldn't have closed this. We now have a CHANGELOG.md in the root of the unified repo, but will need to add all changes for the web release (v2.0.0).

**Comment by trevordblack** [comment]
The branch `all/changelog` contains the bones of a changelog.

Any one person does not have the memory or wherewithall to perfectly recount all of the changes made.

**Comment by trevordblack** [comment]
Please add changes made as you remember, dig them up
