### ISSUE TITLE
M_PI does not exist for MSVC

### ISSUE THREAD

**Issue by trevordblack** [RayTracing/raytracing.github.io#207]
MSVC throws errors looking for M_PI

**Comment by trevordblack** [comment]
https://stackoverflow.com/questions/6563810/m-pi-works-with-math-h-but-not-with-cmath-in-visual-studio

**Comment by hollasch** [comment]
My vote is to keep it simple. In our constants file (which I think Ronald is working on), we should just use
```
const <floatType> pi = 3.1415926535897932385;
```

**Comment by ronaldfw** [comment]
Fixed on the `future` branch.

**Comment by hollasch** [comment]
This should go in to v3 (the `development` branch).

**Comment by hollasch** [comment]
Done and now in the development branch.
