### ISSUE TITLE
Standardize line lengths between books and source

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#219]
Code lines in the books are restricted in order to avoid requiring the reader to horizontally scroll to see all of the code. This means that some lines wrap differently between the source and books, which is unfortunate when trying to compare them.

Revisit the book line lengths for source code, adjusting with CSS or other means. Then reformat the source code to the same line length.

**Comment by hollasch** [comment]
100 characters would be nice. I could accomplish this in Brave (≅ Chrome), by reducing the code font size from 86% to 84%, and the letter spacing (tracking) by -0.20px. _However_, this isn't enough in Firefox, which is pretty discouraging. In addition, when saving as PDF from the browser in Brave/Chrome, you need to set margins to minimum.

It's looking like 86 characters per line may be the best compromise across viewers. Still need to test on Edge/IE and Safari.

**Comment by trevordblack** [comment]
Is this a Markdeep thing? Cause we could easily reach out to McGuire to see
if it's something he has a good understanding of, or is willing to tweak

**Comment by hollasch** [comment]
Markdeep is just a JavaScript payload that transforms the Markdown source to standard HTML. Since the end result is HTML, you can style it with regular old CSS, which is what the above does. I do chat with Morgan these days about Markdeep, but there's nothing that can be done at that level that HTML+CSS can't do.

The challenges above are just regular wrestling with a result rendered across a variety of browsers and configurations. I'm going to cobble up some test cases for us all to try out just to get a good sense of coverage. However, there won't be a one-size-fits-all solution waiting for us. Our best hope is to get a solution that works for most.

**Comment by hollasch** [comment]
Resolved in development branch, PR #247
