### ISSUE TITLE
Images: Book 3 Chapter 8 onwards: Need to update Cornell box screenshots

### ISSUE THREAD

**Issue by jammm** [RayTracing/raytracing.github.io#225]
Since the bug in `random_cosine_direction` was fixed, the screenshots from figure 8-1 are outdated. https://github.com/RayTracing/TheRestOfYourLife/pull/8

**Comment by hollasch** [comment]
Also note that the initial Cornell box render is incorrect, since the back sides of the unrotated faces should not be hit.

**Comment by hollasch** [comment]
Covered individually:

  - #591
  - #592
  - #593
  - #594
  - #595
  - #596
  - #597
  - #598
  - #599
  - #600
