### ISSUE TITLE
Need to consolidate Next Ideas

### ISSUE THREAD

**Issue by trevordblack** [RayTracing/raytracing.github.io#256]
There are a list of next steps and things to do at the end of InOneWeekend and at the end of TheRestOfYourLife.

There are also ideas in the in1weekend blogspot.

There is digital rot over at the blogspot, and many of the next steps at the end of InOneWeekend are implemented in TheNextWeek.

I think this area of the books could use some polish.

**Comment by hollasch** [comment]
Definitely something to revisit. In particular, is there a role for the associated GitHub wiki for this project? I could imagine that creating a new wiki page is the lightest weight extension, and could be as trivial as “see this cool book for approaches to denoising approaches”. That wiki page could grow into a new chapter.

The progression in effort might look like:

1. Wiki page
2. Appendix
3. Chapter
4. Book

I'd like to see us greasing the skids for efforts like this. Balance project growth (with simple guidelines) against uncoordinated complexity.

**Comment by trevordblack** [comment]
I'm closing out this issue as complete.

If anyone has ideas for changes to make, they can either place them in the wiki, or create a new issue.
