### ISSUE TITLE
Restructure acknowledgements

### ISSUE THREAD

**Issue by trevordblack** [RayTracing/raytracing.github.io#262]
There are 4 different pools of acknowledgements.

This could use some polish.

**Comment by trevordblack** [comment]
Specifically,
1. End chapter of InOneWeekend
2. Subchapter of TheNextWeek
3. Subchapter of TheRestOfYourLife
4. Credits on raytracing.github.io

**Comment by hollasch** [comment]
Ah! Didn't catch that. I think that we should leverage the website for all credits, and perhaps have the books include a one-sentence blurb and a link, perhaps.

**Comment by hollasch** [comment]
Done.
