### ISSUE TITLE
Subchapters in Book Series

### ISSUE THREAD

**Issue by trevordblack** [RayTracing/raytracing.github.io#267]
In Markdeep the option exists to partition chapters into subchapters.

At present, there are only three instances of subchapters in the series:

- TheNextWeek - Chapter 1.1 Acknowledgements
- TheRestOfYourLife - Chapter 1.1 Acknowledgements
- (With progress indicator) InOneWeekend - Chapter 2.1 Adding a Progress Indicator

The books already have natural places for subchapter ending and starting.

However, this would be a **very** significant change.

Broadly, there are four possibilities:
1. Leave things as they are, with 3 subchapters
2. Remove all subchapters
3. Use more subchapters
4. Subchapter everything

My personal preferences are 2 and 4.

**Comment by hollasch** [comment]
I'd go with a weak 3. Subchapters are a tool, and shouldn't be used where it doesn't make sense. There may be good opportunities to break chapters down a bit, so a book pass is warranted.

**Comment by hollasch** [comment]
Done in PR #427
