### ISSUE TITLE
Floats in TheRestOfYourLife

### ISSUE THREAD

**Issue by trevordblack** [RayTracing/raytracing.github.io#275]
There are `float`s in  src/TheRestOfYourLife/bucamera.h

**Comment by trevordblack** [comment]
There are `float`s in Chapter 2: A Simple Monte Carlo Program. This is very problematic because this chapter is used to illustrate Monte Carlo convergence on PI

**Comment by hollasch** [comment]
`bucamera.h` is vestigial (back-up camera.h?). I'm removing it. (It also has a compile-breaking typo that I introduced :).

**Comment by hollasch** [comment]
Fixed in development.
