### ISSUE TITLE
Image: Lambertian updates Chapter 10 RestOfYourLife

### ISSUE THREAD

**Issue by trevordblack** [RayTracing/raytracing.github.io#286]
> We’ve basically gotten this same picture (with different levels of noise) with several different
sampling patterns. It looks like the original picture was slightly wrong! Note by “wrong” here I
mean not a correct Lambertian picture. But Lambertian is just an ideal approximation to matte, so
our original picture was some other accidental approximation to matte. I don’t think the new one is
any better, but we can at least compare it more easily with other Lambertian renderers.

We don't yet know if this will be the case after the new lambertian is propagated through the codebase.

**Comment by hollasch** [comment]
Covered individually now:

  - #589
  - #590
  - #591
  - #592
  - #593
  - #594
  - #595
  - #596
  - #597
  - #598
  - #599
  - #600
