### ISSUE TITLE
Update CHANGELOG for v3 release

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#303]

**Comment by trevordblack** [comment]
I think `diff`ing through every commit might be infeasible. So, as a first pass, going through the issues might be the most economical means of filling this out.
I'm looking at a jammed week. So I'll try to get a first pass out tomorrow or Monday

**Comment by hollasch** [comment]
Oh, sorry! I’m working through this right now. No need to work on it.

**Comment by hollasch** [comment]
Updated to 2020-03-22

**Comment by hollasch** [comment]
Completed.
