### ISSUE TITLE
There is a wrong discriminant formula

### ISSUE THREAD

**Issue by spinningwatt** [RayTracing/raytracing.github.io#315]
The formula in sphere.h in chapter 6 of Ray Tracing in One Weekend may be wrong.

```c++

    float discriminant = b*b - a*c;    // should this be -2.0*a*c ?
    if (discriminant > 0) {
        float temp = (-b - sqrt(discriminant))/a;    // should this be /(2.0*a) ?
```

If the code is totally right, I wonder why we rewrite formula like this, any trick?
Thanks

**Comment by trevordblack** [comment]
For the quadratic formula
```
(-b +- sqrt(b^2 - 4ac))/2a
```

Can be rewritten as
```
b = 2h
(-h +- sqrt(h^2 -ac)/a
```

Where in your question, the `b` is actually the `h` variable.
This is a bug, and has already been fixed in the `development` branch.

**Comment by spinningwatt** [comment]
I get it. Sorry for my carelessness. 
I should have noticed that the the previous code assigned the half value of b to the "b", which is your h.
Thanks for your reply
