### ISSUE TITLE
Unused line of code, "The Next Week" main.cc

### ISSUE THREAD

**Issue by cgyurgyik** [RayTracing/raytracing.github.io#317]
In the main.cc file,
You have:
```
camera cam(lookfrom, lookat, vec3(0,1,0), vfov, float(nx)/float(ny), aperture, dist_to_focus, 0.0, 1.0);

    for (int j = ny-1; j >= 0; j--) {
        for (int i = 0; i < nx; i++) {
            vec3 col(0, 0, 0);
            for (int s=0; s < ns; s++) {
                float u = float(i+random_double())/ float(nx);
                float v = float(j+random_double())/ float(ny);
                ray r = cam.get_ray(u, v);
                vec3 p = r.point_at_parameter(2.0);
                col += color(r, world,0);
            }
            col /= float(ns);
            col = vec3( sqrt(col[0]), sqrt(col[1]), sqrt(col[2]) );
            int ir = int(255.99*col[0]); 
            int ig = int(255.99*col[1]); 
            int ib = int(255.99*col[2]); 
            std::cout << ir << " " << ig << " " << ib << "\n";
        }
    }
}
```
Is ```                vec3 p = r.point_at_parameter(2.0);``` necessary for anything?

**Comment by trevordblack** [comment]
It's a hold over from an old revision of the source. It is a bug.

It should be fixed in the `development` branch.

For any issues you find, check against the `development` branch.

**Comment by hollasch** [comment]
Ugh. Another fix that didn't make it to all locations. It's in code for TheNextWeek, and in books 1 & 2.

**Comment by trevordblack** [comment]
I can only find it in `books/RayTracingTheRestOfYourLife.html:2142`

where else did you find it?

**Comment by cgyurgyik** [comment]
books/InOneWeekend.html:794

**Comment by trevordblack** [comment]
The `master` branch is from the long long old way back time of September.

Check any issues against the `development` branch. Which is a good 200+ commits ahead of `master`

`vec3 p = r. ...`
shows up in the `master` branch at `books/InOneWeekend.html:794` , but not in the `development` branch.

This still needs to be removed from `books/RayTracingTheRestOfYourLife.html:2142` in the `development` branch.
But, I can't find it anywhere else in that branch.

Was it somewhere else in the `development` branch?

**Comment by hollasch** [comment]
Gah! I submitted the fix in 66d3d4, but apparently didn't close this issue. Which is fine, because I'd missed the one in _The Rest Of Your Life_.

**Comment by hollasch** [comment]
Done.
