### ISSUE TITLE
[Typo] "The Rest Of Your Life", Chapter 8. Orthnormal Bases

### ISSUE THREAD

**Issue by cgyurgyik** [RayTracing/raytracing.github.io#318]
Once we have an ONB and we have a 𝑟𝑎𝑛𝑑𝑜𝑚(𝑥,𝑦,𝑧) **relative the the** Z-axis we can get the vector relative to 𝑛⃗  as:

**Comment by hollasch** [comment]
Thanks; this has been fixed in the `development` branch.
