### ISSUE TITLE
Ray Tracing: The Next Weekend. Chapter 5, Perlin Noise

### ISSUE THREAD

**Issue by cgyurgyik** [RayTracing/raytracing.github.io#320]
```
static vec3* perlin_generate() {
    float * p = new float[256];
    for (int i = 0; i < 256; ++i)
        p[i] = random_double();
    return p;
}
```
```p``` is a float array, yet the function returns a ```vec3```. Is this a bug?

**Comment by trevordblack** [comment]
There is a disagreement between src and books

it looks like the book should be corrected to

**Comment by trevordblack** [comment]
Scratch that.

The original issue raised was already fixed in a previous commit.
My comment was incorrect.

The book is fine as-is because it is motivating the vec3 perlin_generate.

No issue is present.
Closing this issue.
