### ISSUE TITLE
Output an Image ppm example wrong code

### ISSUE THREAD

**Issue by CGMossa** [RayTracing/raytracing.github.io#321]
I've translated the C++ code in 2. Output an Image, and discovered that the code here does not yield the output shown in the book.

Here's the [play.rust-lang.org](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=35362068bb4fca729a296e0fda6bc75f) link. The output is
```
P3
200 100
255
0 253 51
1 253 51
2 253 51
3 253 51
5 253 51
6 253 51
7 253 51
8 253 51
10 253 51
```
Of the C++ code and the Rust code.
The image also does not look like what is in the book. Here is my output:
![image](https://user-images.githubusercontent.com/1063624/72013938-345ccb80-325f-11ea-90fa-459705989288.png)

**Comment by trevordblack** [comment]
1. I copied the output of your play.rust-lang.org into a text file, removed the headers.
  I got the correct image in my ppm viewer.
  Maybe you're using a bad ppm viewer?

2. 
```
// 6 253 51
// 7 253 51
// 8 253 51
// 10 253 51 #problematic!
// 11 253 51
```
Good catch. Not a lot of people would have caught that.
I think it's just a mistake in copying over.
There are still exactly 200 * 100 pixels in the array, so it works without the 9 253 51

We can remove the error. New one will look like
```
P3
200 100
255
0 253 51
1 253 51
2 253 51
3 253 51
5 253 51
6 253 51
7 253 51
8 253 51
```

**Comment by CGMossa** [comment]
Thanks for the quick reply.
There are a lot more rows missing. The excerpt from the text is

```
P3
200 100
255
0 253 51
1 253 51
2 253 51
3 253 51
4 253 51
5 253 51
6 253 51
7 253 51
8 253 51
9 253 51
10 253 51
11 253 51
12 253 51
13 253 51
14 253 51
15 253 51
``` 

Missing rows: 4, 9, 13, and presumably 19 and onwards. 
I used `OpenSeeIt` to view the `.ppm` file.

I still think there's an issue somewhere, but I cannot put my finger on it.

**Comment by hollasch** [comment]
Still not seeing the issue. For this:
```
// 6 253 51
// 7 253 51
// 8 253 51
// 10 253 51 #problematic!
// 11 253 51
```
What's problematic? There should be 56 values missing in red [0..255] in order to get 200 columns, and 156 values missing in blue [255..0] in order to get 100 columns.

Attached is the output image I get, which matches what's shown in the book.

[image.ppm.txt](https://github.com/RayTracing/raytracing.github.io/files/4044547/image.ppm.txt)

**Comment by hollasch** [comment]
@CGMossa — if you view the example I attached above, does it look correct? If not, it would appear that your PPM viewer may have problems. If it _does_ look correct, then that may help you understand where your code is having problems.

**Comment by hollasch** [comment]
After re-checking the code and generated image, I believe everything looks fine. @trevordblack had a similar experience.

**Comment by CGMossa** [comment]
Yes, thank you for being thorough.
