### ISSUE TITLE
Images: Update renderings for The Next Week

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#325]
Currently, there are 10 different scenes coded in `theNextWeek`. We ensure that each result is included in the book for reference. This will be much easier with the new `scene` or `renderer` class.

**Comment by IceTDrinker** [comment]
Hello,

I will be starting the Next Week in the near future I could document and save images as I go.

I'm rendering at 1920x1080 and saving the results to pngs.

Let me know how I should proceed.

Cheers

**Comment by hollasch** [comment]
Thanks @IceTDrinker ! See issue #179 for discussion around the new formats we're targeting. Currently @trevordblack was going to tackle the book 2 images, but he might well appreciate the assist. Thoughts Trevor?

**Comment by hollasch** [comment]
Oh, there's also some brokenness with the current camera code that will need to be fixed first. See #527, currently in progress.

**Comment by trevordblack** [comment]
Did we settle on a resolution for book 2?
PNGs are a must.
The sample count and resolution should depend on the code up to that point.

**Comment by hollasch** [comment]
Yes, image specs are in #179. The target book resolution is 384×216, PNG format.

**Comment by hollasch** [comment]
Update: image specs are now 400×225. Large images may be JPEG, but very high quality.

**Comment by hollasch** [comment]
We should also true up the nomenclature with the final code, which uses a switch statement with 10 different scene numbers.

**Comment by hollasch** [comment]
All tasks have been broken up into their own issues at this point. Closing this more general issue.
