### ISSUE TITLE
Need to add drawing for sphere directions

### ISSUE THREAD

**Issue by trevordblack** [RayTracing/raytracing.github.io#326]
Missing white board picture for possible sphere normal directions, see
`InOneWeekend.html:794`

**Comment by hollasch** [comment]
Hmmmm, that's a blank line in the middle of a code block at the current tip of the development branch. What's the surrounding text?

**Comment by trevordblack** [comment]
`![Figure [normal-directions]: Possible directions for sphere surface-normal geometry](../images/fig.normal-possibilities.jpg)`

I realized that 794 is in my current branch

**Comment by hollasch** [comment]
@trevordblack — can you sketch out a picture of what you're thinking of?

**Comment by hollasch** [comment]
A picture of a paper sketch would be fine.

**Comment by trevordblack** [comment]
![IMG_20200122_145701](https://user-images.githubusercontent.com/10197672/72942138-93bedf00-3d27-11ea-97d6-cb4a4cdb19a7.jpg)


The plane should be a saturated cyan/real.
The point of intersection a deep red.
The ray_in black
The normals a bright green
The normal arrows are colored green

**Comment by trevordblack** [comment]
_Shoulda gone to art school_

**Comment by petershirley** [comment]
Figure fig.normal-possibilities.jpg checked into branch v3newfigures 
![image](https://user-images.githubusercontent.com/2800266/77267400-13095a00-6c68-11ea-9d80-e88262aac0fd.png)

**Comment by hollasch** [comment]
Fixed in #409
