### ISSUE TITLE
flip_face → flip_surface?

### ISSUE THREAD

**Issue by trevordblack** [RayTracing/raytracing.github.io#327]
You could do `flip_surface`. ¯\_(ツ)_/¯

Consider replacing `flip_face` with something else:
`flip_faces`
`flip_surface`

_Originally posted by @hollasch in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MzM4Mzg0OTg2/pull_request_reviews/more_threads_

**Comment by hollasch** [comment]
Ooooh. “evert”: https://dictionary.cambridge.org/dictionary/english/evert

**Comment by hollasch** [comment]
Still, after thinking about this, the name is ok as-is. Closing.
