### ISSUE TITLE
Trevor's Refactoring Pass (book 1)

### ISSUE THREAD

**Issue by trevordblack** [RayTracing/raytracing.github.io#333]
Trevor needs to do another refactor pass.

**Comment by trevordblack** [comment]
I'm going to throw issues in here as I come upon them.

**Comment by trevordblack** [comment]
InOneWeekend.html:369

    [Listing [ppm-2]: <kbd>[main.cc]</kbd> Final code for the first PPM image
->
    [Listing [ppm-2]: <kbd>[main.cc]</kbd> Final code for the first PPM image]

**Comment by trevordblack** [comment]
InOneWeekend.html:994

`We add a list of objects:`
->

```
We have a generic object called a `hittable` that the ray can intersect with.
We need to add an object that collects `hittable`s so that we can check for multiple intersections.
We create a class that stores a list of objects
```

not perfect, but flesh this out a bit more.

**Comment by trevordblack** [comment]
InOneWeekend.html:876

if the ray and the normal
face in the opposide direction, then the ray is outside the object.

opposite....

**Comment by trevordblack** [comment]
InOneWeekend.html:2324

  $$ \frac{1.5}{1.0} \cdot \sin\theta > 1.0 $$,

remove trailing ,

**Comment by trevordblack** [comment]
TheNextWeek.html:290-331

Seems highlighting for changed parts of the scene

**Comment by trevordblack** [comment]
TheNextWeek.html:815

2. sort the primitives using library qsort

we use `std::sort` now

**Comment by trevordblack** [comment]
TheNextWeek.html:1588-1595

replace `fabs` with whatever we typically use locally, `ffabs`? Make sure correct library is `include`d somewhere

**Comment by trevordblack** [comment]
3. By convention, each of the red/green/blue components range from 0.0 to 1.0. We will relax that later when we internally use high dynamic range, but before output we will tone map to the zero to one range, so this code won’t change.

4. Red goes from black to fully on from left to right, and green goes from black at the bottom to fully on at the top. Red and green together make yellow so we should expect the upper right corner to be yellow.


Both need rewrites

3 -> need to explain 0.0 to 1.0 and 0 to 255
4 -> "red goes from black to fully on" -> "red goes from fully off (black) to fully on (bright red)". same with green

**Comment by trevordblack** [comment]
Can't believe I hadn't caught this before. Why did we go with `point3` rather than just `point`?
@hollasch

**Comment by trevordblack** [comment]
InOneWeekend: Listing 4, has highlighting on `vec3`

**Comment by trevordblack** [comment]
InOneWeekend: 389

Let’s think of a ray as a function $\mathbf{p}(t) = \mathbf{a} + t \vec{\mathbf{b}}$.

Consider putting ray equation in `$$`

**Comment by trevordblack** [comment]
InOneWeekend:392 $p(t)$

needs to be `\mathbf{b}}`

**Comment by trevordblack** [comment]
InOneWeekend: 394

"and this is what is often called a half-line or ray."

consider

and this is what is often called a half-line or a ray. This is where the _ray_ in _ray tracing_ comes from.

**Comment by trevordblack** [comment]
InOneWeekend: 401

$p(t)$ to bold

**Comment by trevordblack** [comment]
InOneWeekend: 545

" formulas to be in terms of vectors so all the x/y/z stuff"

x/y/z needs formatting. Either `x`/`y`/`z` or `$x$/$y$/$z$`

**Comment by trevordblack** [comment]
InOneWeekend: 563

to know if our ray $p(t)

p(t) needs bold

**Comment by trevordblack** [comment]
InOneWeekend: 562-570

lots of P(t) need bolding

**Comment by trevordblack** [comment]
InOneWeekend:576-577

"The rules of vector algebra are all that we would want here, and if we expand that equation and
move all the terms to the left hand side we get:"

consider adding an intermediate step of distributing the dot product

**Comment by trevordblack** [comment]
InOneWeekend:767

"Now, how about several spheres? While it is tempting to have an array of spheres, a very clean
solution is the make an “abstract class”

is to make

**Comment by trevordblack** [comment]
InOneWeekend listing 18 has sphere class highlighted

**Comment by trevordblack** [comment]
InOneWeekend: 1110-1115

"We need some math constants that we conveniently define in their own header file. For now we only
need infinity, but we will also throw our own definition of pi in there, which we will need later.
There is no standard portable definition of pi, so we just define our own constant for it. We'll
throw common useful constants and future utility functions in `rtweekend.h`, our general main header
file."

consider changing pi to `pi` or $pi$

**Comment by trevordblack** [comment]
InOneWeekend: 1176-1178

`auto t = 0.5*(unit_direction.y() + 1.0)` should not be highlighted

**Comment by trevordblack** [comment]
InOneWeekend: 1250

"that returns a canonical random number which by convention returns random real in the range"

returns a random real

**Comment by trevordblack** [comment]
Potential Gotcha:

```c++
#include <cstdlib>
...

inline double random_double() {
    // Returns a random real in [0,1).
    return rand() / (RAND_MAX + 1.0);
}

inline double random_double(double min, double max) {
    // Returns a random real in [min,max).
    return min + (max-min)*random_double();
}
```

if we rewrite random_double using floats, it _can_ return 1.0 due to round-off error

**Comment by trevordblack** [comment]
InOneWeekend:1292

[file] -> Literally anything.

**Comment by trevordblack** [comment]
InOneWeekend:1276-1293

```
<div class='together'>
C++ did not traditionally have a standard random number generator, but newer versions of C++ have
addressed this issue with the `<random>` header (if imperfectly according to some experts).
If you want to use this, you can obtain a random number with the conditions we need as follows:

    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ C++
    #include <functional>
    #include <random>

    inline double random_double() {
        static std::uniform_real_distribution<double> distribution(0.0, 1.0);
        static std::mt19937 generator;
        static std::function<double()> rand_generator =
            std::bind(distribution, generator);
        return rand_generator();
    }
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    [Listing [random-double-alt]: <kbd>[file]</kbd> random_double(), alternate implemenation]
</div>
```

I would honestly rather just write up a simple Xor128 and show that off instead

**Comment by trevordblack** [comment]
InOneWeekend: 1431-1433

"One question is whether we can mix and match shapes and
materials (so we assign a sphere a material) or if it’s put together so the geometry and material are tightly bound"

->

One question is whether the geometry and material are tightly bound or if we can mix and match the two (we could assign a sphere a material)

**Comment by trevordblack** [comment]
InOneWeekend: listing 30

class vec3 is highlighted

**Comment by trevordblack** [comment]
InOneWeekend: 1534-1545

Highlighting needs to be reduced to only 1538-1540

**Comment by trevordblack** [comment]
InOneWeekend:1664-1665
"The distribution present scales by the"

->

This distribution scales by

**Comment by trevordblack** [comment]
vec3.h, material.h need include guards :(((((((

**Comment by trevordblack** [comment]
InOneWeekend:2335

  $$ \frac{1.5}{1.0} \cdot \sin\theta > 1.0 $$,

remove trailing ,

**Comment by trevordblack** [comment]
InOneWeekend: 2452-2453

"There is a big ugly equation for that, but almost everybody uses a simple and surprisingly simple polynomial approximation by Christophe Schlick:"

duplicate simple, use different word

**Comment by trevordblack** [comment]
InOneWeekend: 2633

a complete orthonormal basis (u,v,w) 

$(u,v,w)$

**Comment by trevordblack** [comment]
InOneWeekend: 2637-2640

"Remember that `vup`, `v`, and `w` are all in the same plane. Note that, like before when our fixed
camera faced -Z, our arbitrary view camera faces -w. And keep in mind that we can -- but we don’t
have to -- use world up (0,1,0) to specify vup. This is convenient and will naturally keep your
camera horizontally level until you decide to experiment with crazy camera angles."


Make syntax consistent

**Comment by trevordblack** [comment]
InOneWeekend:2704

"And we can change field of view to get:"

Should explicitly give code change (i think is 20 degrees...?)

**Comment by trevordblack** [comment]
Should this issue be closed out?
It feels like we got all of these either in a merge, or in separate issues.

**Comment by hollasch** [comment]
No idea; this is your baby.
