### ISSUE TITLE
Performance regression, all projects

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#336]
In performance testing, we've increased runtimes 50% across all three projects.

**Comment by hollasch** [comment]
The slowdown occurs in the conversion to using `std::shared_ptr` away from bare arrays.

inOneWeekend: commit 391e3ce
theNextWeek: commit 1db47f9
theRestOfYourLife: commit 55e764a

To address this item (if we choose), we need to adopt a scheme where we can reliably free all allocations after a frame, and at the end of the program. For now, these are the same point in time, so a simple solution is possible.

One approach would be to establish a registry of geometries (`hittable`) and materials, with the ability to free all in a single call. With this, you just need to ensure that shared objects are properly handled.

Another approach is to revisit all uses of shared pointers. In well-defined contexts, a local bare pointer may be used, in order to amortize the cost of refcount management.

**Comment by Rastaban** [comment]
In most cases there should be a single owner to the objects (the object that takes the smart pointer in its constructor), which means they should be switched to std::unique_ptr.  If the pointer is passed to other functions it should pass the raw pointer (unless the called function needs to extend the life of the object, then std::shared_ptr is appropriate).  Making that change would probably address the performance regressions and still correctly cleanup the objects.

I would be happy to take a shot at this if you are okay with this direction.

**Comment by hollasch** [comment]
Moving to a single owner means that we'd lose the ability to multi-instance geometry attributes. If you had a scene with 100 earth textures, you'd have 100 copies of the earth bitmap. The current code allows for material sharing across any number of objects, without having to think about lifetime.

If we moved to a `std::unique_ptr<>` for lifetime management only, but supporting shared use for multiple instances, we'd need to adopt a factory facade for every allocated geometry and material, considerably adding to our API footprint and requiring changes throughout our code.

Finally, the current code can easily be extended for generating animations with support for geometries and materials that live for a single frame, multiple frames, or all frames.

**Comment by Rastaban** [comment]
That makes sense, I didn't realize you were using multi-instance geometry attributes.

**Comment by Rastaban** [comment]
When I actually started digging into it the solution ended up being much more simple than I thought.  There are a few places we iterate over a vector of `shared_ptr `without using a reference.  This causes each iteration to make an expensive copy of the `shared_ptr`.  Switching to `const auto&` cut the runtime of InOneWeekend in half.  I will create a pull request.

**Comment by hollasch** [comment]
GAAAAAAAAAAAAAAH!

**Comment by hollasch** [comment]
Fix in PR #394 verified. Sweet!
