### ISSUE TITLE
Unnecessary calculation in lambertian::scatter()

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#340]
The `lambertian::scatter()` method (`material.h`) adds and then immediately subtracts the hit point:

    vec3 target = rec.p + rec.normal + random_unit_vector();
    scattered = ray(rec.p, target-rec.p, r_in.time());

**Comment by trevordblack** [comment]
One peculiarity of our implementation is that our codebase does not differentiate between geometric points and geometric vectors, referring to both as `vec3`. This was a design decision made out of simplicity, but there are places where this simplicity leads to inefficiency.

Rays are generally constructed as:
`ray(position orig, vector direction, float time)`

But our simplicity causes:
`ray(vec3 orig, vec3 direction, float time)`

With geometric vectors and points represented separately, the code in issue would become:
```
point target = rec.p + rec.normal + random_unit_vector();
ray scattered = ray(rec.p, target-rec.p, r_in.time();
```
Which looks like
```
point = point + vector + vector
ray = ray(point, point - point, float)
```
But ray takes `ray(point, vector, float)`, so we can simplify:
```
vector = vector + vector
ray = ray(point, vector, float)
```
This would look like:
```
vec3 target = rec.normal + random_unit_vector();
scattered = ray(rec.p, target, r_in.time());
```
There's a gotcha, though.
The variable name `target` implies that the instance is a geometric point, when we are changing it to a vector. The variable name should be changed to something that implies a vector, e.g. `direction`:
```
vec3 direction = rec.normal + random_unit_vector();
scattered = ray(rec.p, direction, r_in.time());
```

**Comment by hollasch** [comment]
You pretty much transcribed everything in my head. :)

**Comment by hollasch** [comment]
Done.
