### ISSUE TITLE
Week 2 random scene

### ISSUE THREAD

**Issue by dafhi** [RayTracing/raytracing.github.io#343]
'checker' as lambertian parameter is completely new.  copying "random scene" into github Week Two src also yields no dice.

**Comment by hollasch** [comment]
I don't understand the issue here. What do you mean by "completely new"? Which project has the issue? File name & line number? Are you talking about the master branch or the development branch?

**Comment by dafhi** [comment]
coming from book one, I expect to see like:
vec3(.9, .7, .5) instead of checker

**Comment by hollasch** [comment]
Where? Which branch?

**Comment by dafhi** [comment]
master

**Comment by hollasch** [comment]
Are you talking about book 2? Text? The chapter on motion blur? The code block following "If we take the example…"?

**Comment by dafhi** [comment]
yes

**Comment by hollasch** [comment]
Ok, I see the issue.

In _The Next Week_, chapter "Motion Blur", the code block following "The code below takes the example diffuse…" contains the following line:

```
hittable_list random_scene() {
    hittable_list world;

    world.add(make_shared<sphere>(vec3(0,-1000,0), 1000, make_shared<lambertian>(checker)));
    ...
```

At this point in the text, checker has not been defined and the `lambertian` constructor presented in the immediately preceding code block takes a `vec3` parameter. Several lines later, it also contains this line:

```
make_shared<lambertian>(make_shared<constant_texture>(albedo))
```

There's a third line lower down in the function that constructs `lambertian` with a vector.

These should likely be changed to reflect the values used in the `random_scene` function defined at the end of _In One Weekend_.

Vet changes against the text in the "Solid Textures" chapter and beyond.

**Comment by trevordblack** [comment]
You're talking about the `dev` branch Steve. dafhi is talking about the `master`.

Apparently the issue exists in both. I could have sworn that we had already fixed this bug in `dev`

**Comment by trevordblack** [comment]
@dafhi 
Were you able to get it working in `master` by replacing `checker` with `vec3(0.9,0.7,0.5)`?

**Comment by dafhi** [comment]
sec

**Comment by dafhi** [comment]
actually,
``
    hittable *world = random_scene();
    //hittable *world = two_spheres();
    //hittable *world = two_perlin_spheres();
    //hittable *world = earth();
    //hittable *world = simple_light();
    //hittable *world = cornell_box();
    //hittable *world = cornell_balls();
    //hittable *world = cornell_smoke();
    //hittable *world = cornell_final();
    //hittable *world = final();
``
comes out black.  assuming this is master.  i'll re-download master and try again

**Comment by dafhi** [comment]
having problems with SDL2 .. how i view output .. i'll get back once i sort this out

**Comment by dafhi** [comment]
cornell_balls is one of a few that don't come out black.  going through them all

**Comment by dafhi** [comment]
FYI: Dev C++ and Mingw 8.2 here..
earth and final crash (assuming .jpg)
scenes that work correctly
all cornells

i'll see if i can gather more in formation

**Comment by trevordblack** [comment]
The reason the scenes other than Cornell are black is because there's no light.

Set the sky to blue.
We fixed this in dev, but it's still a problem in master

**Comment by dafhi** [comment]
ok thanks.  i'll try the book example with replaced vec3(,,)

**Comment by dafhi** [comment]
lambertian isn't working with vec3(a,b,c)
metal is working with vec3(a,b,c),f

**Comment by dafhi** [comment]
camera settings for final scene in book one not listed in dev

**Comment by hollasch** [comment]
Good point @dafhi. Recorded in new issue #344.

**Comment by hollasch** [comment]
@dafhi — Is "Dahfi" your surname? Full name "David Dahfi"? I'd like to add you to the acknowledgements.

**Comment by hollasch** [comment]
Ref PR #345.

**Comment by dafhi** [comment]
David Chambers.  What an honor!

**Comment by dafhi** [comment]
think I found another one.  I am a c++ newb so bear with

In One Weekend:  dev
vec3 class (x3)
        vec3& vec3::oper+=(const vec3 &v) { ... extra qualification 'vec3::' on member 'operator+='

I can start separate threads for each new issue in the future if more convenient

**Comment by hollasch** [comment]
Yes, please create a new issue for each specific defect. These are referenced from each fix commit and are planned and reviewed independently.
