### ISSUE TITLE
Book One, newly-typed vec3.h into "common"

### ISSUE THREAD

**Issue by dafhi** [RayTracing/raytracing.github.io#347]
Dev.

Creating a color gradient image (Listing 6)
source code looks like it wants newly-typed "vec3.h" into the common folder

**Comment by hollasch** [comment]
First line of listing:

    #include "common/vec3.h"

Unless your point is that the location of common header files is not directly addressed in the text. It makes sense to do that.

**Comment by hollasch** [comment]
Proposed fix:
1. At first common header (which I _think_ is `vec3.h`), introduce the idea of the project `common` folder.
2. All common-header filenames in code listing captions should be prefixed with `common/`

**Comment by dafhi** [comment]
What I think I was thinking at the time:  copied the src folder and started typing examples.

And newly typed vec3.h (which may contain typos) would not be good to overwrite into common's vec3.h

**Comment by dafhi** [comment]
Yeah I think I copied src so I could drag all the root files into ide.

Knowing vec3 could contain a typo i thought saving to root would be best so as not to kill the perfection in common

So .. overall I'd say my issue here probably isn't one.  Maybe leave it open for a bit and I might remember exactly

**Comment by dafhi** [comment]
I often remember something immediately after closing, haha, but with this, I just can't see it now.

**Comment by hollasch** [comment]
Abandoned the original idea of specifying the `src/common/` folder everywhere for common headers. PR #387 changes the `CMake` options so that common headers can reside either in the `src/common/` directory or in the project directory along with all other source. Bottom line is that we no longer need to specify the common directory for common headers.
