### ISSUE TITLE
Book one:  2 suggestions

### ISSUE THREAD

**Issue by dafhi** [RayTracing/raytracing.github.io#350]
Dev.

Rendering blue-to-white gradient (Listing 8) does not need #include iostream (already in vec3.h)

I actually liked Peter's nx, ny variables because I get a feel for his coding background.

**Comment by hollasch** [comment]
It's generally a good idea to follow "include what you use". You shouldn't have to memorize the includes that are included in the headers you use, or in the headers _they_ use, and so on.

In this example, if `ray.h` changed and no longer needed `vec3.h`, the gradient code would break. Or consider one level down, if `ray.h` includes `vec3.h` includes `iostream` includes `yvals_core.h` includes `crtdefs.h` includes `vadefs.h`.

You could get away without including `vadefs.h` if you include `ray.h`, but it's not good practice.

**Comment by hollasch** [comment]
Resolved as "by design".
