### ISSUE TITLE
Book 1, Scene with metal spheres

### ISSUE THREAD

**Issue by dafhi** [RayTracing/raytracing.github.io#356]
Dev.

Listing [sphere.h] Ray-sphere intersection with added material information

needs a highlight around 3-param constructor.

**Comment by hollasch** [comment]
Are you working in the `development` branch? That's where these issues should be based on at this point.

**Comment by dafhi** [comment]
yes.  just updated comment.

here's the error from Dev C++  (gcc 8.2.0)
invalid new-expression of abstract class type 'sphere'

**Comment by hollasch** [comment]
Great. Since listing numbers are auto-generated on render, it's easier to determine which listing based on the caption text.

**Comment by dafhi** [comment]
the previous example worked .. "random in hemisphere" .. so this is why I think hittable_list needs update

**Comment by hollasch** [comment]
Would you be interested in creating pull requests for some of these? If so, I'll add you to the contributors group.

**Comment by dafhi** [comment]
My source files are heavily edited from the original to use SDL2 .. and so I can 'somewhat quickly' swap around to compare different versions.  But sure I could upload what I have.  I'm new to C and C++

**Comment by hollasch** [comment]
Also, are you on Slack? If so, send me your email address and I'll send you an invite to the RTW Slack workspace.

**Comment by dafhi** [comment]
I am not on slack.  I can look it up

**Comment by hollasch** [comment]
https://slack.com/. Just an option, so no big deal if it's not worth the hassle.

Invite sent to contributors group.

**Comment by dafhi** [comment]
heh.  at this point they're asking for a company name.

yeah.  I'll definitely accept the invite and see if I can zip what I have.  I've never done or requested a pull

**Comment by hollasch** [comment]
Ok. In the meantime, let's take this conversation off the issue. My email address is steve@hollasch.net.

**Comment by dafhi** [comment]
I think actual Listing 46: [main.cc] Scene with metal spheres
may be the culprit.

I pasted to /src/main.cc and get the same thing.
```

92	9	material.h	[Note] candidate: 'metal::metal(const vec3&, double)'
92	9	material.h	[Note] candidate expects 2 arguments, 1 provided
90	7	material.h	[Note] candidate: 'constexpr metal::metal(const metal&)'
90	7	material.h	[Note] no known conversion for argument 1 from 'vec3' to 'const metal&'
90	7	material.h	[Note] candidate: 'constexpr metal::metal(metal&&)'
90	7	material.h	[Note] no known conversion for argument 1 from 'vec3' to 'metal&&'

```
i am new to C

**Comment by dafhi** [comment]
I keep going in circles with this one.  I'm thinking it's hittable_list that needs an update prior to this listing

**Comment by dafhi** [comment]
Found!

Listing 41: [sphere.h] Ray-sphere intersection with added material information
new constructor information isn't highlighted.
        sphere(vec3 cen, double r, shared_ptr<material> m)
            : center(cen), radius(r), mat_ptr(m) {};

thanks a lot ;)

But the two spheres on either side are black :P  Whatev.
