### ISSUE TITLE
Book 1, two listings with same minor issue

### ISSUE THREAD

**Issue by dafhi** [RayTracing/raytracing.github.io#358]
Dev.

Listing 10: [main.cc] Rendering surface normals on a sphere
Listing 22: [main.cc] desc

vec3 ray_color(const ray& r) {
..
-highlight    auto t = 0.5*(unit_direction.y() + 1.0);

**Comment by hollasch** [comment]
I don't see a problem. What's the minor issue?

**Comment by dafhi** [comment]
the auto line is highlighted.  it doesn't need to be

**Comment by hollasch** [comment]
The first instance assigns a new value to existing variable `t`, the second instance defines new value `t`. The highlight indicates that the code has changed and the reader must change the line to a new variable definition.

**Comment by dafhi** [comment]
mybad.  thanks
