### ISSUE TITLE
Quick note about Random() * 255.999

### ISSUE THREAD

**Issue by dafhi** [RayTracing/raytracing.github.io#359]
[updated:  old ceiling was 2]

Coming from my background in 2d programming
 
rnd*255.999 will yield a bias.

  an illustration:

Range with ceiling of 3 will yield

0 to 0.499:  [integer result:  0]  1/6 chance
.5 to 1.499: [integer result:  1]  
1.5 to 2.499: [integer result:  2]
2.5 to 2.999: [integer result:  3]  1/6 chance

Corrected approach:  rnd*256 - 0.5

**Comment by hollasch** [comment]
For a integers in the range [0,2), the equation ⌊1.999 · _R_⌋ will yield 0 for _R_ ∈ [0,½], and 1 for _R_ ∈ (½,1).

With regard to the proposed equation `rnd * 256 - 0.5`, consider the round trip. Given rnd = 255/256, the formula would yield the value 254. With rnd = 0, we'd get a result of -1.

**Comment by dafhi** [comment]
Will hit 0 25% of the time out of all 3 choices.  should hit 33.3..% of the time.
will hit 1 50% of the time.  shouldi hit 33.3..% of the time ..

[0*rnd to .999*rnd] mult 256 =
0 to 255.999
- 0.5 = 
-0.5 to 255.499
(rounds up to rounds down)

At least that's how it is in FreeBASIC.  I'll do some tests

**Comment by dafhi** [comment]
my bad.  i meant ceiling of 3.  updating comment

**Comment by hollasch** [comment]
With a ceiling of 3, you'd be dividing the [0,1) interval into four parts: [0.0, .25)→0, [.25, .50)→1, [.50, .75)→2, and [.75, 1.0)→3. 

x*3 - 0.5 fails this mapping. For example, f(0.40) yields 0, where it should yield 1.

The book's equation of `floor(2.999 * x)` properly divides the interval into four equal intervals. f(0.24) yields 0, and f(0.26) yields 1.

**Comment by hollasch** [comment]
Also note that in C++, static_cast<int>(x) does not perform rounding. It's a truncation.

**Comment by hollasch** [comment]
There is the possibility of handling the exceptional value of 1.0 inside the clamp function rather than via the scaling. Thus

    f(x) = static_cast<int>(256 * clamp(x, 0.0, 0.999));

(The 0.999) could be 255/256 for precision, but that precision isn't necessary since we're just mashing all upper values into the last interval, including those far outside the interval, like 1e6.)

**Comment by hollasch** [comment]
Heh. I'd already had the above improvement, just not everywhere. PR incoming...

**Comment by dafhi** [comment]
Krr I wish I was proficient in c

Try the c version of this
```
dim as integer bins(2)

for i as integer = 1 to 1e6
   bins(rnd*2) += 1
Next

for i as integer = 0 to 2
  print bins(i); " ";
Next
```
Yesterday I updated my first comment.

**Comment by hollasch** [comment]
Not sure what the language above is, but it isn't C++.

Given the code `static_cast<int>(256.0 * clamp(x, 0.0, 0.999))`, give me an example of an input `double` value `x` that yields an incorrect unsigned byte value. I don't see any bug here.

**Comment by dafhi** [comment]
it's BASIC.  I dont know c well enough yet and I get headaches if I think too hard.
yes it rounds.  So then if C truncates, .. well how about that.  I guess then there's no problem.

Still, later when I have some time I'll try it

**Comment by hollasch** [comment]
A diagram might help. Here's an example with [0,1) mapped to four buckets [0,3]:

```
                ...---+---------+---------+---------+---------+----...
     x                0        0.25      0.50      0.75      1.00
    x*3               0        1.00      2.00      3.00      4.00

 trunc(x*3)           [    0    )    1    )    2    )    3   ) 
```

**Comment by dafhi** [comment]
yeah, piece of cake.

nice diagram

**Comment by hollasch** [comment]
Fixed error in diagram; should have been `x*4`.

**Comment by hollasch** [comment]
Ok, resolved as "by design".
