### ISSUE TITLE
Book One, Listing: An example allocation using shared_ptr

### ISSUE THREAD

**Issue by dafhi** [RayTracing/raytracing.github.io#364]
Dev.

Was confusing until i cross-referenced with how it was used in a Listing.  Initial impression was that (1, true) mean number of allocations and "no clue what true meant."

I suggest
```
shared_ptr<thing> thing_ptr = make_shared<thing>(constructor parms, ..);
auto thing2_ptr = make_shared<thing2>(constructor parms, ..);
```

**Comment by hollasch** [comment]
Agreed, that's confusing. Will fix.
