### ISSUE TITLE
Book One - Listing [main.cc] Ray color with scattered reflectance

### ISSUE THREAD

**Issue by dafhi** [RayTracing/raytracing.github.io#365]
Dev.

[temporarily] fixes black spheres from [Issue #356: Scene with metal spheres]

```
vec3 ray_color(const ray& r, const hittable& world, int depth) {
    hit_record rec;
    if (world.hit(r, 0.001, infinity, rec)) {
        ray scattered;
        vec3 attenuation;
        if (rec.mat_ptr->scatter(r, rec, attenuation, scattered)) {
            // If we've exceeded the ray bounce limit, no more light is gathered.
            if (depth < 1) return attenuation;
            
            return attenuation * ray_color(scattered, world, depth-1);
        }

    ..
}
```

on fuzzy spheres is definitely incorrect;  Left and Right spheres show sky-lit boundaries rather than darker

**Comment by dafhi** [comment]
cancel this one.

Just tried ray_color() from 
Listing [main.cc] Ray color with scattered reflectance

and it works now.

Discovered I had problems with some of my headers which was causing blackness.

I'll let someone else close this issue as I don't want to interrupt any processing

**Comment by trevordblack** [comment]
So, this isn't a bug, and was just a mistake?

**Comment by dafhi** [comment]
yeah my "fix" isn't as good as the corresponding ray_color() from the book.

**Comment by dafhi** [comment]
I will say this:  if max_depth = 1 (Book One - dev - shiny spheres),
there's definitely a problem with ray_color()
