### ISSUE TITLE
[cosmetic] Left and Right spheres are swapped

### ISSUE THREAD

**Issue by dafhi** [RayTracing/raytracing.github.io#366]
Just after Listing: [material.h] Metal spheres with fuzziness
".. adding fuzziness 0.3 and 1.0 .."

comes out with silver sphere being the more fuzzy one

**Comment by hollasch** [comment]
The text and image are correct. Here's the original image:
![original](https://user-images.githubusercontent.com/313871/75089370-d8978a80-550c-11ea-8f67-3128bfbe0fd9.png)

This is the image if silver was the more fuzzy (1.00) and the gold sphere had fuzziness 0.30:
![fuzzy-left](https://user-images.githubusercontent.com/313871/75089371-de8d6b80-550c-11ea-8cf9-d6417094275f.png)

**Comment by dafhi** [comment]
sphere on bottom is x: -1 so it's "Left" .. correct?  and that's the silver one

    world.add(make_shared<sphere>(vec3(1,0,-1), 0.5, make_shared<metal>(vec3(0.8, 0.6, 0.2))));
    world.add(make_shared<sphere>(vec3(-1,0,-1), 0.5, make_shared<metal>(vec3(0.8, 0.8, 0.8))));
Listing: [main.cc] Scene with metal spheres

0.3 goes on top
1.0 goes to bottom

**Comment by hollasch** [comment]
He's talking about the rendered image, not the order in source code: 0.3 on the left, 1.0 on the right.

**Comment by dafhi** [comment]
In order to "access" the left image though, a coder is expecting to type 0.3 on the top line.
