### ISSUE TITLE
Book error in "One Dimensional MC Integration"

### ISSUE THREAD

**Issue by amesgames** [RayTracing/raytracing.github.io#378]
Really nice work on the book and example source code.

In the third book, _Ray Tracing: The Rest of Your Life_, there is an error in the following equation:

area(C′r,0,2) = I[0,2] C′rdr = C′r^2(2)−C′r^2(0) = 2C′

Notice that the _r_ appears in the definite integral difference part. Properly substituting 0 and 2 for r, the equation should read something like:

area(C′r,0,2) = I[0,2] C′rdr = (C′*(2)^2)/2 − (C′*(0)^2)/2 = 2*C′

**Comment by trevordblack** [comment]
Nice catch!
It's not too common that we get people bringing up issues that deep into the series.

And, you're right. That notation is awkward and wrong.

Should be written out with `\Biggr|` from latex

```
area(C′r,0,2) = I[0,2] C′rdr =  \frac{C'r^2}{2} \biggr|_{2}^{0}  = (C′(2)^2)/2 − (C′(0)^2)/2 = 2*C′
```
