### ISSUE TITLE
Book One - "multiple objects to use a common object"

### ISSUE THREAD

**Issue by TheRayTracer** [RayTracing/raytracing.github.io#384]
Dev.

On line 1010 the word "object" is used twice in the same sentence. I think it would be an easier read, and more technically accurate, if we could change the second "object" to "instance".

In full:

We'll use shared pointers in our code, because it allows multiple objects to use a common single instance (for example, a bunch of spheres that all use the same material), and because it makes memory management automatic and easier to reason about.

**Comment by hollasch** [comment]
Makes sense.
