### ISSUE TITLE
sphere inter optim

### ISSUE THREAD

**Issue by dafhi** [RayTracing/raytracing.github.io#393]
Karoly's course brings up the idea that when ray.direction is normalized (say for example at the beginning of ray_color()), the 'a' term equals 1.

I was thinking it might be introduced ahead of the final scene in Book One, with an opener perhaps "It turns out there is an additional optimization to the sphere intersection .."

This would task the end of paragraph 2 after Listing:  ray.h] The ray class: "Note that I do not make the ray direction a unit length vector because I think not doing that makes for simpler and slightly faster code."

**Comment by trevordblack** [comment]
Performance for its own sake I'd generally not a good idea for our code base. Is there a learning venue here?

-------- Original Message --------

**Comment by dafhi** [comment]
Excellent point.  And I agree.
