### ISSUE TITLE
Image: img.bouncing-spheres.jpg should be regenerated

### ISSUE THREAD

**Issue by Rastaban** [RayTracing/raytracing.github.io#395]
The bouncing spheres do not have motion blur in the reflection off the metallic sphere in images/img.bouncing-spheres.jpg.  Whatever bug was causing the issue appears to have been addressed in the code because I see the motion blur in the reflection when I run TheNextWeek with `random_scene()`.  The image probably just needs to be regenerated.

**Comment by hollasch** [comment]
Now covered in issue #567
