### ISSUE TITLE
Array out of range

### ISSUE THREAD

**Issue by oxine** [RayTracing/raytracing.github.io#396]
https://github.com/RayTracing/raytracing.github.io/blob/00d0ab026ab86083ee4076d00fcb2802362cb4bb/books/RayTracingTheNextWeek.html#L1099

i j k can be minus value so would leads to error

**Comment by hollasch** [comment]
Original code was:

    float noise(const vec3& p) const {

        float u = p.x() - floor(p.x());
        float v = p.y() - floor(p.y());
        float w = p.z() - floor(p.z());

        int i = int(4*p.x()) & 255;
        int j = int(4*p.y()) & 255;
        int k = int(4*p.z()) & 255;

        return ranfloat[perm_x[i] ^ perm_y[j] ^ perm_z[k]];
    }

Need to track down the evolution of this code.

**Comment by hollasch** [comment]
Well … that was fun. I had to go back to the archives for the original repository for _The Next Week_. All changes are in the new unified repository, but the combination of multiple streams of development makes tracking down the code development for this chunk non-trivial.

Anyway, this code has been broken from the very start in the repo when I first introduced it in commit d1ecb9d2, in 2019-07-28. It was basically a transcription error on my part, and I'm a bit surprised that no-one's reported it until now (thank you @oxine!).

Will fix for upcoming v3.0.0 release.

**Comment by hollasch** [comment]
For the record, my original (bad) transcription was:

    float noise(const vec3& p) const {
        float u = p.x() - floor(p.x());
        float v = p.y() - floor(p.y());
        float w = p.z() - floor(p.z());

        int i = floor(p.x());
        int j = floor(p.y());
        int k = floor(p.z());

        return ranfloat[perm_x[i] ^ perm_y[j] ^ perm_z[k]];
    }

**Comment by hollasch** [comment]
@oxine — can you verify the following works? Thanks.

    double noise(const vec3& p) const {
        auto u = p.x() - floor(p.x());
        auto v = p.y() - floor(p.y());
        auto w = p.z() - floor(p.z());

        auto i = static_cast<int>(4*p.x()) & 255;
        auto j = static_cast<int>(4*p.y()) & 255;
        auto k = static_cast<int>(4*p.z()) & 255;

        return ranfloat[perm_x[i] ^ perm_y[j] ^ perm_z[k]];
    }

**Comment by oxine** [comment]
Verified，now it works well.
