### ISSUE TITLE
Spelling mistake in book2 code block

### ISSUE THREAD

**Issue by oxine** [RayTracing/raytracing.github.io#399]
https://github.com/RayTracing/raytracing.github.io/blob/00d0ab026ab86083ee4076d00fcb2802362cb4bb/books/RayTracingTheNextWeek.html#L883

here `const = O` should be `const = 0` ，but not capitalized letter o.

Since i am not a native speaker, how do we discrible this case in English?

**Comment by hollasch** [comment]
Thanks! “Spelling mistake” is fine. This would also commonly be referred to as a “typo”, slang for a typographical error. In this particular case, it was possibly due to OCR, so ... ocro? Ocrerr?

**Comment by oxine** [comment]
Thank you! Looking forward to the v3.
