### ISSUE TITLE
Revisit existing releases to update URLs and other information

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#4]
This is really the last step of the v2 release — after everything's live, fix up external references.

**Comment by trevordblack** [comment]
the book links in CONTRIBUTING.md are incorrect.
Should be
https://github.com/RayTracing/raytracing.github.io/tree/master/books/*

**Comment by hollasch** [comment]
This issue is about external links — Eric Haine's site, in1weekend.com, and so forth.

**Comment by hollasch** [comment]
Sent update email to Erik Haines for his RealTimeRendering web site. Not many other links, judging by internet search.
