### ISSUE TITLE
Move BVH one chapter earlier in _The Next Week_

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#408]
@trevordblack suggests that we should consider moving BVH coverage ~to _The Next Week_, chapter 1, and out of _In One Weekend_~ one chapter earlier in _Ray Tracing: The Next Week_.

This is a large change, as it affects two books and two bodies of source code. However, our goal with v3 is to grab all of the major changes in one release, so subsequent releases can limit themselves to fixes and additions. My (Hollasch) opinion is that if it makes sense to do this, we should get it into v3.0.0.

**Comment by petershirley** [comment]
Wait isn't BVH in already book 2? The next week chapter 3?

**Comment by trevordblack** [comment]
Errrrr.

Chapter 2: Motion Blur
Chapter 3: BVH

->

Chapter 2: BVH
Chapter 3: Motion Blur

**Comment by trevordblack** [comment]
To be clear. I'm on the fence about this one.
I don't like the idea of starting a book with homework, since BVH is pretty much pure math & code without any new visuals for the user to grab on to

**Comment by trevordblack** [comment]
I lean strongly on the close side. I think this issue should just be dropped

**Comment by petershirley** [comment]
I still have no strong opinion so yield to Trevor :)
