### ISSUE TITLE
Revisit math notation for points and vectors

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#412]
Peter's latest idea: uppercase for points, lowercase for vectors.

**Comment by hollasch** [comment]
So I think the following works:

- Points: uppercase bold non-italic
- Vectors: lowercase bold non-italic
- Other variables, including scalars, are italicized
- No vector barbs used anywhere

**Comment by trevordblack** [comment]
I noticed some inconsistencies in points/vector/etc. in my pass, I'll continue to mark them up in #333, but should I hold add off adding a commit with those changes?

**Comment by hollasch** [comment]
Probably merge PR #483 into your changes.

**Comment by hollasch** [comment]
Done in PR #483
