### ISSUE TITLE
TheRestOfYourLife, Sampling Lights Directly: notation "alpha" not explained.

### ISSUE THREAD

**Issue by iaomw** [RayTracing/raytracing.github.io#416]
![image](https://user-images.githubusercontent.com/2307692/77827513-52c3bc00-7116-11ea-8371-8002b8b08536.png)
This notation or angle `alpha` is not explained in previous paragraphs or figures.
What is the meaning of `alpha`? Where is that angel?

**Comment by trevordblack** [comment]
This chapter has been completely rewritten, and the \alpha has been replaced by a \theta, which if I remember correctly, is the accurate greek letter for this case.

I'm closing out this issue.
