### ISSUE TITLE
Inconsistent use of t0 and tmin

### ISSUE THREAD

**Issue by trevordblack** [RayTracing/raytracing.github.io#418]
In geometric objects with hit, bounding_box,

the function signatures between objects vary between using t0,t1 and t_min, t_max

**Comment by hollasch** [comment]
Also `tmin`, `tmax`.

**Comment by hollasch** [comment]
Preference?

**Comment by hollasch** [comment]
This should really be a major-level change, since it impacts the APIs and structures throughout the code.

**Comment by trevordblack** [comment]
I prefer the explicit `t*min`, not sure whether I prefer `t_min` or `tmin`

**Comment by trevordblack** [comment]
Adding to the pile here, t0 and t1 are parameters for time0 and time1 for the camera class, so using them as the distance parameter for ray is an even badderer idea.

**Comment by hollasch** [comment]
Given that rays are parameterized by _t_, t0 and t1 makes a lot more sense for rays.

**Comment by hollasch** [comment]
In general, I think `time0` and `time1` are much more descriptive than some name involving `t`. We _could_ go with `start` and `end`, but that can also refer to physical spans.

**Comment by trevordblack** [comment]
See #428 

`t` is not the same thing as `time` but some confusion could arise due to the choice of t as parameterization

**Comment by hollasch** [comment]
Resolved in #678
