### ISSUE TITLE
no matching function for call to 'make_shared' Listing 23

### ISSUE THREAD

**Issue by RMaughan93** [RayTracing/raytracing.github.io#421]
`hittable_list world;
    world.add(make_shared<sphere>(vec3(0,0,-1), 0.5));
    world.add(make_shared<sphere>(vec3(0,-100.5,-1), 100));`

throws the above error in my IDE, not sure where I'm going wrong.

**Comment by trevordblack** [comment]
What is your IDE? Do you know if you are running c++11?

Did you `#include <memory>`

**Comment by trevordblack** [comment]
Were you able to fix it?

**Comment by RMaughan93** [comment]
> What is your IDE? Do you know if you are running c++11?
> 
> Did you `#include <memory>`

I am running VSCode and I believe I am running C++ 11. I am also using `#include <memory>`

**Comment by RMaughan93** [comment]
`
hittable_list world;
    world.add(make_shared<sphere>(vec3(0,0,-1), 0.5));
    world.add(make_shared<sphere>(vec3(0,-100.5,-1), 100));
`
is throwing 
`
main.cc:33:15: error: no matching function for call to 'make_shared'
    world.add(make_shared<sphere>(vec3(0,-100.5,-1), 100));
`

I have made sure all include statements are correct

**Comment by hollasch** [comment]
Here's some info on setting up VSCode to work with C++11: https://stackoverflow.com/questions/53995830/compiling-c11-in-visual-studio-code/53995912#answer-53995912

**Comment by hollasch** [comment]
Punted from v3.0.2

**Comment by hollasch** [comment]
Closing this issue, as there hasn't been any motion for two weeks.

@RMaughan93 -- as you write your own raytracer, feel free to use bare pointers instead, and rely on memory cleanup on program termination. This can cause memory leaks if you generate multiple images, but there are multiple ways to address that.

**Comment by m-schaeffer** [comment]
InOneWeekend Section 6.7 Listing 24, having an error about no matching constructor for the following two lines (like maughan, I also checked to make sure the includes are correct and that I'm using std::make_shared):
world.add(make_shared<sphere>(point3(0,0,-1), 0.5)); 
world.add(make_shared<sphere>(point3(0,-100.5,-1), 100));

The error is as follows:

In file included from main.cpp:1:
In file included from ./rtweekend.h:7:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:4405:26: error: 
      no matching constructor for initialization of '_CntrlBlk' (aka
      '__shared_ptr_emplace<sphere, allocator<sphere> >')
    ::new(__hold2.get()) _CntrlBlk(__a2, _VSTD::forward<_Args>(__args)...);
                         ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
main.cpp:30:15: note: in instantiation of function template specialization
      'std::__1::make_shared<sphere, vec3, double>' requested here
    world.add(make_shared<sphere>(point3(0,0,-1), 0.5));
              ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:3585:9: note: 
      candidate constructor [with _A0 = vec3, _A1 = double] not viable: expects
      an l-value for 2nd argument
        __shared_ptr_emplace(_Alloc __a, _A0& __a0, _A1& __a1)
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:3580:9: note: 
      candidate constructor template not viable: requires 2 arguments, but 3
      were provided
        __shared_ptr_emplace(_Alloc __a, _A0& __a0)
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:3590:9: note: 
      candidate constructor template not viable: requires 4 arguments, but 3
      were provided
        __shared_ptr_emplace(_Alloc __a, _A0& __a0, _A1& __a1, _A2& __a2)
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:3566:5: note: 
      candidate constructor not viable: requires single argument '__a', but 3
      arguments were provided
    __shared_ptr_emplace(_Alloc __a)
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:3559:7: note: 
      candidate constructor (the implicit copy constructor) not viable: requires
      1 argument, but 3 were provided
class __shared_ptr_emplace
      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:4405:26: error: 
      no matching constructor for initialization of '_CntrlBlk' (aka
      '__shared_ptr_emplace<sphere, allocator<sphere> >')
    ::new(__hold2.get()) _CntrlBlk(__a2, _VSTD::forward<_Args>(__args)...);
                         ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by m-schaeffer** [comment]
I figured out my issue. I needed to enable support for c++11 in the compiler. The code compiles as written.

**Comment by hollasch** [comment]
Thanks for following up!
