### ISSUE TITLE
Seemingly erroneous highlighting in Firefox

### ISSUE THREAD

**Issue by trevordblack** [RayTracing/raytracing.github.io#430]
Our program outputs the image to the standard output stream (std::cout), so leave that alone and instead write to the error output stream (std::cerr): 

->

Our program outputs the image to the standard output stream (`std::cout`), so leave that alone and instead write to the error output stream (`std::cerr`):

**Comment by trevordblack** [comment]
Hang on. In Firefox, I get `stb_image.h` highlighted. But `std::cerr` and `vec3` sometimes highlighted.

In the text, `std:cerr` is correctly styled with \`\` but isn't highlighted.

**Comment by hollasch** [comment]
We have a CSS rule for `.md code` and another for `.md p code`. It looks like text inside a `div.together` may not be enclosed in a `<p>` element, so the styling rules are firing differently. One of the above specifies background, another does not.

Just need a general review of the CSS code styling and fix.
