### ISSUE TITLE
Need to direct to stb_image on github

### ISSUE THREAD

**Issue by trevordblack** [RayTracing/raytracing.github.io#431]
We don't have a way for the reader to get to stb_image.

We need to
1. Point to their github
2. Explain how to integrate the file.

At present, all we have is

"Thankfully, the stb_image package makes that super simple — just include the header rtw_stb_image.h in main.h: "

This is no where near good enough

**Comment by hollasch** [comment]
PR #433

**Comment by hollasch** [comment]
There's no real integration, since it's a header-only library. All documentation is in the header itself.
