### ISSUE TITLE
Consider changing Cornell Box to unit cube

### ISSUE THREAD

**Issue by trevordblack** [RayTracing/raytracing.github.io#432]
the Cornell box has dimensions of 0, 213, 343, 55

Consider changing the whole thing to be within a 0.0 - 1.0 unit cube.

This would actually be a significant change

**Comment by hollasch** [comment]
I don't think I see the value in making such a change. I'd vote to punt this one.

**Comment by TheRayTracer** [comment]
Without having read this issue, when I followed along with the book series especially book 3, I choose to model the Cornell Box as a unit cube. While it served "no value", positioning items inside and it's overall creation was much easier compared to an arbitrary chosen size. The unit cube in my case was -0.5 to 0.5 where 0,0 was the very centre.

Reference: https://github.com/TheRayTracer/Monte_Carlo/blob/main/scenes/cornell_box.txt

**Comment by hollasch** [comment]
Ok, punting this one.
