### ISSUE TITLE
Small error in "One Dimensional MC Integration"

### ISSUE THREAD

**Issue by domitry** [RayTracing/raytracing.github.io#438]
https://github.com/RayTracing/raytracing.github.io/blob/2460c2ede16dbb8646a9704c6b091a39fb0b3e42/books/RayTracingTheRestOfYourLife.html#L200

While the interval of integration is [0, 2], corresponding sample code is as below:

https://github.com/RayTracing/raytracing.github.io/blob/2460c2ede16dbb8646a9704c6b091a39fb0b3e42/books/RayTracingTheRestOfYourLife.html#L226-L233

 Should `sum/N` be replaced to `2*sum/N`?

**Comment by petershirley** [comment]
Let's try f(x) = 1 as the integrand.   That gives "I = 2" as the analytic answer.   Then the sum += 1 should be what we have.  So sum = N.   Then we divide by N and get I=1.  OK yes something is wrong here.  We need to divide by p(x) which is 1/2, so multiply by 2.  I agree with the fix.
