### ISSUE TITLE
Question about true lambertian

### ISSUE THREAD

**Issue by oxine** [RayTracing/raytracing.github.io#463]
I just have some question in book1 at the lambert part which confused me a lot.

Why `random_in_unit_sphere()` made the distribution scales by cos^3(ϕ)  and the truely lambertian has a distribution of cos(ϕ)? Is there any paper or post about the mathematical prove of the distribution for further reading?

And why in  `random_in_hemisphere()` we use `random_in_unit_sphere()` rather than`random_in_unit_vector()`?  Would this make a distribution of cos^3 which is not true lambertian?

**Comment by trevordblack** [comment]
1. https://github.com/vchizhov/Derivations/blob/master/Probability%20density%20functions%20of%20the%20projected%20offset%20disk%2C%20circle%2C%20ball%2C%20and%20sphere.pdf

2. The choice of `random_in_unit_vector()` and `random_in_unit_sphere()` shouldn't matter for hemispherical scattering. The idea is to have uniform scattering over the entire half-sphere (probability = 1/(2pi) for all `theta`,`phi`). Both of these functions have a uniform probability along `theta`, `phi`. The only difference is that their distribution in `r`. `random_in_unit_vector` has `r` always 1, whereas `random_in_unit_sphere` has `r` with a distribution between 0 and 1. We don't really care about `r` so either will work.

**Comment by oxine** [comment]
Thank you!!!  Helps a lot.
