### ISSUE TITLE
Book 3: Question about mixture PDF

### ISSUE THREAD

**Issue by Dalamar42** [RayTracing/raytracing.github.io#469]
First of all I wanted to thank you for these books. I started them last year as a fun project to learn Rust with after a colleague recommended them. Back then I had no prior exposure to graphics programming, but since then and through these books I have developed an interest in the field and have been wanting to learn more about ray tracing on my own.

The question I wanted to ask is about a problem I am having trying to implement the mixture PDF from chapter 10. In short, as best I can tell I am producing a correct image or at least one that is visually very close to the reference image in the book except that it is significantly darker than both the one in the book (last image in chapter 10) and also the image my own code produces without light sampling.

I am attaching some examples of my testing to make what I mean more clear. All the following are with 1000  rays per pixel.

Image with cosine sampling of lambertian surfaces and no light sampling.
![no_light_sampling](https://user-images.githubusercontent.com/1230838/79073080-622d3280-7cdc-11ea-83d1-1a487fd4a17b.png)

Only cosine sampling again, this time by using the mixture PDF code and passing the cosine PDF as both PDFs in the mixture. This is to test the mixture code. As expected picture looks the same.
![only_cosine_sampling](https://user-images.githubusercontent.com/1230838/79073092-7a04b680-7cdc-11ea-9793-3f193c2fda51.png)

Only light sampling, by passing the geometry PDF twice to the mixture PDF code. Looks similar to the book's image.
![only_light_sampling](https://user-images.githubusercontent.com/1230838/79073121-aae4eb80-7cdc-11ea-8ae9-336432b26d75.png)

This shows the problem. 50% light sampling, 50% cosine sampling. It is a lot darker than the rest.
![50_light_sampling](https://user-images.githubusercontent.com/1230838/79073141-c64ff680-7cdc-11ea-9242-dc4be5471ccf.png)

50% light / 50% cosine sampling again, but this time I have changed the RGB values for the light from (15, 15, 15) to (60, 60, 60). This now looks closer to the book.
![bright_light_50_light_sampling](https://user-images.githubusercontent.com/1230838/79073154-da93f380-7cdc-11ea-883d-e0b9055a3872.png)

I have gone through my code several times and compared it to the reference implementation and as far as I can see I am doing the same things (not identical because I am writing in Rust, but the logic should be the same).

I was wondering if you have any pointers about which part of the logic could have this effect?

**Comment by trevordblack** [comment]
1. !!!! The images in TheRestOfYourLife are wrong at the moment! Don't sweat that for right now. We're hoping to have better images up in the next 1-2 weeks (sorry)

**Comment by trevordblack** [comment]
For the time being, double-check your intuition, but assume that your images are right, _not the books_.
Alternatively, you can sanity-check your work by using the Cornell box found at Morgan McGuire's repo:

http://casual-effects.com/data/index.html

Navigate to Cornell Box, "download" and try one of the included boxes.
Are you at all familiar with the obj file format?

**Comment by Dalamar42** [comment]
Thanks for the quick reply!

My initial suspicion was that the mixture pdf value was somehow wrong by a scale factor thus uniformly darkening the image, but I can't see anything in the code that would have this effect.

I will try your suggestion and compare with a reference box.

> Are you at all familiar with the obj file format?

I am not, but I was looking today into what the standard file formats for scenes are. Currently I've implemented my own by just doing a basic YAML serialisation of the objects in the code, but I want to switch to something widely used precisely so I can try other scenes and this seems like a good choice.

**Comment by Dalamar42** [comment]
I believe I have identified the bug. It was a mistake in the calculation of the cosine PDF and the rectangle PDF caused by the fact that the direction was not the unit vector. After fixing this, the generated image has the same brightness regardless of the sampling used as expected.

The first case in the cosine PDF is just a problem with my code. Both the book and the reference code correctly use the unit vector.

However, I am not sure about the rectangle code.

The computation of the cosine divides by the length of `v` to correct for `v` not being a unit vector so this should be fine:
```cpp
auto cosine = fabs(dot(v, rec.normal) / v.length());
```

However, I am not sure about this line:
```cpp
auto distance_squared = rec.t * rec.t * v.length_squared();
```

If I understood correctly from the equations this should be the square of the distance between the origin and the hit point, but `rec.t * rec.t` should already be that value. A direction generated by the rectangle's `random` method as `v = random_point_on_rect - origin_point`, the length of `v` should be equal to the hit distance so this ends up being the fourth power of the distance.

**Comment by hackmad** [comment]
@Dalamar42 I faced similar issues with the relative brightness. In my case, I found that the normals in hit record were not unit vectors (I haven't figured out why that is happening since there is no scaling/shearing transformations happening during intersection computations). In fact any cosine angle computation requires both vectors to be unit vectors because:

```
dot(A, B) = |A| * |B| * cos(theta)
```

Any calculation that involved dot products such as the cosine pdf, reflections and even refractions were all responsible for dark images and improper reflection.

> However, I am not sure about this line:
> 
> ```c++
> auto distance_squared = rec.t * rec.t * v.length_squared();
> ```
> 
> If I understood correctly from the equations this should be the square of the distance between the origin and the hit point, but `rec.t * rec.t` should already be that value. A direction generated by the rectangle's `random` method as `v = random_point_on_rect - origin_point` should have a length equal to the hit distance so this ends up being the fourth power of the distance.

So `rec.t` is the parameter along the vector `v` that determines the point on the surface. So `rec.t * v.length()` is the distance to that point and therefore `distance_squared = ( rec.t * v.length() ) ^ 2 = rec.t * rec.t * v.length_squared()`.

**Comment by Dalamar42** [comment]
> @Dalamar42 I faced similar issues with the relative brightness. In my case, I found that the normals in hit record were not unit vectors (I haven't figured out why that is happening since there is no scaling/shearing transformations happening during intersection computations). In fact any cosine angle computation requires both vectors to be unit vectors because:
> 
> ```
> dot(A, B) = |A| * |B| * cos(theta)
> ```
> 
> Any calculation that involved dot products such as the cosine pdf, reflections and even refractions were all responsible for dark images and improper reflection.

I had the exact same problem. I was using non unit-vectors to compute the cosine which produced the wrong values.

> So `rec.t` is the parameter along the vector `v` that determines the point on the surface. So `rec.t * v.length()` is the distance to that point and therefore `distance_squared = ( rec.t * v.length() ) ^ 2 = rec.t * rec.t * v.length_squared()`.

Ah right I see now! I need to double check my code, but I think the direction vector in my rays is always the unit vector so `rec.t == distance` which is why I didn't see a problem when I changed it to `rec.t ^ 2`. Thanks for the explanation.

**Comment by Dalamar42** [comment]
I think given this explanation this issue can probably be closed. The first bug was only in my implementation and the second one was not a bug, but a misunderstanding on my part.

Please feel free to reopen if there is something in here that you think is still relevant.
