### ISSUE TITLE
In One Weekend: Fix numbering in "What's next?"

### ISSUE THREAD

**Issue by shaunplee** [RayTracing/raytracing.github.io#472]
The book concludes with a list of possible extensions. The first, conceptually, is adding Lights to the renderer. However, the first numbered paragraph ends without a period, and the sentence appears to conceptually continue in the second numbered paragraph:

> You now have a cool ray tracer! What next?
> 
> 1. Lights. You can do this explicitly, by sending shadow rays to lights. Or it can be done implicitly by making some objects emit light,
> 2. Biasing scattered rays toward them, and then downweighting those rays to cancel out the bias. Both work. I am in the minority in favoring the latter approach.
> 3. Triangles. Most cool models are in triangle form. The model I/O is the worst and almost everybody tries to get somebody else’s code to do this.

It seems that what was intended was:

> You now have a cool ray tracer! What next?
> 
> 1. Lights. You can do this explicitly, by sending shadow rays to lights. Or it can be done implicitly by making some objects emit light, biasing scattered rays toward them, and then downweighting those rays to cancel out the bias. Both work. I am in the minority in favoring the latter approach.
> 2. Triangles. Most cool models are in triangle form. The model I/O is the worst and almost everybody tries to get somebody else’s code to do this.

I've submitted a [pull request](https://github.com/RayTracing/raytracing.github.io/pull/467) to try to correct this.

**Comment by hollasch** [comment]
Done.
