### ISSUE TITLE
Image url wrong In Book2

### ISSUE THREAD

**Issue by oxine** [RayTracing/raytracing.github.io#473]
https://github.com/RayTracing/raytracing.github.io/blob/51112291826e606047c6bbc3e0fadf3a2386ff73/books/RayTracingTheNextWeek.html#L2110

That should be img.cornell-first.jpg

https://github.com/RayTracing/raytracing.github.io/blob/51112291826e606047c6bbc3e0fadf3a2386ff73/books/RayTracingTheNextWeek.html#L767

We don't use qsort anymore

I've created a PR. It's first time for me. Did I make it in right way?

**Comment by oxine** [comment]
I' ve noticed that since we set normal by `rec.set_face_normal` while hitting, the filp class is not needed anymore.So the image is right for that code. May be we should remove the `flip_face` part?

**Comment by oxine** [comment]
https://github.com/RayTracing/raytracing.github.io/blob/51112291826e606047c6bbc3e0fadf3a2386ff73/books/RayTracingTheNextWeek.html#L2067

here missing the celling rect `objects.add(make_shared<xz_rect>(0, 555, 0, 555, 555, white));`
There should be 6 rect including the light rect

**Comment by hollasch** [comment]
Can you please break these out into separate issues? Thanks!

**Comment by hollasch** [comment]
Also, I can't remember if we've added you yet to the list of contributors. If not, and you want to be included, please let me now your real name. (You can send me email directly at steve@hollasch.net.)

**Comment by oxine** [comment]
Okay, I've send the mail and will separate the issues

**Comment by hollasch** [comment]
Done.
