### ISSUE TITLE
permute() in Listing28 should be static

### ISSUE THREAD

**Issue by oxine** [RayTracing/raytracing.github.io#475]
https://github.com/RayTracing/raytracing.github.io/blob/b54ce97423a4c68b4fc75b3a32cbe4a0a3e8c348/books/RayTracingTheNextWeek.html#L1217

it should be a static function

https://github.com/RayTracing/raytracing.github.io/blob/b54ce97423a4c68b4fc75b3a32cbe4a0a3e8c348/books/RayTracingTheNextWeek.html#L1259

here our `noise_texture()` can't take any param yet

https://github.com/RayTracing/raytracing.github.io/blob/b54ce97423a4c68b4fc75b3a32cbe4a0a3e8c348/books/RayTracingTheNextWeek.html#L1498

OCR error `pexm` should be `perm`

**Comment by hollasch** [comment]
Fixed.
