### ISSUE TITLE
Trevor's Refactoring Pass (Book 2)

### ISSUE THREAD

**Issue by trevordblack** [RayTracing/raytracing.github.io#476]

**Comment by hollasch** [comment]
Can we make this more specific? The other one was a grab bag of random issues.

**Comment by trevordblack** [comment]
Well.

I'm going to be closing out everything brought up in book 1. My hope is to find any architectural problems in the books. But there just weren't all that many in book 1. It's fairly polished at this point.

Book 2 and Book 3 might have more structural problems. I don't have anything specifically in mind, so I'm just hitting things down as I run into them.

Book 3 is the one that needs work. But they may be out of scope for 3.1.0 depending on when we want to push that

**Comment by trevordblack** [comment]
TheNextWeek.html:290-331

Seems highlighting for changed parts of the scene

**Comment by trevordblack** [comment]
TheNextWeek.html:815

    sort the primitives using library qsort

we use std::sort now

**Comment by trevordblack** [comment]
TheNextWeek.html:1588-1595

replace fabs with whatever we typically use locally, ffabs? Make sure correct library is included somewhere

**Comment by hollasch** [comment]
I'd suggest that we make this issue a time-box to go through and spawn issues from that. For example, the above should be three separate issues. The problem we keep repeating is having fuzzy amorphous issues where we address 60% of it and then slip 40% into a release, then have a conversation about whether it's actually "done" or not after it's lingered around for a while.
