### ISSUE TITLE
Book2 listing aarect not updated

### ISSUE THREAD

**Issue by oxine** [RayTracing/raytracing.github.io#477]
https://github.com/RayTracing/raytracing.github.io/blob/b54ce97423a4c68b4fc75b3a32cbe4a0a3e8c348/books/RayTracingTheNextWeek.html#L2013
https://github.com/RayTracing/raytracing.github.io/blob/b54ce97423a4c68b4fc75b3a32cbe4a0a3e8c348/books/RayTracingTheNextWeek.html#L2117
https://github.com/RayTracing/raytracing.github.io/blob/b54ce97423a4c68b4fc75b3a32cbe4a0a3e8c348/books/RayTracingTheNextWeek.html#L2136

`material*` should be `shared_ptr<material>`

**Comment by oxine** [comment]
https://github.com/RayTracing/raytracing.github.io/blob/b54ce97423a4c68b4fc75b3a32cbe4a0a3e8c348/books/RayTracingTheNextWeek.html#L2536

And here `hittable*` should be `shared_ptr<hittable>`

**Comment by hollasch** [comment]
Done.
