### ISSUE TITLE
 Missing the celling rect in listing[cornell-box-empty]

### ISSUE THREAD

**Issue by oxine** [RayTracing/raytracing.github.io#479]
https://github.com/RayTracing/raytracing.github.io/blob/51112291826e606047c6bbc3e0fadf3a2386ff73/books/RayTracingTheNextWeek.html#L2067

Here missing the celling rect
`objects.add(make_shared<xz_rect>(0, 555, 0, 555, 555, white));` in the very first cornell box code listing
There should be 6 rect including the light rect and here we've only got 5.

**Comment by hollasch** [comment]
Done.
