### ISSUE TITLE
Flipped Objects part in book 2 (remove `flip_face` class?)

### ISSUE THREAD

**Issue by oxine** [RayTracing/raytracing.github.io#482]
https://github.com/RayTracing/raytracing.github.io/blob/51112291826e606047c6bbc3e0fadf3a2386ff73/books/RayTracingTheNextWeek.html#L2054

I' ve noticed that we have already fliped the normal by `rec.set_face_normal` in `hit` function, the filp class seems to be useless.We may either remove the set normal function in `rect::hit` or remove the flip_face class.

**Comment by hollasch** [comment]
Yow. Excellent comment. A lot of work, but we didn't realize that we'd greatly simplified this part of the code. :)

**Comment by hollasch** [comment]
Putting this in the v3.1.0 milestone unless we decide otherwise.

**Comment by D-K-E** [comment]
I can also confirm that I was able to render cornell box without flip_face class and was quite surprised by not having the Empty Cornell box from listing 55.

**Comment by hollasch** [comment]
Note: see #270 for the original change that implemented proper ray-surface intersection from either side.
