### ISSUE TITLE
replace fabs with something

### ISSUE THREAD

**Issue by trevordblack** [RayTracing/raytracing.github.io#491]
TheNextWeek.html:1588-1595

replace fabs with whatever we typically use locally, ffabs? Make sure correct library is included somewhere

**Comment by hollasch** [comment]
Interesting. Five occurrences in the books, three in the source.

**Comment by hollasch** [comment]
Note that `fabs` and `ffabs` have different behavior, particularly around NaN.

**Comment by hollasch** [comment]
Ok, after thinking about this, I believe we should use `std::fmin` instead of defining our own `ffmin`, similarly for ffmax, and should continue to use the standard `fabs`. Doing perf runs shows no significant difference.
