### ISSUE TITLE
In One Weekend Chapter 8: displaced shadow from ideal Lamberatian sampling

### ISSUE THREAD

**Issue by halfhorst** [RayTracing/raytracing.github.io#493]
I'm looking at In One Weekend Version 3.0.2, 2020-04-11.

The ideal Lambertian sampling function in Chapter 8 is starting to perplex me but I can't tell if it's an issue with the book or on my end, I was hoping you may have some insight. I noted some discussion around this section in other issues as well.

I implemented all three methods for generating a bounce ray (that is, cos^3, cos and uniformly distributed) and the ideal Lambertian is giving me a biased shadow towards -x : 

![biased_shadow](https://user-images.githubusercontent.com/1770961/80057271-fcf6ef80-84da-11ea-891b-7a45c7914e4d.png) 

I can swap in the other two methods and get the correct behavior which is making me suspect the sampling method but it looks fine.. an equation of a circle in x and y with random displacement in z and a r set such that the vector is of unit length.  My random unit vector function (in C) looks like this :

```
Vec3 random_vector_on_unit_sphere() {
  float a = random_float(0, 2 * M_PI);
  float z = random_float(-1, 1);
  float r = sqrtf(1 - (z*z));
  Vec3 unit_vec = {.x=r*cosf(a), .y=r*sinf(a), .z=z};
  return unit_vec;
```

The text above that code (Listing 36) confuses me a bit, too: "Picking points on the sphere can be achieved by picking points in the unit ball, and then normalizing those". This description is what the code I'm referring to used to do, e.g. https://github.com/RayTracing/raytracing.github.io/commit/c4177a7c65e44f890f56f9af18e6b1b7eca924fd#diff-ac9a95c69808cd11a7a014188001f367L1340 but the method has changed. FWIW using that removed method also gives expected results

**Comment by trevordblack** [comment]
Not sure if this is your problem, but that function should be rewritten with y as the parameterizing variable:

```
vec3 random_unit_vector() {
    auto theta = random_double(0, 2*pi);
    auto y = random_double(-1, 1);
    auto circle_r = sqrt(1 - z*z);
    return vec3(circle_r*cos(theta), y, circle_r*sin(theta));
}
```

The idea is that you're slicing the sphere into horizontal circles, where y=[-1,1] chooses the y-plane,
and then theta chooses which part on the circle (the intersection of a plane and a sphere is a circle)

**Comment by halfhorst** [comment]
I like that parameterization, it's more clear, especially the variable naming. I think both should work, though. The equation of a sphere in Cartesian is the same w.r.t x, y and z, you can slice your circles along any axis. 

I found my issue, though, it's on my end. I was burned by C behavior. I was calling `random_float`, which takes no arguments, with a min and a max. I was just getting values in [0, 1), not my expected range 😪 

Thanks for taking a look.  Something for later - that passage around listing 36 still may be a little unclear.
