### ISSUE TITLE
Update source READMEs

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#494]
We currently have a readme file for each of the three source directories. Besides being out of date, they are largely copies of each other. We should instead have a single readme at the root of the source directory that goes over the source structure and CMake build system.

There's also the open question of whether the CMake build directory should be at the root of the project or under the `src/` directory.

**Comment by trevordblack** [comment]
CMake build directory should go in the same directory as the CMakeLists.txt

**Comment by trevordblack** [comment]
I honestly think that we should have only a single README. We just append to the one in root

**Comment by hollasch** [comment]
Yeah, that sounds good.

**Comment by hollasch** [comment]
Addressed in #631.
