### ISSUE TITLE
TheNextWeek: Ch. 4: Solid Textures - update sphere::hit() based on change to hit_record

### ISSUE THREAD

**Issue by shaunplee** [RayTracing/raytracing.github.io#496]
Chapter 4, skips over a bit, explaining how surface coordinates `(u,v)` are computed for a sphere.

In particular, Listing 20 updates `hit_record` to add surface coordinates `double u` and `double v`:

    struct hit_record {
      vec3 p;
      vec3 normal;
      shared_ptr<material> mat_ptr;
      double t;
      double u;
      double v;
      bool front_face;
      ...

Two dimensional coordinates (u,v) correspond to the location at which a ray hit the (2D) surface of an object (sphere).

Listing 21 then updates `scatter` to pass in the `rec.u` and `rec.v` values from `hit_record rec`:

            attenuation = albedo->value(rec.u, rec.v, rec.p);

However, Chapter 4 does not explain how coordinates `(u,v)` are calculated and set in the `hit_record`, presumably when `sphere::hit()` is called with an incoming ray.

Skipping ahead to Chapter 6, `get_sphere_uv()` in Listing 42 seems to solve this problem, which is what I eventually added to my `hit()` for my updates for Chapter 4 to compile. It produces a plausible result:

![checkeredFloor](https://user-images.githubusercontent.com/1076792/80450781-20ed7300-88d7-11ea-8893-472a28705b7c.png)

**Comment by shaunplee** [comment]
Looking more closely at the beginning of Chapter 6, maybe moving the part starting from the sentence:

> For a hittable, we need to also return a 𝑢 and 𝑣 in the hit record.

through Listing 42 from its current location in Chapter 6 to just after Listing 21 in Chapter 4 will address the issue.

Please let me know if this sounds appropriate, and I'll create a pull request accordingly.

**Comment by shaunplee** [comment]
This seems related to #441

**Comment by hollasch** [comment]
Sure, let's target `dev-minor` and we'll see what you have in mind.
