### ISSUE TITLE
Alot of errors Compilers on fedora, Seems to enterely the vec.h class

### ISSUE THREAD

**Issue by Digus12** [RayTracing/raytracing.github.io#503]
I get this error when compiling on linux:  

#pragma GCC diagnostic push
                            ^
In file included from ray.h:4,
                 from hittable.h:4,
                 from hittable_list.h:4,
                 from main.cpp:2:
vec3.h:3:12: note: to match this ‘{’
 class vec3 {
            ^
vec3.h: In constructor ‘vec3::vec3()’:
vec3.h:5:12: error: class ‘vec3’ does not have any field named ‘e’
   vec3() : e{0,0,0} {}
            ^
vec3.h: In constructor ‘vec3::vec3(double, double, double)’:
vec3.h:6:41: error: class ‘vec3’ does not have any field named ‘e’
   vec3(double e0,double e1,double e2) : e{e0,e1,e2}{}
                                         ^
vec3.h: In member function ‘double vec3::x() const’:
vec3.h:7:28: error: ‘e’ was not declared in this scope
   double x() const {return e[0];}
                            ^
vec3.h: In member function ‘double vec3::y() const’:
vec3.h:8:28: error: ‘e’ was not declared in this scope
   double y() const {return e[1];}
                            ^
vec3.h: In member function ‘double vec3::z() const’:
vec3.h:9:28: error: ‘e’ was not declared in this scope
   double z() const {return e[2];}
                            ^
vec3.h: In member function ‘vec3 vec3::operator-() const’:
vec3.h:11:39: error: ‘e’ was not declared in this scope
   vec3 operator-() const{return vec3(-e[0],-e[1].e[2];}
                                       ^
vec3.h: In member function ‘double vec3::operator[](int) const’:
vec3.h:12:44: error: ‘e’ was not declared in this scope
     double operator[](int i) const {return e[i];}
                                            ^
vec3.h: In member function ‘double& vec3::operator[](int)’:
vec3.h:13:39: error: ‘e’ was not declared in this scope
     double &operator[](int i) {return e[i];}
                                       ^
vec3.h: In member function ‘vec3 vec3::operator+=(const vec3&)’:
vec3.h:16:3: error: ‘e’ was not declared in this scope
   e[0] +v.e[0];
   ^
vec3.h:16:11: error: ‘const class vec3’ has no member named ‘e’
   e[0] +v.e[0];
           ^
vec3.h:17:11: error: ‘const class vec3’ has no member named ‘e’
   e[1]+=v.e[1];
           ^
vec3.h:18:11: error: ‘const class vec3’ has no member named ‘e’
   e[2]+=v.e[2];
           ^
vec3.h: In member function ‘vec3& vec3::operator/=(double)’:
vec3.h:29:16: error: no match for ‘operator*=’ (operand types are ‘vec3’ and ‘double’)
   return *this *= 1/t;
          ~~~~~~^~~~~~
vec3.h: In member function ‘double vec3::length() const’:
vec3.h:33:10: error: ‘sqrt’ was not declared in this scope
   return sqrt(length_squared());
          ^~~~
vec3.h:33:10: note: suggested alternative: ‘qsort’
   return sqrt(length_squared());
          ^~~~
          qsort
vec3.h: In member function ‘double vec3::length_squared() const’:
vec3.h:37:10: error: ‘e’ was not declared in this scope
   return e[0]*e[0] + e[1] * e[1] + e[2]*e[2];
          ^
vec3.h: In member function ‘void vec3::write_color(std::ostream&)’:
vec3.h:40:36: error: ‘e’ was not declared in this scope
   out << static_cast<int>(255.99 * e[0] << ' '
                                    ^
vec3.h:42:48: error: expected ‘)’ before ‘}’ token
         << static_cast<int>(255.00 *e[2] << ' '
                                                ^
                                                )
   }
   ~                                             
vec3.h:42:48: error: expected ‘)’ before ‘}’ token
         << static_cast<int>(255.00 *e[2] << ' '
                                                ^
                                                )
   }
   ~                                             
vec3.h:42:48: error: expected ‘)’ before ‘}’ token
         << static_cast<int>(255.00 *e[2] << ' '
                                                ^
                                                )
   }
   ~                                             
vec3.h: In member function ‘double vec3::dot(const vec3&, const vec3&)’:
vec3.h:77:14: error: ‘const class vec3’ has no member named ‘e’
     return u.e[0] * v.e[0]
              ^
vec3.h:77:23: error: ‘const class vec3’ has no member named ‘e’
     return u.e[0] * v.e[0]
                       ^
vec3.h:78:14: error: ‘const class vec3’ has no member named ‘e’
          + u.e[1] * v.e[1]
              ^
vec3.h:78:23: error: ‘const class vec3’ has no member named ‘e’
          + u.e[1] * v.e[1]
                       ^
vec3.h:79:14: error: ‘const class vec3’ has no member named ‘e’
          + u.e[2] * v.e[2];
              ^
vec3.h:79:23: error: ‘const class vec3’ has no member named ‘e’
          + u.e[2] * v.e[2];
                       ^
vec3.h: In member function ‘vec3 vec3::cross(const vec3&, const vec3&)’:
vec3.h:83:19: error: ‘const class vec3’ has no member named ‘e’
     return vec3(u.e[1] * v.e[2] - u.e[2] * v.e[1],
                   ^
vec3.h:83:28: error: ‘const class vec3’ has no member named ‘e’
     return vec3(u.e[1] * v.e[2] - u.e[2] * v.e[1],
                            ^
vec3.h:83:37: error: ‘const class vec3’ has no member named ‘e’
     return vec3(u.e[1] * v.e[2] - u.e[2] * v.e[1],
                                     ^
vec3.h:83:46: error: ‘const class vec3’ has no member named ‘e’
     return vec3(u.e[1] * v.e[2] - u.e[2] * v.e[1],
                                              ^
vec3.h:84:19: error: ‘const class vec3’ has no member named ‘e’
                 u.e[2] * v.e[0] - u.e[0] * v.e[2],
                   ^
vec3.h:84:28: error: ‘const class vec3’ has no member named ‘e’
                 u.e[2] * v.e[0] - u.e[0] * v.e[2],
                            ^
vec3.h:84:37: error: ‘const class vec3’ has no member named ‘e’
                 u.e[2] * v.e[0] - u.e[0] * v.e[2],
                                     ^
vec3.h:84:46: error: ‘const class vec3’ has no member named ‘e’
                 u.e[2] * v.e[0] - u.e[0] * v.e[2],
                                              ^
vec3.h:85:19: error: ‘const class vec3’ has no member named ‘e’
                 u.e[0] * v.e[1] - u.e[1] * v.e[0]);
                   ^
vec3.h:85:28: error: ‘const class vec3’ has no member named ‘e’
                 u.e[0] * v.e[1] - u.e[1] * v.e[0]);
                            ^
vec3.h:85:37: error: ‘const class vec3’ has no member named ‘e’
                 u.e[0] * v.e[1] - u.e[1] * v.e[0]);
                                     ^
vec3.h:85:46: error: ‘const class vec3’ has no member named ‘e’
                 u.e[0] * v.e[1] - u.e[1] * v.e[0]);
                                              ^
vec3.h: In member function ‘vec3 vec3::unit_vector(vec3)’:
vec3.h:89:14: error: no match for ‘operator/’ (operand types are ‘vec3’ and ‘double’)
     return v / v.length();
            ~~^~~~~~~~~~~~
In file included from /usr/include/c++/8/memory:80,
                 from hittable_list.h:5,
                 from main.cpp:2:
/usr/include/c++/8/bits/unique_ptr.h: At global scope:
/usr/include/c++/8/bits/unique_ptr.h:51:28: error: expected unqualified-id before end of line
 #pragma GCC diagnostic push

What am i missing here?

**Comment by hollasch** [comment]
Don't know, but it's likely due to the C++ variant or some platform details. Let us know when you find out the issue, and if there are generic changes that we might make to address this.

Also keep in mind that the intent of the books is to guide you in writing your own ray tracer, so that's another approach you might consider. Set things up your own way, and let the books guide you along the path of implementing the code as you see fit.

**Comment by D-K-E** [comment]
@Digus12 Just a quick suggestion: I have been using [glm](https://glm.g-truc.net/0.9.9/index.html) as a vector library to interface easily with opengl later. If it compiles under fedora, you can alias `dvec3` to `vec3` and other related class, and write couple of wrappers to follow the text ?

**Comment by hollasch** [comment]
Never heard back.
