### ISSUE TITLE
Book 1: 11.2 seems to refer to the variable `vup` in the code before defining it

### ISSUE THREAD

**Issue by LesleyLai** [RayTracing/raytracing.github.io#523]
The book mentions that "use world up `(0,1,0)` to specify `vup`". But in the following code snippet, `vup` is used in the line

```cpp
camera cam(point3(-2,2,1), point3(0,0,-1), vup, 90, aspect_ratio);
```
without any previous definition. It should be a little bit clearer if the code is changed into

```cpp
camera cam(point3(-2,2,1), point3(0,0,-1), vec3(0,1,0), 90, aspect_ratio);
```

**Comment by hollasch** [comment]
Resolved in #537
