### ISSUE TITLE
lambertian scatter_direction computation 

### ISSUE THREAD

**Issue by JensDerKrueger** [RayTracing/raytracing.github.io#530]
Instead of

vec3 scatter_direction = rec.normal + random_unit_vector();

it should be 

vec3 scatter_direction = rec.normal + random_in_unit_sphere();

to get the proper cosine normal distribution for a diffuse material

**Comment by apichlkostner** [comment]
At least in the newer versions of the book the random_in_unit_sphere() was replaced by random_unit_vector() for lambertian reflection in chapter 8.5.
It turned out that random_in_unit_sphere() gives a cos³ distribution.

**Comment by JensDerKrueger** [comment]
Thanks for the response, I checked the latest version of the book and indeed found Pete's comments about this change. He doesn't provide a derivation of the cos³ argument. Since I thought I'd understood the reason why his initial distribution is a correct cos-distribution I'd be very interested in reading the derivation of the cos³ argument to see what's wrong with my "proof". Do you have access to that derivation?

**Comment by apichlkostner** [comment]
I'm just learning with this book and I'm not part of the team.
But I thought about that problem and found a reason why it's cos³ and added it to my repositories readme.
[https://github.com/apichlkostner/Pathtracer](https://github.com/apichlkostner/Pathtracer)

**Comment by JensDerKrueger** [comment]
Great thanks, I simply computed that the length of the line 2*cos(theta) and stopped there, but of course you are right, I should have looked at the volume instead of the just the length.

**Comment by trevordblack** [comment]
The person who pointed out the error also provided a derivation:

https://github.com/vchizhov/Derivations/blob/master/Probability%20density%20functions%20of%20the%20projected%20offset%20disk%2C%20circle%2C%20ball%2C%20and%20sphere.pdf

The person who would be integrating the derivation into the text is me, and if you read through the derivation, it's outside the scope of the first book.

And, ha! "Pete's comments about this change" are actually my comments! I've put in effort to try and match his "voice" in my edits. So, if the comments were at least not jarring, I'll take that as a victory!

**Comment by trevordblack** [comment]
Is this a satisfactory summary? I'm interested in closing out this issue.

**Comment by JensDerKrueger** [comment]
yes, I am. thanks for getting back to me, I simply forgot to close the issue
