### ISSUE TITLE
Book 2: 7.6/7.7 Cornell Box & Flipped Objects Question

### ISSUE THREAD

**Issue by hackmad** [RayTracing/raytracing.github.io#531]
I've read through both Book 1 and 2 a couple times and I might have missed something obvious that seems unclear to me. I do not see how the render of the Empty Cornell Box in 7.6 resulted in 3 of the faces rendering with black colour. 

Looking at the Lambertian material it does not care about front_face and returns an attenuation regardless of this flag. I get the same result whether I use the flipped object or not.

I'm working in Rust (using this as a means to learn both) so it is quite possible something is off. This is the render I get:

![image](https://user-images.githubusercontent.com/19393946/81757398-c5051b80-948c-11ea-91db-f48636665685.png)

I've tried adding Flipped Objects as well but it does not change the result.

Not that this is a good reference but if it helps my implementation is here: https://github.com/hackmad/raytracing_series

**Comment by hollasch** [comment]
Thanks for reporting (and confirming suspicions). This is covered in issue #482.
