### ISSUE TITLE
`get_sphere_uv` does not correspond to its explanation

### ISSUE THREAD

**Issue by D-K-E** [RayTracing/raytracing.github.io#533]
The function `get_sphere_uv` in NextWeek listing 42 at section Texture 6.1, is given as 
```c++
void get_sphere_uv(const point3& p, double& u, double& v) {
    auto phi = atan2(p.z(), p.x());
    auto theta = asin(p.y());
    u = 1-(phi + pi) / (2*pi);
    v = (theta + pi/2) / pi;
}
```
whereas in the formula given in the explanation is:

```
To compute θ and ϕ, for a given hitpoint, the formula for 
spherical coordinates of a unit radius sphere on the origin is:

x=cos(ϕ)cos(θ)
y=sin(ϕ)cos(θ)
z=sin(θ)

We need to invert that. Because of the lovely <cmath> 
function atan2() (which takes any number proportional 
to sine and cosine and returns the angle), we can pass in x
and y (the cos(θ) cancel):

ϕ=atan2(y,x)

The atan2
returns values in the range −π to π, so we need to 
take a little care there. The θ is more straightforward:

θ=asin(z)

which returns numbers in the range −π/2
to π/2. 
```
The problem also exist in `dev-major` branch.

**Comment by hollasch** [comment]
Thanks for reporting! If you would like, feel free to submit a pull request of your suggested changes to the `dev-patch` branch.

**Comment by D-K-E** [comment]
Sure, very solid work by the way. I am also porting the Weekend version to opengl with compute shaders in [here](https://github.com/D-K-E/raytracing-gl)

**Comment by D-K-E** [comment]
The PR that was suppose to change the code for implementing the formula above is closed now, because most of the sources I have cited there favor the existing implementation. The wording in this section might be improved to show how we arrive to the implementation of `get_sphere_uv` function, instead of using unit sphere at origin to represent the problem.

**Comment by trevordblack** [comment]
Suggest punting to 3.2
