### ISSUE TITLE
Figure notation update: fig-1.02-lerp

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#538]
Vector should be lowercase *b*, no barb.

File: `fig.lerp.jpg`

**Comment by hollasch** [comment]
Renamed to `images/fig-1.02-lerp.jpg`.

**Comment by trevordblack** [comment]
Fixed with commit https://github.com/RayTracing/raytracing.github.io/commit/2c7c95960729d18222f1976f7b8416bfd2971ee9
