### ISSUE TITLE
Figure notation update: fig-1.11-reflection - ray reflection

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#541]
- Normal **n** should be lowercase
- Vector **b** should be lowercase

File: `fig.ray-reflect.jpg`

**Comment by hollasch** [comment]
Renamed to `images/fig-1.11-reflection.jpg`.

**Comment by trevordblack** [comment]
Completed with commit https://github.com/RayTracing/raytracing.github.io/commit/8cca6a0addb04e2abc7ad957bc8e4d5379421801?short_path=9b539ac#diff-9b539ac31c537d3813ac527337566a900a3346a58bfab37eca02e9cbda64fff3
