### ISSUE TITLE
Next week: Instance rotation on y axis does not match the formula in hit function

### ISSUE THREAD

**Issue by D-K-E** [RayTracing/raytracing.github.io#544]
The formula for rotating about y axis is given as:
```
Similarly, for rotating about y (as we want to do for the blocks in the box) 
the formulas are:
x′=cos(θ)⋅x+sin(θ)⋅z
z′=−sin(θ)⋅x+cos(θ)⋅z
```

Its application by the `hit` function:
```c++
origin[0] = cos_theta*r.origin()[0] - sin_theta*r.origin()[2];
origin[2] = sin_theta*r.origin()[0] + cos_theta*r.origin()[2];
direction[0] = cos_theta*r.direction()[0] - sin_theta*r.direction()[2];
direction[2] = sin_theta*r.direction()[0] + cos_theta*r.direction()[2];
...
p[0] =  cos_theta*rec.p[0] + sin_theta*rec.p[2];
p[2] = -sin_theta*rec.p[0] + cos_theta*rec.p[2];
normal[0] =  cos_theta*rec.normal[0] + sin_theta*rec.normal[2];
normal[2] = -sin_theta*rec.normal[0] + cos_theta*rec.normal[2];
```

The `origin` and `direction` follows the formula for rotating about z axis:
```
The result for rotating counter-clockwise about z is:
x′=cos(θ)⋅x−sin(θ)⋅y
y′=sin(θ)⋅x+cos(θ)⋅y
```

**Comment by trevordblack** [comment]
Simply changing `rotate_y` to:

```
origin[0] =  cos_theta*r.origin()[0] + sin_theta*r.origin()[2];
origin[2] = -sin_theta*r.origin()[0] + cos_theta*r.origin()[2];
direction[0] =  cos_theta*r.direction()[0] + sin_theta*r.direction()[2];
direction[2] = -sin_theta*r.direction()[0] + cos_theta*r.direction()[2];
...
p[0] =  cos_theta*rec.p[0] + sin_theta*rec.p[2];
p[2] = -sin_theta*rec.p[0] + cos_theta*rec.p[2];
normal[0] =  cos_theta*rec.normal[0] + sin_theta*rec.normal[2];
normal[2] = -sin_theta*rec.normal[0] + cos_theta*rec.normal[2];
```

Produces incorrect results. With the red diffuse showing up on the wrong side of the cube (likewise for green).
I don't remember exactly, but i'm pretty sure the source is correct as written.
Maybe something to do with rotating the world coordinates in the reverse of the object coordinates...

**Comment by trevordblack** [comment]
Following up.

This is the code for rotate_y::hit:
```
bool rotate_y::hit(const ray& r, double t_min, double t_max, hit_record& rec) const {
    auto origin = r.origin();
    auto direction = r.direction();

    origin[0] = cos_theta*r.origin()[0] - sin_theta*r.origin()[2];
    origin[2] = sin_theta*r.origin()[0] + cos_theta*r.origin()[2];

    direction[0] = cos_theta*r.direction()[0] - sin_theta*r.direction()[2];
    direction[2] = sin_theta*r.direction()[0] + cos_theta*r.direction()[2];

    ray rotated_r(origin, direction, r.time());

    if (!ptr->hit(rotated_r, t_min, t_max, rec))
        return false;

    auto p = rec.p;
    auto normal = rec.normal;

    p[0] =  cos_theta*rec.p[0] + sin_theta*rec.p[2];
    p[2] = -sin_theta*rec.p[0] + cos_theta*rec.p[2];

    normal[0] =  cos_theta*rec.normal[0] + sin_theta*rec.normal[2];
    normal[2] = -sin_theta*rec.normal[0] + cos_theta*rec.normal[2];

    rec.p = p;
    rec.set_face_normal(rotated_r, normal);

    return true;
}
```

This code can be summarized as:
```
bool rotate_y::hit(const ray& r, double t_min, double t_max, hit_record& rec) const {
    // figure out if we hit rotated object
    // if NOT hit
    //   return false
    // if hit
    //   Determine where the intersection is
    //   return true
}
```

The code that you thought was erroneous:
```
    auto origin = r.origin();
    auto direction = r.direction();

    origin[0] = cos_theta*r.origin()[0] - sin_theta*r.origin()[2];
    origin[2] = sin_theta*r.origin()[0] + cos_theta*r.origin()[2];

    direction[0] = cos_theta*r.direction()[0] - sin_theta*r.direction()[2];
    direction[2] = sin_theta*r.direction()[0] + cos_theta*r.direction()[2];

    ray rotated_r(origin, direction, r.time());

    if (!ptr->hit(rotated_r, t_min, t_max, rec))
        return false;
```

Is really just the code to determine if an intersection occurs.
`origin` and `direction` start the function in "world space".
`ptr->hit` checks to see if a ray is in "object space".

In order for `ray rotated_r(origin, direction, r.time());` to identify true intersections, the ray `rotated_r` needs to be in "object space"

That means we need to convert `origin` and `direction` to object space.
If the mapping from "object space" to "world space" is
```
x′=cos(θ)⋅x+sin(θ)⋅z
z′=−sin(θ)⋅x+cos(θ)⋅z
```
Then the inverse mapping from "world space" to "object space" is
```
```
x=cos(θ)⋅x'+sin(θ)⋅z'
z=−sin(θ)⋅x'+cos(θ)⋅z'
```

Later in the function:
```
    auto p = rec.p;
    auto normal = rec.normal;

    p[0] =  cos_theta*rec.p[0] + sin_theta*rec.p[2];
    p[2] = -sin_theta*rec.p[0] + cos_theta*rec.p[2];

    normal[0] =  cos_theta*rec.normal[0] + sin_theta*rec.normal[2];
    normal[2] = -sin_theta*rec.normal[0] + cos_theta*rec.normal[2];

    rec.p = p;
    rec.set_face_normal(rotated_r, normal);

    return true;
```

`rec.p` and `rec.normal` are in "object space". They need to be in "world space". So we apply the object2world transformation:
```
   p[0] =  cos_theta*rec.p[0] + sin_theta*rec.p[2];
    p[2] = -sin_theta*rec.p[0] + cos_theta*rec.p[2];

    normal[0] =  cos_theta*rec.normal[0] + sin_theta*rec.normal[2];
    normal[2] = -sin_theta*rec.normal[0] + cos_theta*rec.normal[2];
```

where we finally have `rec.p` and `rec.normal` in the correct world space, and we can move on with our ray traversal.

The source as written is correct, but the test does not have any of the above explanation.
Hence the confusion.

It might be a good idea to add this explanation to the text, but I would suggest that it might be outside of 3.2.0
@hollasch Thoughts?

**Comment by hollasch** [comment]
Yes, it would be good to add an explanation, but I agree that it should be post v3.2.0.

**Comment by trevordblack** [comment]
@hollasch 

Am I owning this or are you?
I know that you're interested in overhauling transforms.

If you write the source I can write the text?
I can also do both.

**Comment by trevordblack** [comment]
@D-K-E can you look over the fix in PR #913

**Comment by D-K-E** [comment]
Yes looking at it right now

**Comment by D-K-E** [comment]
It looks much more clear.

**Comment by trevordblack** [comment]
Closing out this issue, thanks for this one

**Comment by 543877815** [comment]
@trevordblack Thanks for good explanations!!
