### ISSUE TITLE
The Rest: Listing 12, superfluous addition and subtraction rec.p

### ISSUE THREAD

**Issue by D-K-E** [RayTracing/raytracing.github.io#604]
Listing 12 of the book The Rest of Your Life contains a superfluous addition and subtraction operation for hit record point in the lambertian scattering method. It is given as:
```c++
        virtual bool scatter(...) const {
            point3 target = rec.p + rec.normal + random_unit_vector();
            scattered = ray(rec.p, unit_vector(target-rec.p), r_in.time());
            ...
        }
```
I think what is being intended is
```c++
point3 target = rec.normal + random_unit_vector();
scattered = ray(rec.p, unit_vector(target), r_in.time());
```
which avoids adding and subtracting the `rec.p`.

**Comment by hollasch** [comment]
Hey! Just realized I haven't added you to the acknowledgements (your feedback is very useful). Can you email me your name so I can include it? → steve@hollasch.net.
