### ISSUE TITLE
The Rest: to_light.make_unit_vector is not defined anywhere

### ISSUE THREAD

**Issue by D-K-E** [RayTracing/raytracing.github.io#606]
The Rest: listing 20 contains a method `make_unit_vector` which is not defined anywhere.
Probably `unit_vector` function is intended from `vec3.h`. 
The problem persists in dev-major/minor/patch branches as well.

**Comment by hollasch** [comment]
Messed up and made correction directly on `dev-patch` (no PR). Corrected in e46df5951d00aaf7f7a3d6949c66d9b8d567813c
