### ISSUE TITLE
[In one Weekend] cam::get_ray input parameters sudden change

### ISSUE THREAD

**Issue by mratsim** [RayTracing/raytracing.github.io#616]
Looking into the camera implementation, the initial parameters where u, v and they changed to s, t without highlighting.

I assume they were supposed to be u, v to keep in line with the figures and s, t was a leftover from a previous change.

![image](https://user-images.githubusercontent.com/22738317/82730305-ee307200-9cfe-11ea-89eb-bcb0f5a5f919.png)
![image](https://user-images.githubusercontent.com/22738317/82730312-f7214380-9cfe-11ea-84bb-7faa4f7c4ee1.png)

**Comment by hollasch** [comment]
Thank you. Yes, I actually noticed (and have a correction for this) yesterday, when I went through the entire book. Lots of little mistakes to be fixed in book 1, including this one.

Keeping this one open, as I haven't created separate issues for the problems I've encountered.

**Comment by hollasch** [comment]
Resolved in PR #625
