### ISSUE TITLE
True up the nomenclature with the final code, which uses a switch statement with 10 different scene numbers.

### ISSUE THREAD

**Issue by trevordblack** [RayTracing/raytracing.github.io#620]
We should also true up the nomenclature with the final code, which uses a switch statement with 10 different scene numbers.

_Originally posted by @hollasch in https://github.com/RayTracing/raytracing.github.io/issues/325#issuecomment-633160872_

**Comment by hollasch** [comment]
This is ongoing with the current progression task rolling through book 2.

**Comment by trevordblack** [comment]
With the exception of the explicit `cornell_smoke` as `case 7:`, the code in the source and the in-line source in text are very similar (after #643).
Close this issue?

**Comment by hollasch** [comment]
No, we need to get this synchronized. I'll re-render `cornell_balls` to see if it's a worthy image. If not, we can just remove it completely in the code. If it's useful, we'll add text to explain it. Similarly for `cornell_final`.

`cornell_smoke` just needs the case in the text.

**Comment by hollasch** [comment]
Ref #650, #653
