### ISSUE TITLE
Section 4.3 PrematureColor Class References RayTracingTheNextWeek

### ISSUE THREAD

**Issue by Mluckydwyer** [RayTracing/raytracing.github.io#622]
There seem to be premature `color` type references made when transitioning to implementing textures. I am following along and up until this point we have utilized `vec3`s to implement the RGB normalized values to represent a color, thus the code would read `...make_shared<lambertian>(vec3(0.5, 0.5, 0.5))` in **Listing 24** in the `main.cc` for instance. This is confusing since it looks like the color header is later implemented (referring to the repo common directory). It also causes my IDE ti light up since it cannot find the implementation of `color` anywhere. Am I missing something?

**Comment by hollasch** [comment]
`color` is a `using`-style alias for `vec3`, defined in `src/common/vec3.h`. Since `using`s are not a strong typedef, you should be free to use `vec3` wherever you see `point3` or `color`, if that's your preference.

**Comment by Mluckydwyer** [comment]
Ahh I now see. I must have missed those declarations in **Listing 4** in section 3.1 of InOneWeekend when I went through that. Apologies

**Comment by Mluckydwyer** [comment]
Or actually, there must have been an update since I completed the first book, since looking back the current source seems to match the book but my source seems to implement the old `vec3` implementation throughout. I appreciate your assistance.

**Comment by hollasch** [comment]
Yeah, we've been making a lot of changes. Good to improve the project, bad for folks in the middle of things. A hard line to walk. We do all development in isolated dev branches, so what's online is cohesive, but you may still want to rely primarily on the book and code in your own local clone, so you're not randomized.
