### ISSUE TITLE
Compilation error in Listing 26 for generating random numbers. 

### ISSUE THREAD

**Issue by yehaixuan4428** [RayTracing/raytracing.github.io#626]
Should it be 
```
distribution(generator)
```
instead of 
```
generator(distribution)
```
Reference : https://en.cppreference.com/w/cpp/numeric/random/uniform_real_distribution

**Comment by hollasch** [comment]
YES! I found and fixed this in an experimental branch, but forgot to commit this fix. Thank you for reporting it.

**Comment by hollasch** [comment]
Never mind -- I _did_ create an issue for this: #621
