### ISSUE TITLE
[The Next Week] [Typo] Chapter 8.1 "Intance" should be "Instance"

### ISSUE THREAD

**Issue by manas96** [RayTracing/raytracing.github.io#629]
I would like to make the change. Do I make a PR against `dev-minor` ?

**Comment by trevordblack** [comment]
1. Make a branch off of dev-minor
2. Make change
3. Make PR against dev-minor
4. Be sure to add the change to the CHANGELIST
5. Would you like to be added to the acknowledgments section?

If you need help with any of this feel free to ask

**Comment by manas96** [comment]
Done. Yes, I would like to be added to the acknowledgments.
