### ISSUE TITLE
Book 2 correction and phrase clarity, 5.5 Lattice Points and 8.2 Instance Rotation

### ISSUE THREAD

**Issue by okaneco** [RayTracing/raytracing.github.io#657]
#### Section 5.5 - Using Random Vectors on the Lattice Points

https://github.com/RayTracing/raytracing.github.io/blob/ce85fe59ce089b38adcae650cb2c762b9b50e1d3/books/RayTracingTheNextWeek.html#L1577-L1579

I believe `interpretation` is meant to be `interpolation`, and that `Perlin` should be capitalized in both instances here.

Should the last sentence instead be "We will scale the Perlin output to be between 0 and 1."? I don't really see it as casting.  
The code being referred to:
```cpp
        virtual color value(double u, double v, const point3& p) const {
            return color(1,1,1) * 0.5 * (1.0 + noise.noise(scale * p));
        }
```

#### Section 8.2 - Instance rotation

I'm not sure if the second sentence is missing a period, it's a bit of a run-on sentence. "That gives you the correct impression" can probably be omitted. https://github.com/RayTracing/raytracing.github.io/blob/ce85fe59ce089b38adcae650cb2c762b9b50e1d3/books/RayTracingTheNextWeek.html#L2420-L2422

---

Thank you for the books, I've really enjoyed the series and hope to continue further learning. I've completed it in Rust and saved images of each scene along the way.
https://github.com/okaneco/rtiow

**Comment by hollasch** [comment]
Thank you for the suggestions; good ideas. Regarding the uses of `perlin`, I think the text is referring to the _function_, not the person. Still, you're right that it could be cleaned up for clarity.
