### ISSUE TITLE
RestOfYourLife: 12.2 image not possible before going further in the book

### ISSUE THREAD

**Issue by Walther** [RayTracing/raytracing.github.io#658]
Thank you for the absolutely fantastic tutorial series! This has been a joy to follow ❤

In RestOfYourLife chapter 12 Cleaning Up PDF Management, with the new `scatter_record` structs and using the new pdf pointers, the image `Cornell box with arbitrary PDF functions` cannot be rendered. When passing in a `HitableList` of a single light to the `ray_color` as `lights`, you'll end up with a mostly-black image except for the light itself.
![1594018737](https://user-images.githubusercontent.com/2943750/86566766-e0634300-bf72-11ea-9498-d2aec811c493.png)

After a couple of hours of debugging, i noticed that in chapter `12.5 Adding PDF Functions to Hittable Lists` there are `pdf_value` and `random` implementations added for `HitableList`. Adding these to my code with no other changes results in a picture as expected:
![1594020479](https://user-images.githubusercontent.com/2943750/86567179-929b0a80-bf73-11ea-95fa-c6b399d88ddf.png)

In addition to bumping into this in my Rust implementation, I was able to replicate this by commenting out the relevant lines in `hitable_list.h` in the repository and making a render.

**Comment by trevordblack** [comment]
Noted. Going into v3.3.0

We're going to be ripping book 3 inside-out.

So, if you've got anything else, shout 'em out.
Thanks

**Comment by hollasch** [comment]
As a side note, in the past month or so we've been going through books 1 and 2 step-by-step, following the text. We were chagrined to find buckets of issues, many which slipped in as we've been reworking things. All this to say that I'm inclined to think you're correct; sorry about the headache. We'll be reworking this in the next minor/major release.

**Comment by trevordblack** [comment]
I'm going to go ahead and close out this issue. If it comes back up, we'll whack it when rendering the book 3 images again.
