### ISSUE TITLE
FlipFace issues

### ISSUE THREAD

**Issue by Walther** [RayTracing/raytracing.github.io#661]
In Book 2 (the published version) there is [a chapter](https://raytracing.github.io/books/RayTracingTheNextWeek.html#rectanglesandlights/flippedobjects) on flipping objects. With the other improvements and changes that have been made to the tutorial, it apparently isn't necessary anymore; the first attempt of Cornell box renders correctly with all faces visible. (This caused some extra debugging - "why does this work even if it shouldn't yet?")

Apparently, in https://github.com/RayTracing/raytracing.github.io/pull/602, the relevant parts have been already removed, but the published version online still has it. That part could be easily fixed by doing a publish some day when the new version is complete.

However! In Book 3, the flipface usage is reintroduced in order to make the rectangle-shaped light one-sided, to avoid bleed-through in the ceiling. Currently, Book 3 has no code for it. When the currently-merged version of Book 2 gets published, there will be no place for a reader to find the flip face methods. Perhaps a tiny remark, but something that occurred to me 😄

**Comment by hollasch** [comment]
Youch! Didn't catch that problem. We'll have to at least add a note for v3.2.0, and hopefully fix this up in v3.3.0 or later.

**Comment by trevordblack** [comment]
I'm splitting this into two issues:
1. Removing Chapter 7.7 from book 2 AND giving an example flipface source for chapter 3. We don't need something pretty here, but I'm going to demand that we have the source (this issue).
2. Rewriting Book3 to allow for flipface when flipping the light (#662)

**Comment by trevordblack** [comment]
I'm actually going to renege on my own demands.
I'm going to drop the source for `flip_face` into the text of book 3, but I'm not going to explain how it's used or where it goes.

Quite frankly, the source in Book 3 needs a lot of work before an explanation is possible.
PR incoming

**Comment by trevordblack** [comment]
Okay, I lied. I figured it out literally seconds later.
PR incommmming....
