### ISSUE TITLE
Address `material::scatter()` function mismatch between book and source

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#669]
- Book two has a `material::scatter()` method that takes four arguments.
- Book three text has a `material::scatter()` method that adds a fifth argument.
- Book three _source_ has a `material::scatter()` method that takes three arguments.

Also note that the original `isotropic::scatter()` method in book three took four arguments, so the source code was actually invoking the default `material::scatter()` method, so that image is probably wrong.

**Comment by trevordblack** [comment]
This can probably be closed out with the merge of #885
