### ISSUE TITLE
Sometimes renders in wrong order: closest_so_far is not utilized

### ISSUE THREAD

**Issue by awarebayes** [RayTracing/raytracing.github.io#671]
Hi, I've spotted an error in the renderer code which caused it to render it in the wrong order (i.e. Z-buffer was mixed).
Without checking closest_so_far it renders the objects in the order they were added to the vector.

Where:
6.5 A List of Hittable Objects
Listing 20: [hittable_list.h] The hittable_list class

Wrong:
```
auto closest_so_far = t_max;

for (const auto& object : objects) {
    if (object->hit(r, t_min, closest_so_far, temp_rec)) {
     ...
    }
}
```

Right:
```
auto closest_so_far = t_max;
for (const auto& object : objects) {
    if (object->hit(r, t_min, closest_so_far, temp_rec)) && temp_rec.t < closest_so_far {
     ...
    }
}
```
For instance if you push the big sphere first the following result is produced:
```
world.add(make_shared<sphere>(point3(0,-100.5,-1), 100));
world.add(make_shared<sphere>(point3(0,0,-1), 0.5));
```
![image](https://user-images.githubusercontent.com/42784580/87685761-6dd13f00-c78c-11ea-95d6-fd05dfd40c07.png)

With fix, it works the way intended:
![image](https://user-images.githubusercontent.com/42784580/87686068-c1dc2380-c78c-11ea-90fe-311b60ba4fc0.png)

**Comment by trevordblack** [comment]
The check to see if an object is before closest_so_far is in the hittable class.

Did you forget to check against `t_max` in
```
bool sphere::hit(const ray& r, double t_min, double t_max, hit_record& rec) const {
    vec3 oc = r.origin() - center;
    auto a = r.direction().length_squared();
    auto half_b = dot(oc, r.direction());
    auto c = oc.length_squared() - radius*radius;
    auto discriminant = half_b*half_b - a*c;

    if (discriminant > 0) {
        auto root = sqrt(discriminant);
        auto temp = (-half_b - root)/a;
        if (temp < t_max && temp > t_min) {
            rec.t = temp;
            rec.p = r.at(rec.t);
            vec3 outward_normal = (rec.p - center) / radius;
            rec.set_face_normal(r, outward_normal);
            return true;
        }
        temp = (-half_b + root) / a;
        if (temp < t_max && temp > t_min) {
            rec.t = temp;
            rec.p = r.at(rec.t);
            vec3 outward_normal = (rec.p - center) / radius;
            rec.set_face_normal(r, outward_normal);
            return true;
        }
    }
    return false;
}
```

There may be an error here, but I'm failing to reproduce it on the latest version of `dev-minor`

**Comment by awarebayes** [comment]
Sorry, my bad!
