### ISSUE TITLE
Mention changes to Dielectric in The Rest of Your Life?

### ISSUE THREAD

**Issue by browserdotsys** [RayTracing/raytracing.github.io#674]
In The Rest of Your Life section 12.4, the text doesn't mention that there are also changes to Dielectric needed to support `scatter_record`. The changes needed are very small (and can be found in the source) but this tripped me up briefly since I had implemented PDF-based scattering as a new method with a default implementation rather than replacing `scatter`, with the result that the Dielectric class fell back on producing vec3(0,0,0).

PS: Thanks for the books! It was a very fun way to [learn a new language](https://github.com/browserdotsys/vecchio).

**Comment by hollasch** [comment]
Related: #669
