### ISSUE TITLE
Need Source Code README

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#68]
- [x] In One Weekend
- [x] The Next Week
- [x] The Rest Of Your Life

**Comment by trevordblack** [comment]
What do we want in this source code readme?

I'm not sure what that we could add of value that isn't a build system. And, at least for v2, we're not including one of those.

**Comment by hollasch** [comment]
Fixed in PR https://github.com/RayTracing/raytracing.github.io/pull/172
