### ISSUE TITLE
Bug: rect hit returning NaN's, Infinities

### ISSUE THREAD

**Issue by Walther** [RayTracing/raytracing.github.io#681]
https://github.com/RayTracing/raytracing.github.io/blob/7b92650a045a887391bf8148af86c5e6c46c7a9e/src/TheRestOfYourLife/aarect.h#L124-L126
If `r.direction().y()` happens to be zero, you'll get `t=infinity`. This infinity will get passed along, because `infinity > infinity` is `false` so the `if` branch is not taken.

Additionally, if `k-r.origin().y()` happens to be `0` as well, you'll get `0.0 / 0.0` resulting in a `NaN` that again gets passed along.

This exists in all three cases of `rect`, with different axes being the culprit.

Caveat emptor: I bumped into this in my Rust implementation, so some specific details may be slightly different, including in case infinity & NaN semantics are slightly different in C++. But I _think_ this should be applicable.

---
_Offtopic sidenote: wonder if it would be worth it to make the distance be named something else than `t`, considering some other functions in the book use `t` or `t0, t1` for time_

**Comment by hollasch** [comment]
Regarding the side note: see #678

**Comment by hollasch** [comment]
See #756

**Comment by hollasch** [comment]
Fixed in ed119afc11dab9bd912d0c2872fbd780c0909f8c
