### ISSUE TITLE
Book2: Listing 29: include rtweekend.h

### ISSUE THREAD

**Issue by estshorter** [RayTracing/raytracing.github.io#691]
`rtweekend.h` should be included as it uses `random_double`.

**Comment by rjkilpatrick** [comment]
It is missing from the book source,
https://github.com/RayTracing/raytracing.github.io/blob/7b92650a045a887391bf8148af86c5e6c46c7a9e/books/RayTracingTheNextWeek.html#L1422-L1425

But can be found in the `src` directory:
https://github.com/RayTracing/raytracing.github.io/blob/7b92650a045a887391bf8148af86c5e6c46c7a9e/src/common/perlin.h#L1-L18

It's also needed for `point3` class etc.
I can submit a PR if needed
