### ISSUE TITLE
Book1 Diffuse text is confusing

### ISSUE THREAD

**Issue by yig** [RayTracing/raytracing.github.io#696]
The text around the correct cos(𝜙) distribution is confusing. Sections 8.6 "An Alternative Diffuse Formulation" and 8.5 "True Lambertian Reflection" both seem to me to be correcting Section 8.1 "A Simple Diffuse Material" by claiming to describe a correct cos(𝜙) distribution. However, the pictures aren't the same, so I must be misunderstanding.

Moreover, in Section 8.6 "True Lambertian Reflection", the text above code listing 37 says, "This is achieved by picking points on the surface of the unit sphere, offset along the surface normal. Picking points on the sphere can be achieved by picking points in the unit ball, and then normalizing those." Based on this, I would have expected code listing 37 to make use of "random_in_unit_sphere()". Instead, it does something else entirely that is not explained. (It generates a z value and an xy-plane angle, and then chooses x and y such that they have the angle and the point is on the unit sphere).

**Comment by trevordblack** [comment]
Closing this out with the landing of #1010
