### ISSUE TITLE
Listing 37: Incorrectly generating random unit vector

### ISSUE THREAD

**Issue by pmcmorris** [RayTracing/raytracing.github.io#697]
Maybe I'm reading this incorrectly but what the code does doesn't seem to match the function name.  The current code appears to do a uniform distribution on cylinder and then stretch to a sphere.  Doesn't that raise the probability of points near the poles?

```cpp
vec3 random_unit_vector() {
    auto a = random_double(0, 2*pi);
    auto z = random_double(-1, 1);  // uniform in z means the same # of hits over less surface area
    auto r = sqrt(1 - z*z);
    return vec3(r*cos(a), r*sin(a), z);
}
```
I was expecting something more like this:
```cpp
vec3 random_unit_vector() {
        auto a = random_double(0, 2 * pi);
        auto b = random_double(-pi/2, pi/2);
        auto z = sin(b);
        auto r = sqrt(1 - z * z);
        return vec3(r * cos(a), r * sin(a), z);
}
```

**Comment by yig** [comment]
This is related to https://github.com/RayTracing/raytracing.github.io/issues/696

**Comment by hollasch** [comment]
See https://mathworld.wolfram.com/SpherePointPicking.html for the derivation of the `random_unit_vector()` function. Still, the text needs to be made more clear.

**Comment by pmcmorris** [comment]
Reading my own advice... don't to that either it has a similar problem.

But I'm assuming wolfram would have a much better fix. :)

**Comment by hollasch** [comment]
No fix to the function is needed. The current function is identical to the approach illustrated in Wolfram, though the variable names are different.

**Comment by hollasch** [comment]
Hmmm. Now I'm doubting myself. I think you may be right. Investigating.

**Comment by hollasch** [comment]
Took a while to get through my thick skull. Turns out I added this alternate algorithm 2019-10-21 (one year ago), and yes, misunderstood what _u_ meant above.

The original form used `random_in_unit_sphere()` and then normalized those points. I'm going to revert back to that, since it's most comprehensible.
