### ISSUE TITLE
Book2: Listing 40: mistake on header's name

### ISSUE THREAD

**Issue by ambiguoustexture** [RayTracing/raytracing.github.io#698]
At line 1868 of [RayTracingTheNextWeek.html](https://github.com/RayTracing/raytracing.github.io/blob/master/books/RayTracingTheNextWeek.html):
`[Listing [perlin-smoothed-2]: <kbd>[perlin.h]</kbd> Perlin smoothed, higher frequency]`, 
the name of the header file should be _texture.h_

**Comment by hollasch** [comment]
Thanks!

**Comment by hollasch** [comment]
Fixed in #709
