### ISSUE TITLE
[Book 2] Explicitly set aperture size in all cases.

### ISSUE THREAD

**Issue by raonetwo** [RayTracing/raytracing.github.io#699]
I would recommend that all values that may change in the switch case be explicitly set. This is already being done for field of view, and this can be explicitly done for aperture size as well.

If not than in the code snippet shown in the book highlight the aperture size for each scene.

I missed setting the aperture size to 0 (default) instead of 0.1 (earlier default) and ended up with defocussed final render.
![image-_copy_](https://user-images.githubusercontent.com/17951961/90486233-4d631e80-e156-11ea-8551-add28e7b502a.png)

**Comment by hollasch** [comment]
Looks like the best approach is one of the following sketches:
- #754
- #755

Leaning toward approach B (#754).

This is a least a minor-level change, so moving it to v3.3.0 for now.

**Comment by hollasch** [comment]
Fixed with the new `scene` class.
