### ISSUE TITLE
Add a test for the `bvh_node` class right after we're done writing it

### ISSUE THREAD

**Issue by define-private-public** [RayTracing/raytracing.github.io#704]
We write the code for this class pretty early on in the book, but we don't test it until the end of the book (the final scene).  In the general flow of things this doesn't seem that right.  I think it would be good to show the user to the use the class with the "bouncing balls" scene that was finished in the previous chapter, as there are a lot of objects and the `bvh_node` surely should benefit the performance.

**Comment by trevordblack** [comment]
I agree with the above. I was about to create a similar issue until I found this

**Comment by L3tum** [comment]
I think it would be alright to just use the last scene from the last book (Raytracing in one weekend) and just push it through the BVHNode. In my case it resulted in a 5x time decrease and should be good to visualize the need for such structures. Maybe only do the 400x225 to keep it in realistic timeframes.

**Comment by rongguodong** [comment]
After created issue #715, I realized this one is for the same thing. I have a one line change in issue #715 for that. :)

**Comment by trevordblack** [comment]
This appears to have been completed with commit 49c1e1ea1c1f3fcaaa39ec2babdb54ed901987d0 
in #855
