### ISSUE TITLE
[Question] Andrew Kensler optimization

### ISSUE THREAD

**Issue by antoniogamiz** [RayTracing/raytracing.github.io#710]
Hi, could you please add a link/reference to the paper/blog/similar where Andrew Kensler explains that optimization? I'm having some trouble understanding why that version is better, thanks.

**Comment by antoniogamiz** [comment]
In fact, I do not know why that code even compiles:
~~~C++
        auto t0 = (min()[a] - r.origin()[a]) * invD;
        auto t1 = (max()[a] - r.origin()[a]) * invD;
~~~
What is `min()` and `max()`??

**Comment by antoniogamiz** [comment]
Agh, sorry for raising this issue, I have just realized they are methods...

**Comment by trevordblack** [comment]
I think it was an informal conversation that happened over email.

There is this blog post, which you've already discovered, by Kensler:
eastfarthing.com/blog/2015-04-21-noise/

And there is this blog post by Shirley, with an unhelpful dead image.
http://psgraphics.blogspot.com/2019/03/making-your-bvh-faster.html

I believe Kensler found the solution in the text by profiling the code.
This isn't a complete answer, but was this satisfactory?

**Comment by hollasch** [comment]
Related to issue #817.
