### ISSUE TITLE
`trilinear_interp` is inconsistent between listings and src

### ISSUE THREAD

**Issue by rjkilpatrick** [RayTracing/raytracing.github.io#722]
When we are introduced to `trilinear_interp`, it is a function outside of the `perlin` class (listing 33):
https://github.com/RayTracing/raytracing.github.io/blob/80a955b23d7c95844bccabb6127abd4733d18a28/books/RayTracingTheNextWeek.html#L1597-L1611

However, when later amended (listing 39), it is moved into the class and marked with `const` (only valid for class member functions).
https://github.com/RayTracing/raytracing.github.io/blob/80a955b23d7c95844bccabb6127abd4733d18a28/books/RayTracingTheNextWeek.html#L1842-L1865

In the `src` directory, the `const` is missing but it's given a static 
https://github.com/RayTracing/raytracing.github.io/blob/80a955b23d7c95844bccabb6127abd4733d18a28/src/common/perlin.h#L100-L116

I propose changing [listing 33](https://github.com/RayTracing/raytracing.github.io/blob/80a955b23d7c95844bccabb6127abd4733d18a28/books/RayTracingTheNextWeek.html#L1597-L1611) to a private member function for consistency.

Can someone advise about which function signature (i.e. `static` and/or `const`) should be the authoritative version? I can then put a PR together

**Comment by hollasch** [comment]
Thanks. It should be `static`; delete the `inline` keyword.

**Comment by hollasch** [comment]
Resolved in #724
