### ISSUE TITLE
`bvh_node` is broken with negative-radius spheres

### ISSUE THREAD

**Issue by define-private-public** [RayTracing/raytracing.github.io#733]
I wanted to create some "Matryoshka hollow glass spheres", so I setup this scene:

```c++
    hittable_list world;

    const color ground_yellow(0.8, 0.8, 0);
    const color gold(0.8, 0.6, 0.2);
    const color blue(0.1, 0.2, 2);
    const color green(0.1, 0.9, 0.3);
    const double glass_refractive_index = 1.5;
    const auto ground_mat = make_shared<lambertian>(ground_yellow);
    const auto blue_mat   = make_shared<lambertian>(blue);
    const auto left_mat   = make_shared<dielectric>(glass_refractive_index);
    const auto center_mat = make_shared<lambertian>(green);
    const auto right_mat  = make_shared<metal>(gold, 1);
    const double tiny_y = 0.005;

    world.add(make_shared<sphere>(point3(-1,  tiny_y, -1),  0.5,  left_mat));
    world.add(make_shared<sphere>(point3(-1,  tiny_y, -1), -0.35, left_mat));
    world.add(make_shared<sphere>(point3(-1,  tiny_y, -1),  0.3,  left_mat));
    world.add(make_shared<sphere>(point3(-1,  tiny_y, -1), -0.2,  left_mat));
    world.add(make_shared<sphere>(point3(-1,  tiny_y, -1),  0.15, left_mat));
    world.add(make_shared<sphere>(point3(-1,  tiny_y, -1),  0.1,  blue_mat));
    world.add(make_shared<sphere>(point3( 0,  0.15 , -1),   .5,  center_mat));
    world.add(make_shared<sphere>(point3( 1,  tiny_y, -1),  0.5,  right_mat));
    world.add(make_shared<sphere>(point3( 0, -100.5, -1),   100,  ground_mat));   // The ground (Big boi)

    const bvh_node world_bvh(world, 0, 1); 

    point3 lookfrom(0, 0.25, 3.25);
    point3 lookat(0, 0, -1);
    auto vfov = 25.0;
    auto aperture = 0.0;
    color background = color(0.70, 0.80, 1.00);

    // Camera

    const vec3 vup(0,1,0);
    const auto dist_to_focus = (lookfrom - lookat).length();
    const int image_height = static_cast<int>(image_width / aspect_ratio);

    camera cam(lookfrom, lookat, vup, vfov, aspect_ratio, aperture, dist_to_focus, 0.0, 1.0);
```

When rendering on `world`, I get this, which is correct:
![three_spheres_no_bvh](https://user-images.githubusercontent.com/4551425/93409772-9990a400-f865-11ea-9287-9133772a5c6c.png)

But when I render with `world_bvh`, this is the result:
![three_spheres_bvh](https://user-images.githubusercontent.com/4551425/93409790-a90fed00-f865-11ea-864d-8fe82aa80117.png)

I don't think that's right.

**Comment by hollasch** [comment]
Ref. #532

I believe that this is due to using negative radius spheres, and that you should be using appropriate indices of refraction for your air-inside-glass bubbles.

Can you try the following instead?

      hittable_list world;

      const color ground_yellow(0.8, 0.8, 0);
      const color gold(0.8, 0.6, 0.2);
      const color blue(0.1, 0.2, 2);
      const color green(0.1, 0.9, 0.3);
      const double glass_refractive_index = 1.5;
      const auto ground_mat = make_shared<lambertian>(ground_yellow);
      const auto blue_mat   = make_shared<lambertian>(blue);
      const auto left_mat   = make_shared<dielectric>(glass_refractive_index);
    + const auto left_air   = make_shared<dielectric>(1/glass_refractive_index);
      const auto center_mat = make_shared<lambertian>(green);
      const auto right_mat  = make_shared<metal>(gold, 1);
      const double tiny_y = 0.005;

      world.add(make_shared<sphere>(point3(-1,  tiny_y, -1),  0.5,  left_mat));
    - world.add(make_shared<sphere>(point3(-1,  tiny_y, -1), -0.35, left_mat));
    + world.add(make_shared<sphere>(point3(-1,  tiny_y, -1),  0.35, left_air));
      world.add(make_shared<sphere>(point3(-1,  tiny_y, -1),  0.3,  left_mat));
    - world.add(make_shared<sphere>(point3(-1,  tiny_y, -1), -0.2,  left_mat));
    + world.add(make_shared<sphere>(point3(-1,  tiny_y, -1),  0.2,  left_air));
      world.add(make_shared<sphere>(point3(-1,  tiny_y, -1),  0.15, left_mat));
      world.add(make_shared<sphere>(point3(-1,  tiny_y, -1),  0.1,  blue_mat));
      world.add(make_shared<sphere>(point3( 0,  0.15 , -1),   .5,  center_mat));
      world.add(make_shared<sphere>(point3( 1,  tiny_y, -1),  0.5,  right_mat));
      world.add(make_shared<sphere>(point3( 0, -100.5, -1),   100,  ground_mat));   // The ground (Big boi)

      const bvh_node world_bvh(world, 0, 1); 

      point3 lookfrom(0, 0.25, 3.25);
      point3 lookat(0, 0, -1);
      auto vfov = 25.0;
      auto aperture = 0.0;
      color background = color(0.70, 0.80, 1.00);

      // Camera

      const vec3 vup(0,1,0);
      const auto dist_to_focus = (lookfrom - lookat).length();
      const int image_height = static_cast<int>(image_width / aspect_ratio);

      camera cam(lookfrom, lookat, vup, vfov, aspect_ratio, aperture, dist_to_focus, 0.0, 1.0);

**Comment by hollasch** [comment]
Also, I'm assuming this is for _Ray Tracing: The Next Week_, right?

**Comment by define-private-public** [comment]
The "smaller negative" sphere is a trick that @petershirley mentioned as a way of producing a hollow glass sphere.  I tried out you recommendation of doing the `1 / glass_refractive_index`.  It produced this:

No BVH:
![render_inv_refract_no_bvh](https://user-images.githubusercontent.com/4551425/97650622-7e05e500-1a30-11eb-9950-9a6c8ddbb22e.png)

With BVH:
![render_inv_refract_bvh](https://user-images.githubusercontent.com/4551425/97650628-82ca9900-1a30-11eb-8fbf-aa4b6867e3d1.png)

It doesn't look right.  The BVH node is from "Ray Tracing: The Next Week".

**Comment by define-private-public** [comment]
I figured out the fix.  When making the `aabb` for the `sphere` to use be used for the `bvh_node`, `std::abs()` should be wrapped around the radius.  I'll submit a patch.

**Comment by hollasch** [comment]
The entirely blue sphere is very surprising. I can't imagine how that could happen.

**Comment by hollasch** [comment]
I think the above fix should get things working for you. Please let me know if this is untrue.

**Comment by define-private-public** [comment]
Hi,  sorry for the delays.

I've been quite preoccupied these past few weeks.  I'll be taking a look at it most likely during the upcoming Holiday/weekend.
