### ISSUE TITLE
Book 3 listing 38 (in section 12.2) doesn't tell the user how to handle the new `lights` parameter in `ray_color()`

### ISSUE THREAD

**Issue by define-private-public** [RayTracing/raytracing.github.io#738]
https://raytracing.github.io/books/RayTracingTheRestOfYourLife.html#cleaninguppdfmanagement./handlingspecular

When I ran the code, I was getting some segfaults, then I realized that `lights` wasn't populated.  This section should instruct the user how to collect the lights from listing 38 and then pass that into `ray_color()`.

**Comment by hollasch** [comment]
* section 12.2

**Comment by hollasch** [comment]
Thanks!
