### ISSUE TITLE
Improve names for time, ray values in hittable and derived classes

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#746]
We need better names that distinguish between these, instead of using generic _t_ names.

**Comment by trevordblack** [comment]
We have `t` for the parametric distance (ray values), `t` for time

We already have a diagram that has `t` for parametric distance (figure 2).

What do we change hittable and it's children to?

There's also this egregious example:
```
            point3 cen0, point3 cen1, double t0, double t1, double r, shared_ptr<material> m)
            : center0(cen0), center1(cen1), time0(t0), time1(t1), radius(r), mat_ptr(m)
```

**Comment by trevordblack** [comment]
`t_min`, `tmin`, `t_max`, `tmax`

`time0`, `time_0`, `tm0, `time1`, `time_1`, `tm1`

???

**Comment by trevordblack** [comment]
I propose:

`t_min`, `t_max`, `time0`, `time1`, `tm0`, `tm1`

**Comment by trevordblack** [comment]
Or, find a new letter for the parametric distance and start redoing figures, code, and text.

**Comment by hollasch** [comment]
I think `t_min` and `t_max` for _t_ parameters (like with rays) are good, as are `time0`, `time1` for time intervals.

Where would you use `tm0` and `tm1`? Not wild about those.

**Comment by trevordblack** [comment]
```
         camera(
             point3 lookfrom,
             point3 lookat,
             vec3   vup,
             double vfov, // vertical field-of-view in degrees
             double aspect_ratio,
             double aperture,
             double focus_dist,
             double t0 = 0,
             double t1 = 0
         ) {
             auto theta = degrees_to_radians(vfov);
             auto h = tan(theta/2);
             auto viewport_height = 2.0 * h;
             auto viewport_width = aspect_ratio * viewport_height;
 
             w = unit_vector(lookfrom - lookat);
             u = unit_vector(cross(vup, w));
             v = cross(w, u);
 
             origin = lookfrom;
             horizontal = focus_dist * viewport_width * u;
             vertical = focus_dist * viewport_height * v;
             lower_left_corner = origin - horizontal/2 - vertical/2 - focus_dist*w;
 
             lens_radius = aperture / 2;
             time0 = t0;
             time1 = t1;
         }
```

**Comment by trevordblack** [comment]
Basically in function signatures where we don't want to use `time0` `time1` because those are already member variables.

Did we standardize on how we wanted to accomplish this?

`_time0`?

**Comment by trevordblack** [comment]
we also have member variables `_max`, and `_min` in aabb.

So our notation here is _inconsistent_

**Comment by trevordblack** [comment]
Oh, and `src/*/bvh.h` is a _mess_

**Comment by hollasch** [comment]
Following up on Slack.

**Comment by trevordblack** [comment]
Outcome:
`t_max`
`t_min`
`time0`
`time1`
`_time0`
`maximum`
