### ISSUE TITLE
rotate_y has bounding box with incorrect time

### ISSUE THREAD

**Issue by trevordblack** [RayTracing/raytracing.github.io#749]
```
rotate_y::rotate_y(shared_ptr<hittable> p, double angle) : ptr(p) {
  auto radians = degrees_to_radians(angle);
  sin_theta = sin(radians);
  cos_theta = cos(radians); 
  hasbox = ptr->bounding_box(0, 1, bbox);
  ...
```

where
```
hasbox = ptr->bounding_box(0, 1, bbox);
```
the 0 and 1 need to be determined at runtime

**Comment by hollasch** [comment]
_Oif._

**Comment by trevordblack** [comment]
box_compare has similar problems

**Comment by trevordblack** [comment]
`rotate_y` requires removing `hasbox` and just solving for the bounding-box of the base ptr lazily.

`box_compare` will require passing the `time0|1` parameters down

**Comment by hollasch** [comment]
See comments in #770. The current bounding box implementation has design problems. Deferring to v4.0.0.

**Comment by hollasch** [comment]
See #799
