### ISSUE TITLE
Redesign the aabb (axis-aligned bounding box) class

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#773]
Specifically, we should support AABB values empty (or null) and universe:

- universe = <-∞, -∞, -∞> → <+∞, +∞, +∞>
- empty = <+∞, +∞, +∞> → <-∞, -∞, -∞>

I've used this formulation earlier in my career, and the math just flows through calculations beautifully. The only other change we'd need to make is to update aabb::hit(), aabb::area(), and aabb::longest_axis().

If we do this, we can rip out all of the boolean checks for whether a hittable has a bounding box. Instead, we enforce the requirement that all hittables have a bounding box.

We have a single place in our codebase where a hittable did not have a bounding box, and that was a hittable_list with zero components. In my proposed scheme, we should just return the empty AABB.

A lighter weight implementation of this could be just a special case where the minimum of any dimension is greater than the maximum of any dimension. We could add a method aabb::is_empty() to check for this. The lightweight implementation should be sufficient for our use case; the version with infinite values is mostly useful when computing the intersection and union of bounding boxes.

**Comment by trevordblack** [comment]
This is conceptually very cool. I'd have to write out the code, or see it written out, to determine if it's easier/simpler/more learnable.

Having
> where the minimum of any dimension is greater than the maximum of any dimension
to represent an empty AABB is interesting. Zero is a special case in FP, so there shouldn't (!!) be round off error associated with an empty if max and min are both all zeroed out. But I think having an explicit definition for empty will be valuable.
whether that is:
<+∞, +∞, +∞> → <-∞, -∞, -∞>
OR
<0, 0, 0> → <0, 0, 0>

Hell, maybe we can get some of those "signed zeros" I keep hearing about in the literature (twitter)

**Comment by hollasch** [comment]
Actually, <0,0,0>→<0,0,0> is the bounding box for the single point <0,0,0>, which is very different from the empty bounding box.

For example, if b1 = <10,10,10>→<11,11,11>, b2 = <0,0,0>→<0,0,0>, and b3 = _empty_ = <+∞,+∞,+∞>→<-∞,-∞,-∞>:

- intersection(b1, b2) = <10,10,10>→<0,0,0> = _empty_
- intersection(b1, _empty_) = <+∞,+∞,+∞>→<-∞,-∞,-∞> = _empty_
- union(b1, b2) = <0,0,0>→<11,11,11>
- union(b1, _empty_) = b1

And if we had _universe_ = <-∞,-∞,-∞>→<+∞,+∞,+∞>:

- intersection(b1, _universe_) = b1
- union(b1, _universe_) = _universe_
- intersection(_empty_, _universe_) = _empty_
- union(_empty_, _universe_) = _universe_

**Comment by hollasch** [comment]
Done.
