### ISSUE TITLE
Implement an interval class

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#777]
A class that operates on ranges of `double` values. Use cases:

- [x] aabb class (#796)
- [ ] time interval (#795)
- [x] clamp (#793)
- [x] hittable::hit() (#786)
- [ ] moving_sphere time range (#797)
- [ ] moving_sphere center range (#797)

Here's a sketch of an interval class (not all methods below need be implemented; only those actually needed):

    struct interval {
        double min, max;

        interval() : min(0), max(0) {}
        interval(double x) : min(x), max(x) {}
        interval(double _min, double _max) : min(_min), max(_max) {}

        double size() const {
            return max - min;
        }

        bool contains(double x) const {
            return min <= x && x <= max;
        }

        double clamp(double x) const {
            return (x < min) ? min
                 : (x > max) ? max
                 : x;
        }

        interval hull(const interval& other) const {
            return interval(std::min(min, other.min), std::max(max, other.max));
        }

        interval intersect(const interval& other) const {
            return interval(std::max(min, other.min), std::min(max, other.max));
        }

        static interval empty    = interval(+std::numeric_limits::infinity, -std::numeric_limits::infinity);
        static interval universe = interval(-std::numeric_limits::infinity, +std::numeric_limits::infinity);
    }

This class could also support transforms, such as scale, translate, whatever.

**Comment by hollasch** [comment]
Hmmm. It appears that "range" is unconventional / inaccurate. Looks like "interval" is more correct.

**Comment by hollasch** [comment]
From Slack discussion, constant values are `interval.empty` and `interval.universe`.

**Comment by trevordblack** [comment]
Suggest defining `const infinity` to `std::numeric_limits::infinity`

**Comment by hollasch** [comment]
I like it. The better way would be:
```
using std::numeric_limits::infinity;
```

**Comment by trevordblack** [comment]
Yeah, but qualify it's a double:
```c++
using std::numeric_limits<double>::infinity;
```

**Comment by hollasch** [comment]
_Oif_. Ok,
```
const auto infinity = std::numeric_limits<double>::infinity();
```

**Comment by hollasch** [comment]
*ARRRRGGGHHH!!!* That looks exactly like the line we already have in `src/common/rtweekend.h`. :^P

**Comment by hollasch** [comment]
The remaining three tasks all have to do with time, which is more broadly covered in #799. We'll use `interval` as appropriate when revisiting time.

**Comment by hollasch** [comment]
Also see specific issues for the tasks given above.
