### ISSUE TITLE
Create further reading appendix for book 1

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#784]
Incorporate the material from https://in1weekend.blogspot.com/2016/01/ray-tracing-in-one-weekend.html.

**Comment by trevordblack** [comment]
https://github.com/RayTracing/raytracing.github.io/wiki/Aggregation-of-Possible-Next-Steps

**Comment by trevordblack** [comment]
Wow. I wrote that a year ago.
And reading through it, I'm shocked at how much better I've gotten at writing since then

**Comment by hollasch** [comment]
Resolve this as duplicate of #407?

**Comment by trevordblack** [comment]
Agreed. Duplicate.

Closing
