### ISSUE TITLE
Delete `virtual` keyword for overriding methods

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#805]
Just had this come up at work: the `virtual` keyword is redundant with `override` or `final`. Either of the last two imply that the function is virtual.

Hence a common recommendation is that the first declaration of a virtual function get the `virtual` keyword, and that all derived classes use either `override` or `final` and do _not_ use the `virtual` keyword. Makes sense, and reduces unnecessary keyword clutter. I think we should adopt this convention.

**Comment by trevordblack** [comment]
I approve

**Comment by hollasch** [comment]
Done.
