### ISSUE TITLE
implementation with D 

### ISSUE THREAD

**Issue by ulaas** [RayTracing/raytracing.github.io#815]
Hi i have implemented the c++ one weekend code into D for fun
you can reference if you like https://github.com/ulaas/dray
it was a great read, i will surely consume the other books. thanks for great work!

**Comment by D-K-E** [comment]
@ulaas Hey congragulations! You can edit the wiki section directly if I am not mistaken.

**Comment by ulaas** [comment]
oh, will do when i have the time thanks. i will iterate this into a multithreaded interactive version. i will tag the BOOK version.
thanks again.
