### ISSUE TITLE
aabb::hit() has wildly different performance based on the two presented implementations

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#817]
For now, I have both versions coded up in `aabb.h`, with a preprocessor block that selects the fast (prior) one. We'll need to resolve this before we ship v4.0.0.

**Comment by trevordblack** [comment]
I've been crazy busy and haven't found the energy to attack this. We'll see about tomorrow

**Comment by hollasch** [comment]
See also #892

**Comment by hollasch** [comment]
Ah, I finally figured it out. The 10x slower version was not properly tightening the `ray_t` interval with each axis. Instead, it was using temporary variables, so the result was much less optimal. I'll make a few light touches with the current working code and the listing in the book and be done with this.

**Comment by hollasch** [comment]
Fixed in #1120
