### ISSUE TITLE
Book 3 Ray Tracing For The Rest of Your Life-Listing 11

### ISSUE THREAD

**Issue by kyamant** [RayTracing/raytracing.github.io#831]
In the third book _Ray Tracing For The Rest of Your Life_, listing 11 for `material.h` has:

`scattered = ray(rec.p, unit_vector(direction), r_in.time());`

the variable `direction ` was not declared.

**Comment by trevordblack** [comment]
I'm on it, thank you

**Comment by hollasch** [comment]
@trevordblack — let's throw this on `dev-patch`.

**Comment by trevordblack** [comment]
Well. It's in the changes I literally just created a PR for.........

**Comment by hollasch** [comment]
You, sir, have ruined _everything_.

No worries, keep it in `dev-major`, and I'll cherry-pick into v.3.2.4.

**Comment by trevordblack** [comment]
sure
sure sure sure

**Comment by trevordblack** [comment]
Can I close out this issue?

**Comment by hollasch** [comment]
Hmmm, looks like v3.2.4 ain't happening; I'd forgotten whether this was true and had to check. There's nothing on `dev-patch`. Let's just say this is fixed in `dev-major`.

Added an entry to CHANGELOG, as the only change in #884.
