### ISSUE TITLE
Math cleanup pass

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#839]
- Use consistent indentation levels for our math blocks
- Use equation alignment where appropriate

**Comment by ymherklotz** [comment]
In case this is useful, I just noticed that the alignment of italic variables in math blocks didn't use `\textit`, which means the spacing looks a bit strange sometimes as they are basically independent letters.

I have made the changes for all variables like that in Book3 (https://github.com/ymherklotz/raytracing.github.io/tree/textit-in-mathblocks), and if this is useful and a wanted changed, I could make the same changes in Book1 and Book2.

**Comment by hollasch** [comment]
Thank you! In most cases, this has only a very slight effect on kerning, but there are definitely cases where it's significant. Here's a good example:

Before:
![pSurface-before](https://user-images.githubusercontent.com/313871/131231061-38b38e6a-7fa3-428e-87f5-1fb7a6028e42.jpg)

After:
![pSurface-after](https://user-images.githubusercontent.com/313871/131231072-a0ea459f-8b64-4af0-a091-b7b1c9246db3.jpg)

It's also proper markup, which would be enough to convince me.

Thanks again for the help -- converting the other two books would be most appreciated, based on the `dev-major` branch. Also, please add yourself to `acknowledgements.html`, and add a new v4.0.0 entry in changelog.md.

**Comment by hollasch** [comment]
Done.
