### ISSUE TITLE
7.2 Uniform Sampling a Hemisphere . cube cosine 

### ISSUE THREAD

**Issue by zjlo** [RayTracing/raytracing.github.io#846]
int main() {
        int N = 1000000;
        auto sum = 0.0;
        for (int i = 0; i < N; i++) {
            auto r1 = random_double();
            auto r2 = random_double();
            auto x = cos(2*pi*r1)*2*sqrt(r2*(1-r2));
            auto y = sin(2*pi*r1)*2*sqrt(r2*(1-r2));
            auto z = 1 - r2;
            sum += z*z*z / (1.0/(2.0*pi));
        }
        std::cout << std::fixed << std::setprecision(12);
        std::cout << "Pi/2     = " << pi/2 << '\n';
        std::cout << "Estimate = " << sum/N << '\n';
    }

The cos(theta) has changed , why isn't the sin(theta)  sqrt(1-(1-r2)*(1-r2))?  
Is this a bug? 

    auto x = cos(2*pi*r1)*sqrt(r2*(2-r2));
    auto y = sin(2*pi*r1)*sqrt(r2*(2-r2));
    auto z = 1 - r2;

**Comment by hollasch** [comment]
I'm not sure if this is what you're getting at, but the variables `x` and `y` are not used in this program. Apparently this has always been the case, and we've never caught it.

**Comment by hollasch** [comment]
Hey @trevordblack — looks to me like we can just remove the `x` and `y` calculations. Do you concur?

**Comment by trevordblack** [comment]
I concur. That said, I chose to write them into the book 3 edits because it reinforces the written math

**Comment by hollasch** [comment]
If there's information you want to preserve, perhaps retain as comments?

    int main() {
        int N = 1000000;
        auto sum = 0.0;
        for (int i = 0; i < N; i++) {
            auto r1 = random_double();
            auto r2 = random_double();
            // x = cos(2*pi*r1)*2*sqrt(r2*(1-r2));
            // y = sin(2*pi*r1)*2*sqrt(r2*(1-r2));
            auto z = 1 - r2;
            sum += z*z*z / (1.0/(2.0*pi));
        }
        std::cout << std::fixed << std::setprecision(12);
        std::cout << "Pi/2     = " << pi/2 << '\n';
        std::cout << "Estimate = " << sum/N << '\n';
    }

Either way, can you fold these into your book3 edits? That's probably the right place to do this.

**Comment by trevordblack** [comment]
Will do

**Comment by trevordblack** [comment]
Solution is in #840
