### ISSUE TITLE
Reflections on ceiling of Cornell Box

### ISSUE THREAD

**Issue by math-araujo** [RayTracing/raytracing.github.io#866]
Hey! First of all, thanks all for the effort put on the book and code, it's a delight to learn through it!

Everything worked as expected up to Book 2 Next Week - Chapter 7, including the empty Cornell Box.

However, on Chapter 8, the [Cornell Box with two blocks](https://raytracing.github.io/books/RayTracingTheNextWeek.html#instances) shown some reflections on the ceiling that does not appear on the images on the [book](https://raytracing.github.io/images/img-2.19-cornell-blocks.png), on the [master branch](https://github.com/RayTracing/raytracing.github.io/blob/master/images/img-2.19-cornell-blocks.png) nor in [dev-major](https://github.com/RayTracing/raytracing.github.io/blob/dev-major/images/img-2.19-cornell-blocks.png). Here is my result:

![two_blocks_cornell_box_reflections](https://user-images.githubusercontent.com/52018308/107868145-709a2c80-6e60-11eb-8c8e-152a889c8d24.png)

I thought that I've done something wrong on my code somewhere, but after some attempts I tried to comment out the following code section of [`lambertian::scatter` function](https://github.com/RayTracing/raytracing.github.io/blob/master/src/TheNextWeek/material.h#L42) because the reflections seems to be approximately in the same direction of the surface normals: 
```
    // Catch degenerate scatter direction
    if (scatter_direction.near_zero())
        scatter_direction = rec.normal;
```

After commenting this code, I got the following result, which seems very close to the reference images on the book and on the repository:

![two_blocks_cornell_box_maybe_fixed](https://user-images.githubusercontent.com/52018308/107868150-7f80df00-6e60-11eb-8e50-3c968d7ec794.png)

Are the reference images outdated? Looking at the git history, it appears that the [images](https://github.com/RayTracing/raytracing.github.io/commit/7ed556c3f68118ca34df9d20637f317d4a277f5b) were committed before the [code for degenerate direction](https://github.com/RayTracing/raytracing.github.io/commit/1da626eca15a5d6929929f6284b3595375ddb200#diff-d4e457ef10aecdac6e9e415ddf6778263fb8727ca67d59abf54489b49c9c0857) was committed. 

Thanks!

**Comment by hollasch** [comment]
Nice job checking both the `master` and `dev-major` branches. I would trust that your images are more up to date than the ones in book. After we're done with our huge update, we'll be going through the books one-by-one, reproducing the code and renders along the way, and will be able to verify your observations.

I'll add this to the v4.0.0 milestone so we track it. Thank you for reporting, and for the diligence in investigating.

**Comment by math-araujo** [comment]
Thanks for the reply! I'll post here if I find any additional info that is relevant to confirm (or discard) my results.

**Comment by hollasch** [comment]
Should be validated as part of #779.

**Comment by hollasch** [comment]
Just finished with a Book 2 progression 2024-03-27.

The latest rendering of this image (2.20) doesn't show any artifacts on the ceiling like the first image above.

Reviewing the code change to guard against near-zero scatter direction, this should very rarely happen — it should only be triggered if the random direction is exactly opposite the normal vector. Given this, I suspect that the original poster's code has an error either in the `vec3::near-zero()` or the `random_unit_vector()` functions.
