### ISSUE TITLE
Book 1: Why add degrees_to_radians function when it's unused?

### ISSUE THREAD

**Issue by ronnieholm** [RayTracing/raytracing.github.io#876]
Section 6.7, Common Constants and Utility Functions adds the `degrees_to_radians` function but no code near by makes use of the function. That's confusing to the reader.

**Comment by hollasch** [comment]
It's used as the single entry in the utility section of `rtweekend.h`, since we're showing the basic layout of the file, and is later used in `camera` class and in `hittable.h`.
