### ISSUE TITLE
The translate transform changes scattering behavior for dielectric materials.

### ISSUE THREAD

**Issue by rossg42** [RayTracing/raytracing.github.io#889]
Hi,

I believe I've encountered a bug in the `translate` transform class that becomes apparent when moving an object with a `dielectric` material. Using the final Cornell box scene in Book 3, we expect to get (from the reference code in both `master` and `dev-major`):

![cb_baseline](https://user-images.githubusercontent.com/6170208/116947239-d2895780-ac41-11eb-8477-8d5193f4730b.png)

However, when I change the glass sphere to use the translation transform instead of a fixed point, by changing the line (line 60 `main.cc` in the `dev-major` branch):

    world.add(make_shared<sphere>(point3(190,90,190), 90 , glass));

to

    world.add(make_shared<translate>(make_shared<sphere>(point3(0,0,0), 90, glass), vec3(190, 90, 190)));

I instead get:

![cb_translated_sphere](https://user-images.githubusercontent.com/6170208/116947355-24ca7880-ac42-11eb-842d-6dd2af1693d1.png)

I think the issue is in `translate`'s `hit()` function, where it resets the surface normal (line 90 in `hittable.h` on `dev-major`):

    rec.set_face_normal(moved_r, rec.normal);

If the underlying object had previously flipped the normal vector (because the ray is hitting the inside of the glass sphere), this call could set `rec.front_face` to `true` when it shouldn't be.

Empirically, removing that line entirely seems to fix the problem, and I recover the baseline image. Does this seem correct?

**Comment by hollasch** [comment]
Translation is a no-op on vectors, so your fix feels right. Nice catch!

**Comment by trevordblack** [comment]
I think rotation is just broken for spheres.

Swapping the above for
```
world.add(make_shared<rotate_y>(make_shared<sphere>(point3(0,0,0), 90, glass), 90));
```

Produces:
![rotation](https://user-images.githubusercontent.com/10197672/130313744-fae20f5c-beae-46de-af39-b2c477de6f9c.jpg)

Notice the tiny sphere poking out in the bottom right corner.

I think this is because we're translating in the sphere code, causing the sphere to revolve around a point in space

**Comment by trevordblack** [comment]
We get this piece of advant garde art if we rotate instead:
```
     world.add(make_shared<rotate_y>(make_shared<sphere>(point3(190,90,190), 90, glass), 90));
```

![cornell_rotate_sphere](https://user-images.githubusercontent.com/10197672/130315310-3eeb72a0-3b44-43d6-8754-9e8b58563056.jpg)


But that's two distinct errors colliding at once

**Comment by trevordblack** [comment]
good catch.

the fix is in https://github.com/RayTracing/raytracing.github.io/pull/913/commits/e17e01df3c0c064b6b88f3b8b61ab977ef2f97c4

**Comment by trevordblack** [comment]
Fixed in dev-major
