### ISSUE TITLE
Book 3 Section 8.2: Typo in pseudo code

### ISSUE THREAD

**Issue by nya3jp** [RayTracing/raytracing.github.io#894]
Book 3 Section 8.2 has the following pseudo code to generate a unit vector:

```
if absolute(n.x > 0.9)
    a ← (0, 1, 0)
else
    a ← (1, 0, 0)
```

The first condition has a typo. It should be either `if absolute(n.x) > 0.9` or `if (absolute(n.x) > 0.9)`.

**Comment by hollasch** [comment]
This has been fixed in `dev-major` (pending v4.0.0 release).
