### ISSUE TITLE
Upgrade the local markdeep to latest version or just use the official latest

### ISSUE THREAD

**Issue by srayuws** [RayTracing/raytracing.github.io#898]
Currently the local markdeep is 1.11. There is a bug in this version on Firefox and is already fixed in 1.12, as mentioned in the release note:

    Fixed section numbers not aligning with table of contents numbers in Firefox. 

In 1.11 and Firefox, the first section under "3.The vec3 Class" looks like "3.4 Variables and Methods", which should be "3.1 Variables and Methods".

I noticed there are two script tag at the end of the HTML file, the `https://morgan3d.github.io/markdeep/latest/markdeep.min.js` and a local version.
Can you kindly upgrade the local version to the latest or just remove the local one?

**Comment by hollasch** [comment]
Thank you for the feedback! I've pushed this directly to `master`, so it should be immediately updated on the live site. This updates Markdeep to v1.13.

**Comment by hollasch** [comment]
As a side note, I'm making the same change to `dev-major`.
