### ISSUE TITLE
Add related images (earthmap.jpg) to source code

### ISSUE THREAD

**Issue by ruiwng** [RayTracing/raytracing.github.io#91]
can you upload the related images? thank you!!!

**Comment by trevordblack** [comment]
I googled for free photos to use in commercial works. This came up

https://pixabay.com/photos/earth-map-summer-july-continents-11048/

![image](https://user-images.githubusercontent.com/10197672/64080883-d2d39180-ccad-11e9-8e6e-9b78661018ab.png)
