### ISSUE TITLE
Use favicons for the github io pages

### ISSUE THREAD

**Issue by trevordblack** [RayTracing/raytracing.github.io#911]
Create favicons that can be used in github io pages.

**Comment by trevordblack** [comment]
@hollasch  Take a look at these two:
The same picture sent through different favicon generators on the web

https://realfavicongenerator.net/favicon_result?file_id=p1feqc0ggsv1h1lsskpn1h5a1glf6
[favicon_package_v0.16.zip](https://github.com/RayTracing/raytracing.github.io/files/7111080/favicon_package_v0.16.zip)

http://faviconit.com/en
[faviconit(2).zip](https://github.com/RayTracing/raytracing.github.io/files/7111081/faviconit.2.zip)

I'm not sure if we can/should just prepend html to markdeep, or if it's even necessary

**Comment by trevordblack** [comment]
I'm just going to ping morgan mcguire on twitter

**Comment by trevordblack** [comment]
We might have to create 3 html files (one for each book) that are just stubs with favicons that `htmlinclude\` the markdeep content for each book

**Comment by trevordblack** [comment]
From Morgan on twitter:
```
You can directly put <link rel="icon" type="image/png" href="favicon.png"> in the Markdeep document. Most browsers will automatically grab "/favicon.png" or "/favicon.ico" from your server as well (does not help you on http://github.io, though).
```

So I think we want something like

```
<!-- Markdeep: https://casual-effects.com/markdeep/ -->
<link rel="icon" type="image/png" href="favicon.png">
<link rel='stylesheet' href='../style/book.css'>
<style class="fallback">body{visibility:hidden;white-space:pre;font-family:monospace}</style>
<script src="markdeep.min.js"></script>
<script src="https://morgan3d.github.io/markdeep/latest/markdeep.min.js"></script>
<script>window.alreadyProcessedMarkdeep||(document.body.style.visibility="visible")</script>
```

In each of the three books.

I want the same favicon across all 3 books (and the index.html).
@hollasch What do you think would make for a good favicon? I've played around with a bunch of our images, and they all look illegible at 32x32. Do you have any insight here?

**Comment by hollasch** [comment]
Given the size constraints, I'd think either a simple specular ball, or perhaps a white "R" on a black background (same as title font).

**Comment by trevordblack** [comment]
How about


![favicon](https://user-images.githubusercontent.com/10197672/134791546-666716d3-ecbf-40a4-851a-88d1725f52c4.png)

**Comment by trevordblack** [comment]
We can add the favicon html tag above or below the markdeep.

I opted to put it above because it takes a second or two for the markdeep to parse and load.
If the favicon is below the markdeep, the rendered  favicon is at first the default (no favicon found), before being rendered _after_ the markdeep loads.

By opting to put the favicon above the markdeep the rendered favicon changes immediately and remains the same as the markdeep body is rendered.

Regardless of
1. Favicon tag above or below the markdeep
2. Choice of favicon

This represents a viable (and probably final) means of adding favicons to our text

**Comment by hollasch** [comment]
Awesome. I think I'd prefer a uniformly colored sphere with a nice sharp specular highlight, but getting this in at all is more important and we can kick around actual icon content later.

**Comment by trevordblack** [comment]
I just saw this suggestion:
> perhaps a white "R" on a black background (same as title font)

and I quite like it

**Comment by hollasch** [comment]
Good enough. We settle with 
![favicon](https://github.com/RayTracing/raytracing.github.io/assets/313871/edab25f5-56e4-44c0-aed2-ed4e55cf9c3b)
