### ISSUE TITLE
The perlin_interp function not returning correct values?

### ISSUE THREAD

**Issue by 40163650** [RayTracing/raytracing.github.io#92]
When I followed the tutorial in the book, I found that just before the turbulence is added I encountered some issues with my scene not rendering correctly.

I expected it to look like this:
![screenshot_1_expected](https://user-images.githubusercontent.com/12065481/48987023-f3652e80-f112-11e8-82cf-0a1d10cc07e6.png)
What I actually got was this:
![screenshot_1_actual](https://user-images.githubusercontent.com/12065481/48987032-00821d80-f113-11e8-9ecb-a9ae5708ae7f.png)

After continuing the tutorial to the turbulence section, I noticed that fabs() was used on the accumulated total. I wondered if this would fix my issue with the perlin_interp function (i.e. noise.noise() not noise.turb()), so I used it at the end there.

It did get rid of the black boxes but the result was also still not quite what was intended:
![screenshot_1](https://user-images.githubusercontent.com/12065481/48987116-d3823a80-f113-11e8-9456-ddf266fe197a.png)

Perhaps this is because I used a scale value of 1, but setting it higher leads to results more similar to using turbulence.

**Comment by hollasch** [comment]
Fixed in #261, development branch.
