### ISSUE TITLE
Lighting Oversaturation Problem

### ISSUE THREAD

**Issue by pkudva** [RayTracing/raytracing.github.io#93]
After working on the Cornell box, I noticed some trouble with the lighting, especially when I had a large light, which in the book said would help with the noise. I replaced one of the boxes with a glass sphere and noticed the obvious problem with the light of my image. Even with 1000 secondary rays, it didn't fix it.

![HQ_with_light_artifact](https://user-images.githubusercontent.com/15827339/54508262-962ffb80-4902-11e9-9a23-58676ac9c142.jpg)

I eventually figured out that there needed to be a value cap on the colors, so it wouldn't oversaturate. This might have been covered in the next book "Ray Tracing the Rest of Your Life", but with the final image of this book having a glass sphere and a very bright light, I figured it might be useful to mention it. 
Here's my final image with that color cap:
![HQ_final_product](https://user-images.githubusercontent.com/15827339/54508485-4998f000-4903-11e9-8c55-52bd8e6138ca.jpg)

**Comment by hollasch** [comment]
See pull request https://github.com/RayTracing/TheRestOfYourLife/pull/5

This isn't the solution, but contains valuable information. I have a solution sketched out in the original book repo, and will resurface it here after the v2 release to web.

**Comment by hollasch** [comment]
Resolved in #226
