### ISSUE TITLE
Book 3: estimating half-way point has wrong complexity

### ISSUE THREAD

**Issue by spkersten** [RayTracing/raytracing.github.io#930]
Here:
https://github.com/RayTracing/raytracing.github.io/blob/dev-major/books/RayTracingTheRestOfYourLife.html#L935
the text mentions that the code in Listing 12 has complexity `O(N^2)`. However, the two for loops are `O(N)` and the sort is `O(N log N)`, so isn't the complexity `O(N log N)`?

**Comment by trevordblack** [comment]
Ahh, GREAT CATCH.

I'm pretty sure you're right about this. I'll need to double check what I was thinking when I wrote that.

Also, thank you for checking against the `dev-major` branch!
