### ISSUE TITLE
Book 3: Not actually sampling from uniform PDF

### ISSUE THREAD

**Issue by spkersten** [RayTracing/raytracing.github.io#933]
This listing in the section about "Using a Uniform PDF Instead of a Perfect Match":
https://github.com/RayTracing/raytracing.github.io/blob/62ce2e6a1f08b4c103808e513dc1c8fc6a188776/books/RayTracingTheRestOfYourLife.html#L1631-L1656
doesn't seem to actually sample using a uniform PDF. It still samples from `rec.normal + random_unit_vector()`, so cosine-weighted. The PDF value, `pdf = 0.5 / pi;`, is set as-if it was sampled uniformly. The final image looks good, because the error is cancelled by a wrong `scattering_pdf` of `0.5 / pi`. That should remain `cosine/pi`, irrespective of which sampling PDF is chosen.

**Comment by spkersten** [comment]
Off topic: Since I'm only reporting things that I think are wrong, which feels rather negative, I want to say that I'm really enjoying these books. This is one of the nicest programming projects I've done so far.

**Comment by trevordblack** [comment]
Nah, you're good. I need to go through and do a final check on book 3. I'm just procrastinating as I know that it's still quite rough

**Comment by trevordblack** [comment]
I merged your PR before realizing that I shouldn't have

**Comment by trevordblack** [comment]
It looks like your code is right, but I might be making infrastructure changes.

The mistake that your code is fixing should never have occurred, so I need to do some code refactoring to simplify.
