### ISSUE TITLE
Lighting bug

### ISSUE THREAD

**Issue by adihodos** [RayTracing/raytracing.github.io#94]
Hi! I ported this to Rust (https://github.com/adihodos/raytracer.git), all went pretty smooth (I even added multithreadead support) until I added lighting support. Raytracing the Cornell box results in this ugliness :
![raytraced](https://user-images.githubusercontent.com/155867/54824392-75292b00-4cb3-11e9-8a4f-0e3fbcf8c5a4.png).
Can you give me some hints as to why this is happening ?

**Comment by hollasch** [comment]
Duplicate of #93
