### ISSUE TITLE
Little spheres float above the big world sphere

### ISSUE THREAD

**Issue by ahcox** [RayTracing/raytracing.github.io#948]
From viewpoints around the edge of the scene, the little spheres float far enough above the big world sphere to see under them. 

![Screenshot from 2021-10-19 20-23-55](https://user-images.githubusercontent.com/1584013/137985536-b334bb7f-0342-41e3-867f-37d43a9a6fae.png)

It is a noticeable separation even from the default viewpoint:

![inOneWeekend_stick_down](https://user-images.githubusercontent.com/1584013/137985255-a8b882d4-776c-4d6f-a372-ef90542c7b8a.gif)

The following change fixes this issue: https://github.com/RayTracing/raytracing.github.io/pull/947

**Comment by hollasch** [comment]
Comment from @trevordblack in the pull request:
> You're right that they aren't flush, but that's not the point.
>
> It's cool that you figured out how to solve for this, but it's not really a problem. And it doesn't really negatively affect the text or the code.
>
> The books are full of little hacks and shortcuts that get to the learning as fast as possible while introducing a few simplifications.
> We try to make sure these simplifications are in the stuff that isn't graphics related.
> This is a good example of that. You're right that it's "wrong" in that it isn't flush with the sphere, but this hack exists because it's simple, and it encourages people to fix it on their own if they discover it.
