### ISSUE TITLE
bounding_box function in bvh_node has confusing naming

### ISSUE THREAD

**Issue by anazli** [RayTracing/raytracing.github.io#95]
The **bounding_box** virtual function is declared in the **bvh_node** class  as

 `virtual bool bounding_box(float t0, float t1, aabb& box) const;`

but is defined outside the class as 

`bool bvh_node::bounding_box(float t0, float t1, aabb& b) const {
    b = box;
    return true;
}`

where **box** is a member variable of the class. I think the member should be declared as **m_box** and the last parameter of the function as **box** (as it is in the pure virtual function).

**Comment by hollasch** [comment]
Fixed in PR #241, development branch.
