### ISSUE TITLE
Book 1: misleading unit_vector() in vec3.h

### ISSUE THREAD

**Issue by xyq1113723547** [RayTracing/raytracing.github.io#961]
The book Ray Tracing in One Weekend defines unit_vector() in vec3.h:  
```
inline vec3 unit_vector(vec3 v) {
    return v / v.length();
}
```
However, this function will not return the normalized vector, since v.length() will always return 3 here.  
This is similar to the question in here: https://stackoverflow.com/questions/53094137/is-there-a-function-to-calculate-this-unit-vector-in-glm  
The book probably should use the following function  
```
inline vec3 unit_vector(vec3 v) {
    return glm::normalize(v);
}
```

**Comment by trevordblack** [comment]
Sorry, what?

Our length function is defined here:
https://github.com/RayTracing/raytracing.github.io/blob/master/src/common/vec3.h#L51

**Comment by xyq1113723547** [comment]
My bad. In my code, length() is defined by glm.
Thank you very much for correcting me!
