### ISSUE TITLE
Rotating cube by more than 45 degrees results in incorrect image

### ISSUE THREAD

**Issue by Morozov-5F** [RayTracing/raytracing.github.io#965]
I've discovered this bug when I was working on my version of my path tracer.

When I create a sample scene with a single cube and rotate it around by more than 45 degrees the reference implementation produces interesting results (one side of the cube is shaded for some reason):
![image](https://user-images.githubusercontent.com/1385292/143787096-ad894388-222d-4dbd-b3e5-3aab070ebe17.png)

Here's a code to recreate this simple scene: 
```c++
 auto green = make_shared<lambertian>(color(.12, .45, .15));
 auto cube = make_shared<rotate_y>(make_shared<box>(point3(-1, -1, -1), point3(1, 1, 1), green), 45);
 world.add(cube);
 background = color(0.70, 0.80, 1.00);

 aspect_ratio = 1.0;
 image_width = 200;
 samples_per_pixel = 50;
 lookfrom = point3(0, 5, -20);
 lookat = point3(0, 0, 0);
 vfov = 20.0;
```

I believe that is because of a typo when [setting the front face](https://github.com/RayTracing/raytracing.github.io/blob/659398e72746b9bf98bfd5414604e383a43f4833/src/TheNextWeek/hittable.h#L163) in the `rotate_y` class: 
```c++
rec.set_face_normal(rotated_r, normal);
```

The function uses the rotated ray to set the front face but we've already rotated the normal back to the supposed position. I believe that either we need to use the original ray when setting the front face or we should set the front face first and rotate it back afterwards. I tried the first approach because it seemed easier and the rotations work as expected:

![image_fixed](https://user-images.githubusercontent.com/1385292/143787397-ffb89acc-fa90-46b5-aaea-05768599df40.png)

I can submit a PR with fixes if this is indeed a bug.

**Comment by hollasch** [comment]
Are you basing this on v3.2.3 (the latest public version) or on the code in the `dev-major` branch? I seem to recall that we addressed this a while ago.

**Comment by Morozov-5F** [comment]
I was trying that on the latest release (which, I believe is 3.2.3). I'll try to reproduce it in the latest dev.

**Comment by Morozov-5F** [comment]
@hollasch Yep, latest dev-major doesn't have this bug anymore, thanks for pointing that out! I believe that we can close this.
