### ISSUE TITLE
[Book The Rest of Your Life]: Listing 35: `pdf_ptr` 0 vs nullptr

### ISSUE THREAD

**Issue by D-K-E** [RayTracing/raytracing.github.io#966]
The Listing 35 in the book The Rest of Your Life assigns `0` to `pdf_ptr` of `metal`, and `nullptr` to that of `dielectric`. There is very little difference in the result but since we are passing it `shared_ptr` to `mixture_pdf`. It might be better to use just `nullptr`

**Comment by hollasch** [comment]
Fixed in branch `dev_major`.
