### ISSUE TITLE
Improve Hand Drawing Figures

### ISSUE THREAD

**Issue by AmirhosseinAzimyzadeh** [RayTracing/raytracing.github.io#982]
I'm not sure if it's an issue, but these hand drawings can be replaced with more clean and clear illustrations.
I'm able to redesign them if you're OK with that.

here are some figures that I redesigned on Figma:
https://www.figma.com/file/mGsrgpPGktGnGYnGe8SJsz/Ray-Tracing-book?node-id=0%3A1

![fig-1 09-rand-vec](https://user-images.githubusercontent.com/39561409/149460588-84fe1cfa-456c-4a48-8262-aef4824b6a2d.jpg)
![fig-1 05-sphere-normal](https://user-images.githubusercontent.com/39561409/149460648-6e8efc44-5e08-4c87-88f5-59d1ecb82adf.jpg)
![fig-1 06-normal-sides](https://user-images.githubusercontent.com/39561409/149460649-5e7f071d-ba38-41af-afce-4e93973bb3f7.jpg)

**Comment by hollasch** [comment]
Thank you for the offer, Amirhossein. The hand-drawn "whiteboard" style illustrations are actually part of the style of the books, which started out as an experiment to see how lightweight Peter Shirley could make the whole book writing process. Now Trevor and I (the co-authors) try to maintain this style as we go. Our goal is to maintain fidelity while keeping the illustration process lightweight. So while we appreciate your offer, we'll stay with the current style.

That said, please let us know if you find an illustration lacking in some way, or incorrect.

**Comment by AmirhosseinAzimyzadeh** [comment]
I understood, thanks for your answer.
