### ISSUE TITLE
Book 3.10.1: `camera::ray_color()` switches from `double pdf` to `double pdf_val` halfway through

### ISSUE THREAD

**Issue by trevordblack** [RayTracing/raytracing.github.io#988]
Pick one of the above and make it consistent.

**Comment by hollasch** [comment]
This is a local variable in `camera::ray_color()`. Also confusing versus `hittable::pdf_value()`.

**Comment by hollasch** [comment]
`pdf` clashes with the class name. `pdf_value` clashes with `hittable::pdf_value()`, though that should be ok as a local name.

**Comment by hollasch** [comment]
Ugh. The `material` classes all use `pdf` as the PDF value parameter. I think I'll let these slide for now.

**Comment by hollasch** [comment]
Done.
