### ISSUE TITLE
where is aabb.h?

### ISSUE THREAD

**Issue by m4r35n357** [RayTracing/raytracing.github.io#994]
I cut & pasted the code from web pages rather than using the sources direct.  On one occasion when something didn't work I _did_ have a quick look at the sources, but stopped when I couldn't find aabb.h, _which I use_!

I had a quick look to see if it had been moved to another file, but I don't know how to grep github ;)

So, where is the aabb class?

**Comment by TheRayTracer** [comment]
In the common directory - https://github.com/RayTracing/raytracing.github.io/blob/master/src/common/aabb.h

**Comment by m4r35n357** [comment]
Ah, OK thanks, I don't have that directory structure as I used the book instead of the source.  Thanks!
